### ISSUE TITLE
Jenkins is doing his imitation of a stranded whale again

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN#1071]
It took a _lot_ longer this time \o/

I tried poking the stop buttons as was desbribed in the wiki [here](https://github.com/KSP-CKAN/CKAN/wiki/Configuring-Jenkins#restarting-docker-slaves) but it seems to not have much of an impact.

Summoning @hakan42 seems to be the appropriate action.

**Comment by hakan42** [comment]
Who will take the appropriate action  (whatever that might turn out to be) later today. Sorry, far away from real computer access atm

**Comment by Dazpoet** [comment]
No hurries, I'm busy "playing" KSP aka fixing whatever it was I broke when I set up pruning and configs :p

**Comment by Dazpoet** [comment]
It is intermittently throwing a stack trace the size of a phonebook when I go to the docker stop/start page and it all seems to be about being out of space so I'd say that's probably the problem :)

**Comment by techman83** [comment]
Out of disk space. Cleared things up, restarted it and nudged the slaves back into life.

**Comment by Postremus** [comment]
Why does the Jenkins not automaticly clear things up? How much disk space has jenkins overall?

----- Ursprüngliche Nachricht -----
Von: "Leon Wright" <notifications@github.com>
Gesendet: ‎05.‎06.‎2015 07:37
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Betreff: Re: [CKAN] Jenkins is doing his imitation of a stranded whale again(#1071)

Out of disk space. Cleared things up, restarted it and nudged the slaves back into life.

**Comment by techman83** [comment]
It's not really Jenkins, it's other things on the host that are in the progress of being migrated away.

**Comment by Dazpoet** [comment]
Yay Jenkins is working, closing this until it happens again :wave: :+1: :fish:

**Comment by techman83** [comment]
> _Caaaan yoooou giive uuuus moooore spaaaaace_
> - Dory

That's the problem in a nutshell. MirrorKAN still appears to be running on that host. Along with the AWS mirror.
```
-rw-r--r-- 1 mirror mirror  1.8M Jun  9 07:37 netkan_log.txt
```
I don't seem to be seeing where it's being called from and it's going to always whittle away the space. Even if I clear out mods (which I'd rather do when we confirm we have all of them on the other mirror) it's going to start populating them again next run and put us in the same position.

Some of the logging is also hosed due to it being out of space, so it's hard to get a complete picture of what is going. So I'm a little flummoxed.

I think we need to have a serious look at what Jenkins is being used for, because the Jenkins infrastructure has acquired quite an amount of technical debt that is becoming unfeasible to maintain.

**Comment by techman83** [comment]
I cleared a little more space out. But I'd suggest it'll only buy us a day or two.

**Comment by hakan42** [comment]
@techman83 , Mirrorkan is started hourly from the root crontab (I see that it is already disabled there) and from the webhook (I see that the webhook is still running, you might want to kill it)

**Comment by techman83** [comment]
Oh, that's why I'm not seeing it. Let me go kill the webhook!

**Comment by techman83** [comment]
Killed! thanks @hakan42

**Comment by Dazpoet** [comment]
Jenkins is currently working so I'll close this until it happens again :)
