### ISSUE TITLE
Is "identifer" case-sensitive?

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#1119]
In the main ckan-repository there are mods providing identifiers which are the same as the identifier of existing mods if case is ignored.
In my opinion it would be strange if "MyMod" is distinct from "mymod" and both coexist in the index. So I would suggest to define identifiers as case-insensitive.

Please define in the Spec if identifiers are case-sensitive.

**Comment by pjf** [comment]
Hello from me teaching in Canberra,

As far as I know we've always treated identifiers as being case sensitive,
and I'd argue this should be the case as the metadata is intended for
machine consumption, and not solely by our own systems.

If the extant clients are treating them as case insensitive then that would
be good to know. :)

Yes, we should absolutely define this in the spec.

**Comment by janbrohl** [comment]
To be more precise: I stumbled upon mod "ContractConfigurator-SCANSat"  compared to "ContractConfigurator-SCANsat" being provided.

As the spec says "For most mods, this means the identifier should be the name of the directory in GameData in which the mod would be installed, or the name of the .dll with any version and the .dll suffix removed." and at least on Windows pathnames are case-insensitive "MYMod" and "MyMod" propably (if they use the simple setup) cannot be installed at the same time the way I understand it even though they currently can coexist in the repo. So actually it can be useful to require identifiers to be unique ignoring case  And if they are - why not define them as case-insensitive for referencing, too?

**Comment by plague006** [comment]
The identifier being the same as the folder name isn't a requirement, just a typical convention. If the identifier has the same name as the install folder there is less information required in the metadata. We also tend to like having the mod identifier be the same as the installation folder since it makes searching for the appropriate identifier easier for all.

As to identifiers themselves, as pjf mentioned they should be case-sensitive for consistency at a machine level, but each identifier should also be unique at a case-insensitive level for human readability (and windows).

I corrected the ContractConfigurator-SCANsat cases, if there are any more I'd be happy to know about them as well.

**Comment by plague006** [comment]
#889 has more information about case sensitivity. But I'm closing this as the question is answered: `identifier` is case sensitive. Thanks again for spotting the inconsistency in `ContractConfigurator-SCANSat`

**Comment by plague006** [comment]
As far as adding it to the spec, I'll put in a PR.
