### ISSUE TITLE
(De)select all button

### ISSUE THREAD

**Issue by RichardLake** [KSP-CKAN/CKAN#1148]
It would be useful to have a button to select/deselect all the mods on the recommend and suggests screens.

**Comment by Postremus** [comment]
such a button is everywhere usefull. for example, when you want to deinstall all installed mods.

**Comment by RichardLake** [comment]
#1211 Adds a delectect all button to the main mod list not the recommends/suggests window.

**Comment by plague006** [comment]
We now have a (de)select all button available for recommends and suggests. We don't have one available in the main mod screen because:

1) wanting to uninstall all mods is very uncommon and we would be better served by a button/function that does explicitly that
2) it's not possible to use it in a "select all" context as you would inevitably create conflicts when trying to install every mod
3) a (de)select all button would almost certainly be mistaken for a "revert all install/uninstall changes" button where a user expects their currently installed mods to remain intact.

With all that established, closing this but certainly open to the idea of a "uninstall all"-type option.

**Comment by politas** [comment]
Select All could be useful if applied to a filtered list based on the "filter by" fields.

**Comment by plague006** [comment]
Can only speak for my own habits, but I usually filter with a single mod in mind. That said I don't represent everyone, so re-opening.

**Comment by politas** [comment]
I can easily see someone deciding they want all of Roverdude's mods, for instance - They generally make a useful combined set.

**Comment by ayan4m1** [comment]
Yes, I would use this with the filter box to select small batches of mods at once using a common search term. I understood that it wasn't trivial to add to this app in particular, but I was missing the ability to find 10 mods and check them all at once.

If you wanted to "uninstall all" then you'd set the filter type to be Installed and then hit the "deselect all shown" button.

From a UI perspective I think changing the "Installed" column to have a checkbox would keep things small. It also means the "de-select all" checkbox can go away assuming the two tabs are using the same grid control.

I think the workaround for the "trying to change the dependency tree state too much at once" issue will be to uncheck each item individually and allow the state to settle without enforcing deps, but that will probably decrease the speed/efficiency of the operation and I haven't looked at the ckan.dll API much yet.

I don't want to bring an opinionated pull request so I am hoping to get a little more feedback from everyone using my half-baked ideas at solving this as a lightning rod.
