### ISSUE TITLE
Update Metadata to Better Handle New KSP Versions

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/CKAN#1156]
So KSP 1.0.3 came out a few hours ago and there are already 228 mods compatible with it in CKAN! Only problem is that a lot of these mods are old (sometimes *ancient*) versions of mods.

Here's a small sampling of old versions of mods offered to me with KSP 1.0.3 from my install list before I got bored looking for them:

- AntennaRange (1.8a)
- Chatterer (0.9.0)
- CollisionFX (3.0.1)
- DockingPortAlignmentIndicator (4.0)
- EditorExtensions (2.7)
- FinalFrontier (0.7.9-972)
- ImprovedChaseCamera (1.4.0)
- InfernalRobotics (v0.21)
- KIS (1.1.1)
- MechJeb (2.5.0)
- OuterPlanetsMod (1.6.5)
- PilotAssistant (1.5.5)
- PlaneMode (0.4.1)
- PlanetShine (0.2.2.3)
- RasterPropMonitor (v0.19.3)

I think this is *huge* problem because we're giving people old, buggy versions of mods that will likely cause an untold amount of angst as users become frustrated that mods aren't working, then they complain to modders, and modders spend who knows how much time trying to figure out why bugs they thought they fixed have regressed. Needless to say this doesn't endear us to modders.

Most of these are caused by old versions of mods either having a `ksp_version_min` without a corresponding `ksp_version_max` or targeting a version like `1.0` while newer versions target `1.0.1` or `1.0.2`.

I propose the following solutions:
1. As a matter of policy prohibit specifying `ksp_version_min` without also specifying `ksp_version_max`.
2. As a matter of policy prohibit specifying a `ksp_version_max` for an unreleased version of KSP.
3. Modify the version matching algorithm in the CKAN client so that `"ksp_version": "1.0"` does not match for *any* `1.0.x` release.
4. Modify the `$vref` code so the maximum `ksp_version_max` it generates is the currently released version of KSP, regardless of what's specified in the `.version` file.
5. Undertake a cleanup of the existing metadata to make it comply with the above policies.

The downside? Brand new releases of KSP will have 0 supported mods in CKAN, which I think is **OK**. I think that's a better world to be in than one where brand new releases of KSP get old buggy code.

**Comment by pjf** [comment]
So the problem here isn't the mods which are genuinely version-independent (like flags), but ones which specify a min version but no max version?

We *do* have things like "ksp_version: 1.0" matching any 1.0.x release on the expectation that point releases for KSP won't necessarily break compatibility. Word on the street was that most 1.0.0 mods worked fine in 1.0.1, and so on. There are some mods from 0.23 days that *still* legitimately work under modern KSP releases. However it's pretty clear it's a mistake when we ignore a more recent release to offer an *old* release because it has a more generalised version tag; this is the case with Chatterer (0.9.0 marked as "1.0", and 0.9.4 marked as "1.0.2").

I'd counter-suggest the following:

**netkan.exe:** KerbalStuff seems to leave off the `.0` after new major KSP releases. Lots of our indexing is off because of that. Therefore `netkan.exe` should *add* the `.0` when it sees a version from KS.

**metadata health:** It's almost certainly a mistake if a *new* release of a mod contains an exact version string that would also have been matched by an *older* release of the same mod with a generalised version string. We can write a tool to check for this, and we should examine (and fix) the metadata we find.

Together, I think these we catch the vast majority of mistakes, without limiting what people can do with the metadata.

I don't think we should be prohibiting metadata containing future KSP releases, because modders who are also members of the testing team can genuinely release mods which are future-compatible. Likewise we do have old mods which really have continued to work fine on new releases; in those cases users aren't getting an older version of a mod when they wanted a newer one. They're instead getting the *same* older version they've always enjoyed.

> The downside? Brand new releases of KSP will have 0 supported mods in CKAN, which I think is OK.

Heh, you should try spending any times near our users after a new KSP release. :) The complaint that so few mods are available even though they *obviously* work in the new version fills pages of my inbox, along with cries that the CKAN shouldn't enforce checks on the KSP version *at all*. Sometimes we even get pull requests removing the version checking code.

That reminds me. I should add the instructions on how to force-install mods to the FAQ, given we've just had a new KSP release and everyone will ask that again.

**Comment by dbent** [comment]
:+1: from me

**Comment by pjf** [comment]
Have code to find erroneous versions, patch incoming

**Comment by Dazpoet** [comment]
This sounds amazing, many of these problems also arised when 1.0.0 came about but I had no idea how to explain the issue well enough. Happy to see it being worked on! :+1:

**Comment by pjf** [comment]
Metadata side of this is done (KSP-CKAN/CKAN-meta#607). Now we just need to adjust netkan.exe. :)

**Comment by janbrohl** [comment]
A field for the last modification date of the metadata (see #1116 ) or for the mod-version itself could help identify mod-age independently of declared KSP version compatibility. This way a warning can be issued for mods which are _propably_ unmaintained, outdated or something like that.

**Comment by sarbian** [comment]
I am not doing 1 PR for each of my mods to change ksp_version_max each time a minor KSP fix is out.

**Comment by pjf** [comment]
@sarbian: We absolutely don't want you to do that either! :) Most of this ticket involved the interaction between `netkan.exe` and KerbalStuff with .0 releases. Since we've patched the extant metadata and our indexer itself, it shouldn't re-occur.

@dbent : Look at how quickly #1173 came in! :) :)

**Comment by awdAvenger** [comment]
EditorExtensions version 2.2 is listed as compatible with 1.0.4 due to only version_min being set.

**Comment by dbent** [comment]
KSP-CKAN/CKAN-meta#623 is tracking promiscuous versions
