### ISSUE TITLE
Allow Netkan per-version overrides

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#1160]
Sometimes we'd like to override what data `netkan.exe` indexes for a single version. For example, if an existing release works with newer KSP releases.

I think a good solution is to update `netkan.exe` so that we can add version-specific directives. I'm going to propose te `x_netkan_override` field, which does an exact version comparison, and if successful uses the override segment to replace existing fields as the final step before writing (ie: after KS, AVC, and other expansions):

```
"x_netkan_override" : {
    "version" : "1.4.2",
    "overide" : {
        "ksp_version_min" : "1.0.0",
        "ksp_version_max" : "1.0.3"
    }
}
```

Then if we see that precise version of a mod being released (which includes reindexing what we already have) then we can change what we spit out. If we see any other version we ignore the override and proceed as normal.

Originally discussed in KSP-CKAN/CKAN-meta#608.

**Comment by dbent** [comment]
How about multiple overrides and version ranges? I've seen a few times where @Dazpoet has had to
freeze/stage changes to `.netkan` files because mods were undergoing major changes to their metadata in upcoming releases. It would be handy to specify these changes ahead of time, and know they'd only be applied when the new version is released, cutting down our Time-to-Accurate-Metadata (**TAM**, new acronym I'm inventing it) drastically. This also makes the `.netkan` more complete historically rather that only being usable for the current release. 

For example:

```json
{
  "x_netkan_override": [
    {
      "version": "<1.0.0",
      "override": {
        "depends": [
          { "name": "AwesomeMod" }
        ]
      }
    },
    {
      "version": [ ">=1.0.0", "<2.0.0" ],
      "override": {
        "depends": [
          { "name": "AwesomeMod", "min_version": "1.0.0" },
          { "name": "AmazingMod" }
        ]
      }
    },
    {
      "version": ">=2.0.0",
      "override": {
        "depends": [
          { "name": "AwesomeMod", "min_version": "3.0.0" },
          { "name": "AmazingMod", "min_version": "2.0.0" }
        ]
      }
    }
  ]
}
```

In this example I'm using a new syntax for expressing version ranges so that both inclusive and exclusive comparisons can be made.

The question I have is whether these overrides are straight up key replacements (i.e. an *override*) or actually a merge, i.e. if an override specifies a `depends` list, is that list merged into the non-override `depends` list or does it completely replace it. Thinking about it, not-merging is far simpler and may be easier for someone just looking at the metadata to understand. 

This would also be useful for #865.

**Comment by pjf** [comment]
@dbent : Have I told you recently how awesome you are? Because you're friggin' awesome.

I think we should go the *replace* route, at the top-level of the datastructure, because:

- It's easier to code and understand.
- It means that fields can be removed in an understandable way.

The second point here is important, because without it there's no good way to *remove* a relationship for a given version.

I may take a stab at this on the weekend (if it's not already done by then) as it lets us solve a *lot* of metadata issues in a TAM-friendly way. :)

**Comment by pjf** [comment]
I have a work in progress for this which I'm currently testing.

**Comment by pjf** [comment]
Adding a `delete` keyword as well, as I've just discovered that with the current spec there plenty of times we want to delete some keys and add others (eg: remove `ksp_version`, and add min/max versions).

**Comment by pjf** [comment]
WIP on the `1160_netkan_version_override` branch. So far it's looking really promising (I'm testing on TACLS, and it's producing the right results), but I want to litter the code with tests first. :)

**Comment by dbent** [comment]
:+1: :cake:

**Comment by Dazpoet** [comment]
Aww yiss! Can't wait to try these things out :+1:
