### ISSUE TITLE
Versions for "provides"?

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#1165]
Currently there is no way to declare which version of a mod is provided if using "provides".

Is this supposed to be that way?

**Comment by pjf** [comment]
At the moment yes, because we've [adopted the Debian spec](https://www.debian.org/doc/debian-policy/ch-relationships.html#s-virtual) for relationships in general. I'm not strongly attached to the position, but it does mean extra complexity, as actual and virtual packages may differ in version number, and specifying a provides-with-version is likely trying to signal that it can completely replace another package along with low-level functionality (eg: `provides ModuleManager 1.2.3`), which may be the case but so far as been rare.

I'm not actually sure what our relationship resolver does when asked to check a relationship that targets a provided package that also includes a version number. I know that Debian ignores provided packages if a version number is specified, but I suspect what we do at the moment isn't particularly well defined.

It's also worth looking forward to when we may be able to have migration packages in the future, with something similar to Debians [provides-conflicts-replaces](https://www.debian.org/doc/debian-policy/ch-relationships.html#s7.6.2) relationship, although I suspect whether or not version numbers are used for these is mostly academic.

**Comment by pjf** [comment]
Closing out old tickets. If I've closed this one in error, let me know and I'll reopen.
