### ISSUE TITLE
CKAN shouldn't try to write files to drives that don't have enough free space

### ISSUE THREAD

**Issue by gsarducci** [KSP-CKAN/CKAN#1236]
I have CKAN in a local h:/KSP directory.  Upon executing an install of Realism Overhaul using CKAN, it begins dumping temp files into G:/AppData/Local/Temp.  This drive is in reality a dummy partition for a Linux boot that only has 256MB of space, so predictably it runs out of space and CKAN nukes with an exception.

**Comment by gsarducci** [comment]
![image](https://cloud.githubusercontent.com/assets/9887345/8506630/e99f1bc4-21e3-11e5-9f42-5ce20e600e4f.png)

**Comment by gsarducci** [comment]
![image](https://cloud.githubusercontent.com/assets/9887345/8506638/43a5cf1e-21e4-11e5-8c42-4cb499e04864.png)

**Comment by Postremus** [comment]
Does this also happen when you try to install RO using the cli?

**Comment by Postremus** [comment]
"ckan install RealismOverhaul" should be the command for doing that.

**Comment by gsarducci** [comment]
Ran command line and it threw a different error, but I did watch the G: drive as it was happening and it still was depositing temp files in there.  This time though when the program stopped it cleaned up.  The GUI didn't, instead leaving all the temp files in there.  Anyway, screen shot coming.

**Comment by gsarducci** [comment]
![image](https://cloud.githubusercontent.com/assets/9887345/8508290/233d38a6-2230-11e5-87c1-b5014ac37575.png)

**Comment by gsarducci** [comment]
Interestingly, if I run it a few times via CLI it works.  I imagine it's because it already has some of the data downloaded so every time I go to run it it has to fetch less and eventually can accomplish what it needs to do within the limitations of the "G" drive.

**Comment by Dazpoet** [comment]
An explanation to the above is probably that it downloads one/a few mods and upon nuking itself with the exception moves all already done downloads to the cache. So every attempt you finish part of the process, just like you thought :)

**Comment by politas** [comment]
Has this been sorted out by #2535 and #2536?

**Comment by HebaruSan** [comment]
No, I don't think so. The `AppData/Local/Temp` part of it sounds like this is happening during the download itself, which saves to a temp file (from `Path.GetTempFileName()` or `FileTransaction.GetTempFileName()`), rather than when we copy the temp file into the cache.

https://github.com/KSP-CKAN/CKAN/blob/b9a91fa2a3b8780a4f8310127f13cfc6400a816c/Core/Net/NetAsyncDownloader.cs#L48

https://github.com/KSP-CKAN/CKAN/blob/b9a91fa2a3b8780a4f8310127f13cfc6400a816c/Core/Net/Net.cs#L137

In this case the best solution is probably to not configure the Windows `%TEMP%` path to point to a full partition.

**Comment by HebaruSan** [comment]
I don't think it makes sense to try to make downloads succeed with a full system temp folder. The files have to go somewhere.
