### ISSUE TITLE
Manual override of dependencies?

### ISSUE THREAD

**Issue by danheidel** [KSP-CKAN/CKAN#1303]
Is it possible to allow the user to do a manual override of a module's required dependencies?  The Community Resource Pack crashes my game on load and is a required dependency for several commonly used mods.

I can manually install these mods and they seem to work just fine without the CRP.  Right now, I have to fall back to doing manual installs.

Would it be possible to allow a user to override the dependencies?  Obviously, this can cause problems but the user has chosen to take fate into their own hands at that point.

**Comment by pjf** [comment]
The CKAN is pretty insistent about making sure dependencies are installed, so there are a couple of options:

1. If the mods don't absolutely need the CRP, then we can mark it as a recommendation in the metadata, rather than a dependency. (Recommendations are installed by default, but the user can unselect and uninstall them.) This fixes the problem for everyone. :)
2. If that's not appropriate, or you want to test things yourself, you can download the appropriate `.ckan` file [from the metadata repo](https://github.com/KSP-CKAN/CKAN-meta), edit it to remove the dependencies (you can use any text editor), and then `File -> Install from .ckan`. Be aware the files are in JSON format, so make sure you don't have any extra commas (although our parser *might* forgive that, I'm not sure).

The CKAN client might prompt you to reinstall the mod when it detects the metadata upstream is different from what was used locally, but you can decline that to say "yes, I really want my hacked install". :)

**Comment by danheidel** [comment]
Thanks for the fast response!

1) This would be nice but I think the actual mod maintainers should be the arbiters of whether the dependencies are marked as required or not, regardless of whether that the case in reality.  
2) This worked great, if a tad cumbersome.  I assume that when updated versions are added to CKAN, I'll have to add updated .ckan files as well?

**Comment by plague006** [comment]
Yes, you'll have to do that with every update (unless the dependencies change ofc).

**Comment by danheidel** [comment]
Figured.  Oh well, I do full stack JS development for the day job, tweaking some JSON files isn't exactly exotic work for me.
