### ISSUE TITLE
NetKAN shouldn't break compatibility when a mod author updates ksp versions

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/CKAN#1310]
From KSP-CKAN/NetKAN-bot#26

> I noticed this commit: KSP-CKAN/CKAN-meta@7a18901

> Netkan-bot bumped the ksp_version of the mod from 1.0.2 to 1.0.4 because the author updated the kerbalstuff page. The problem is that now the mod can't be installed under 1.0.2 even though we know it's compatible.

> To accommodate people who choose not to upgrade, netkan-bot should probably create a compatibility range (ksp_min and ksp_max) if a ksp_version change occurs without an associated new release.

> - @plague006

**Comment by techman83** [comment]
I'm not sure how we best handle this, NetKAN inflates the metadata as provided by the sources. I'm not 100% familiar with the internals though. @dbent you've spent time on this recently, thoughts?

**Comment by dbent** [comment]
[Inconveiable!](https://www.youtube.com/watch?v=OHVjs4aobqs) Right now it would be impossible to do, NetKAN has no idea what the previously generated metadata was. To accommodate this NetKAN would have to be modified to accept the last generated `.ckan` file as input and the NetKAN bot would have to be modified to provide this to NetKAN (*with* proper version sort order) on execution.

We would also need to consider that the previously generated metadata is just *wrong*, and the reason NetKAN is being executed is to fix the bad metadata, in which case the previous metadata should be ignored.

It would also complicate local testing as the user would have to correctly select the previous `.ckan` to get the same behavior as the bot.

For this specific case I think the changes to Kerbal Stuff described in #1173 are the more elegant solution, allowing mod authors to specify a range of compatibility rather than just a single version.

**Comment by techman83** [comment]
@dbent Indeed. It's likely a bit of an edge case issue and I'd be tempted not to try and make netkan try and guess what is going on as it could produce inconsistent results. At least now it is clear where it's getting its information from.

**Comment by plague006** [comment]
I'm closing this because, while I was the originator of this issue, I realize it's just a flat-out bad idea. We can never be sure *why* a mod author might be changing KSP version compatibility. It's best for us not to play guessing games with authorial intent.
