### ISSUE TITLE
Searching mods by their abbreviation / alternate names

### ISSUE THREAD

**Issue by mongoose11235813** [KSP-CKAN/CKAN#1313]
Is it possible to make a search capable of finding mods by their abbreviations? E.g. Kerbal Attachment System - KAS,  Kerbal Inventory System - KIS and so on.
Some people don't even know/remember whole names of mods because everyone on forums uses abbreviations instead.

**Comment by plague006** [comment]
A full implementation would require a new metadata field (probably inside `resources`) to list alternate names. A much more 'cheaty' (but incomplete) implementation would be adding the alternate names in parentheses to the existing `name` field.

**Comment by Dazpoet** [comment]
One might also consider making the `"provides"` field searchable seeing as some mods acctually have that one. When I first started ckanning I remember thinking it weird that I couldn't search for FAR or NEAR when clearly their metadata include those as alternate names.

**Comment by HebaruSan** [comment]
GUI already does this by pre-calculating the abbreviations:

https://github.com/KSP-CKAN/CKAN/blob/8746077501dcf1edb365230af270c451a0f645e3/GUI/GUIMod.cs#L242-L243

https://github.com/KSP-CKAN/CKAN/blob/8746077501dcf1edb365230af270c451a0f645e3/GUI/MainModList.cs#L745-L750

Closing as fixed by #1430.
