### ISSUE TITLE
CKAN Local Package Installing Plug-in

### ISSUE THREAD

**Issue by Gustavo6046** [KSP-CKAN/CKAN#1314]
I am developing a plugin that lets you install .lpf packages inside the \ckan\Plugins\lpip\packages folder once running one Batch file named lpip.bat. Also included is an lpipins.cmd file that can install the packages directly from Command Prompt and the unzip.cmd used for unzipping operations.
The packages are .lpf files (only .zip files renamed to .lpf to distinguish it from normal zip files and therefore can be opened by 7-Zip) that must be of the same name as the mod's folder to be created inside the gamedata folder, and must be put inside the 'packages' folder by extracting a zip or using an autoextraction program made by the modder. Anything else should be ok. The lpip.bat asks the name of the package to install. Then it uses the unzip.cmd I downloaded somewhere to do the rest of the job. Unfortunately this means it has problems installing mods with multiple folders into gamedata. This is where enters lpipins.cmd which is openable from the command prompt and quickly installs with the following syntax:
lpipins.exe <NameOfPackage>

**Comment by Postremus** [comment]
What do you want to achieve with this plugin?

**Comment by Gustavo6046** [comment]
Installing mods with CKAN using local .lpf (LPIP Package File) files for the case of lack of Internet. Or storing CKAN mods as a local file instead of GitHub repo.

**Comment by plague006** [comment]
CKAn creates a local cache (CKAN/downloads) of mods it downloads. Additionally you can install (most) mods offline via CKAN via command-line `ckan install -c file.ckan> or from the GUI `file -> Install from .ckan...`

I don't see a great use for this, anyone without access to the internet probably isn't relying on a tool such as CKAN which is built around the idea of acquiring mods from the internet.

With that said if the plugin is something you want to make: I wish you all the best with it.

**Comment by plague006** [comment]
I was polite and courteous all day. I'm done. I don't know if me blocking @Gustavo6046 also prevents him from posting in KSP-CKAN but I've blocked him and I'll be shutting down any more nonsense he posts.

**Comment by plague006** [comment]
For context.
He's fighting with another dev over his license and just acting like a troll: https://github.com/Zinggi/UnrealScriptIDE/pull/24
He's trying to drum up support for KSP 1.0.0 which is a version you can't even acquire anymore so he's either a pirate or has sat on that version since April: https://github.com/snjo/Firespitter/pull/122 https://github.com/KSP-CKAN/NetKAN/issues/1939
He's reporting errors for mods to us https://github.com/KSP-CKAN/NetKAN/issues/1937, which is understandable but now in this thread he's going to write a plugin when he has shown in every one of his comments that he has no idea about the community or this project?

Lastly, he's arguably a mysogenist: https://github.com/KSP-CKAN/NetKAN/issues/1939

I don't know why I'm arguing my case so strongly.. his contribution activity log speaks for itself.

**Comment by techman83** [comment]
@plague006 there is a clear [Code of Conduct](https://github.com/KSP-CKAN/CKAN/wiki/Code-of-Conduct) which you can lean on. I think there is a case to made that they were in violation of it. It's really important that all contributors and users feel comfortable being a part of the project.

I don't feel they were making a positive contribution to the project and you've done an exceptional job of being polite and respectful.
