### ISSUE TITLE
RFC: Changelogs with PRs

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#1342]
We make lots of releases, but there's a big big problem with the release process: most of the releases are made by me.

The actual work required to do a release is pretty straightforward: one hits the release button, fills in the release notes and version, and picks a release image. Easy, right?

Well, not quite. Writing release notes is a right pain, and I usually do it by combing through `git log` and looking at merges. However this is error-prone, and there have been times in the past when I've missed or misrepresented changes.

I'd like to change things so that PRs require a changelog entry. This is easy from the bot side of things; we just need a test that checks that our hypothetical `Changelog` file is updated as part of the PR. This means that making a release simply involves copying the contents of the changelog file, or (in an ideal world) having a bot copy the contents for us. This should make the release process easier, and mean our release notes are more accurate.

If anyone can spot any flaws in this plan, do speak up now, but I look forward to the near future where the only thing stopping any collaborator making a release is coming up with a suitably cool release name. :)

**Comment by pjf** [comment]
http://keepachangelog.com/ seems to have some good ideas for this in the modern age.

**Comment by dbent** [comment]
First time hearing about http://keepachangelog.com/ but I agree with most of their points, and what I do with my own projects follows [quite](https://raw.githubusercontent.com/Apokee/HotSpot/develop/CHANGES.md) [closely](https://raw.githubusercontent.com/Apokee/PlaneMode/develop/CHANGES.md).

The biggest difference is that instead of having an **Unreleased** version, I just automatically add the next patch version with an `-alpha` tag, following [semver](http://semver.org/) conventions. I do this because my changelog is actually semantic, my build scripts derive the current version from the changelog (in fact it's the only place in my projects where a version string actually appears). This means that continuous builds can get nice [artifact ](https://ci.appveyor.com/project/Apokee/hotspot/build/107/job/uivjof2mbce9sdia/artifacts) names, that don't match any currently released version.

**Comment by HebaruSan** [comment]
Current status is that every merged PR has an entry added to  `CHANGELOG.md` as per [the process on the wiki](https://github.com/KSP-CKAN/CKAN/wiki/Releasing-a-new-CKAN-client#when-merging-pull-requests):

```
$ vim CHANGELOG.md                                  # Or whatever your favourite editor is, if not vim.
$ git add CHANGELOG.md
$ git commit -m 'Merge #<PR-Num> <Description>'     # This commits the merge, *and* your changes to CHANGELOG.md
```

And [the instructions for releases](https://github.com/KSP-CKAN/CKAN/wiki/Releasing-a-new-CKAN-client#making-a-release) say to copy and paste those entries into the release notes:

> 5. Copy'n'paste in the release notes for this version, usually from the changelog. Add extra notes if necessary.

It's working pretty well. More automation would be neat-o, but the burden is not unbearable.
