### ISSUE TITLE
Installing Realistic Progression Zero and Realism Overhaul does not pull in Real Solar System

### ISSUE THREAD

**Issue by waerloga** [KSP-CKAN/CKAN#1346]
I attempted a fresh install with CKAN 1.12.0, Realistic Progression v0.35, Realism Overhaul v10.2.0.

I the first attempt I had selected just RP-0 and it was missing many recommended mods from Realism Overhaul. @NathanKell stated that CKAN does not pull in second order recommended mods, so I tried again by selecting both RO and RP-0.

It did not attempt to auto install Real Solar System (nor RemoteTech RSS, but that's a obsolete requirement for 1.0.4-based RO/RP-0), it got the other recommended mods however.

**Comment by plague006** [comment]
The good news: CKAN does pull second order recommends (try installing RSS, and because RO is required you'll get recommendations for B9 Procedural Parts and deadly re-entry (among others).

The bad news is that RO doesn't pull in RSS properly because it `depends` on a module that is `provided`.

I created a test branch: https://github.com/KSP-CKAN/CKAN-meta/tree/RO-RSS-test for easy testing.

GUI:
If RO `depends` RSS then as you install RO, RSS will install as expected (you choose a texture pack). If RO `recommends` RSS then RO will present a blank `recommends` page when the install reaches that point (essentially it knows there's a recommendation but can't fulfill RSS' `depends`).

CLI:
In both `depends` and `recommends` the CLI will install RO + RSS as expected.

**Comment by Postremus** [comment]
The solution should be to ask the user before the Installation begins what provider he wants to use.

**Comment by Dazpoet** [comment]
I thought situations like these where solved by https://github.com/KSP-CKAN/CKAN/pull/1002 but that might just be first order? In my naivity I'll just throw out the question if one can make whatever magic happened in #1002 happen in more places in the installation process without blowing things up?

**Comment by HebaruSan** [comment]
> The bad news is that RO doesn't pull in RSS properly because it depends on a virtual module, and the relationship resolver just doesn't accept that.

I believe this was solved in the second side fix of #2577. The original test case here is spoiled because RP-0 now `depends` on RSS (which is automatically added to the change set), but RealismOverhaul still just recommends it, and installing RO shows RSS as a recommendation:

![image](https://user-images.githubusercontent.com/1559108/74176760-f526ef00-4bfd-11ea-934e-c82d23a99de5.png)
