### ISSUE TITLE
Leave older mod's version available

### ISSUE THREAD

**Issue by jenyaza01** [KSP-CKAN/CKAN#1350]
Once some mod is updated, it may lose compatibility with an older version(s) of the game.
Is it possible to update the list of mods that are currently incompatible, for presence of an earlier version of the mod, which were compatible with an older version of the game.
Example: I have version 1.0.2, mod Throttle Controlled Avionics updated to version 1.0.4 and is no longer available for installation. But there was also a compatible version of the mod, which even not contain some innovations, but it CAN be installed. This is better than the "incompatible" and a dash instead of checkbox.
Update to latest game version is good, but may not be always possible.

On the other hand, it can be difficult, expensive and need a lot of work.
In this case, it is not critical
Thanks.
(with some Google Translate)

**Comment by plague006** [comment]
Related: https://github.com/KSP-CKAN/CKAN/issues/1310

**Comment by plague006** [comment]
CKAN never intentionally breaks compatibility, that's why you are (or should be) still able to install most mods with ksp version 1.0.2. In this specific case (https://github.com/KSP-CKAN/CKAN-meta/commit/291029784d51a07eeb58619ede4fd01323cfcdfa#diff-ac2a07b317cc958701b3537d110fe43a) it was a bug that caused `ThrottleControlledAvionics` ver 2.2.1 to lose compatibility. This is also manually corrected in https://github.com/KSP-CKAN/CKAN-meta/commit/681b15f46efde16f0aae53cf36f3f7e48dfac219 so the mod should be available to you once again.

https://github.com/KSP-CKAN/CKAN/commit/1c1fb18f5f3735dedd2a5774aac3b3775a511968 is the permanent fix for this issue.

**Comment by jenyaza01** [comment]
I'm very happy, thanks for all!
*downloading mod*
==========================
This is the fastest support team in my life. Except parents.

**Comment by plague006** [comment]
Happy to help.
