### ISSUE TITLE
Priority for mods

### ISSUE THREAD

**Issue by VasVadum** [KSP-CKAN/CKAN#1375]
A priority list, to let you set what mods are most important to you.  So you can mark a mod as highest priority, and when you make a mod pack link or whatever (haven't tried yet with ckan) to share your pack, it shows the other users the priority as well.  I'll show my old spreadsheet as an example (half not updated but the priority is intact)
https://docs.google.com/spreadsheets/d/1PCbSwgSAueii_4LpiTorgmkuDpO61Vuo-uvRqhICBVo/edit

**Comment by plague006** [comment]
So for typical end-users, I'm wholly unclear on what the use-case is. If a user installs the mods, then they want the mod. If the user doesn't install the mod, then they don't want it. Is there any other program that has a feature like this so I can visualize it?

For modpack creators I see value in what you're suggesting: some mods are required, some are recommended, and some are merely suggested.

For example we'll pretend `RealismOverhaul` is a modpack (because it basically is).
https://imgur.com/a/ZRG0T
In the first image we have the non-optional mods. These are the core of the pack that define it. The second image are a set of recommended mods (important but optional) and they're selected by default. The third image are a set of suggested mods (nice additions but not important) and they're de-selected by default.
