### ISSUE TITLE
Mechjeb not working

### ISSUE THREAD

**Issue by AsgerJon** [KSP-CKAN/CKAN#1533]
I can't get mechjeb to work with ckan. Forscience works, but no mechjeb :(

**Comment by plague006** [comment]
Can you explain what you mean by "not working"? Is CKAN failing to install the mod?

**Comment by AsgerJon** [comment]
Mechjeb is showing in CKAN as installed, but when I open KSP there's no sign of mechjeb anywhere. However Forscience does work.

**Comment by plague006** [comment]
If CKAN has correctly installed the mod, your issue isn't due to CKAN. MechJeb is a very popular mod and the latest version was indexed on CKAN 5 days ago. I suspect if there were an issue with CKAN's installation of MechJeb there would be multiple reports.

To verify that the files are correctly installed, your `GameData/MehcJeb2` directory should look like:
````
|   LICENSE.md
|   
+---Icons
|       Ascent_Guidance.png
|       Attitude_Adjustment.png
|       Custom_Window_Editor.png
|       Delta-V_Stats.png
|       Docking_Autopilot.png
|       Landing_Guidance.png
|       Maneuver_Node_Editor.png
|       Maneuver_Planner.png
|       MJ2.png
|       Orbit_Info.png
|       QMark.png
|       RCS_Balancer.png
|       Rendezvous_Autopilot.png
|       Rendezvous_Planner.png
|       Rover_Autopilot.png
|       Settings.png
|       Smart_A_S_S_.png
|       Spaceplane_Guidance.png
|       Surface_Info.png
|       Translatron.png
|       Utilities.png
|       Vessel_Info.png
|       Warp_Helper.png
|       
+---Parts
|   +---MechJeb2_AR202
|   |       AR202_HD2_tex.dds
|   |       model.mu
|   |       part.cfg
|   |       
|   \---MechJeb2_Pod
|           model.mu
|           model000.dds
|           model001.dds
|           model002.dds
|           part.cfg
|           
\---Plugins
        MechJeb2.dll
````

If the tree I presented matches what you have installed, then this isn't a CKAN issue and we can't offer assistance.
