### ISSUE TITLE
Reupload of Kopernicus 0.6

### ISSUE THREAD

**Issue by ThomasKerman** [KSP-CKAN/CKAN#1537]
Hi all,
today I released Kopernicus 0.6, but unfortunately, someone reported a bug, that was present in previous versions too, right after I released it. I fixed the issue and reuploaded the .zip on GitHub.
However, the CKAN bot has already cached the bugged 0.6 release, so I would like to ask if someone of you could fix this and recache the current release.

@Olympic1 told me, that @techman83 could fix this.
Thanks in advance,
Thomas

**Comment by plague006** [comment]
I think there's a bit of confusion about CKAN caching mods. CKAN doesn't send mods to users. Ever. The cached copy of mods is strictly for Jenkins testing. Sometimes this can be relevant if folder names are changed and it affects testing, but aside from that: end users never see or know about any caching. CKAN downloads files directly from the download link inside .ckan files.

Unrelated to Jenkins caching files: if there was a serious bug, users who previously installed that version of Kopernicus will have no way via CKAN to update since the version is identical.

**Comment by ThomasKerman** [comment]
Ah, awesome. Thanks for the clarification. :)
I don't think that there is a need to force a pseudo-update, since the bugs are not that serious, but thanks though.

~ Thomas
