### ISSUE TITLE
CKAN regularly breaks KSP install

### ISSUE THREAD

**Issue by mobarre** [KSP-CKAN/CKAN#1569]
This happens a lot to me. Sometimes after updating my mods with CKAN, I end up with KSP being unable to start because of apparently missing files.

Here's the relevant extract from KSP.log:
http://pastebin.com/i7872Zbp

The way to solve this is generally me spending my evening reinstalling KSP instead of playing it. I am getting quite good at it though...

I can provide more info is needed (.ckan file maybe ?)

Using CKAN 1.6.0 but this has been here for a while now (first happened to me last summer).

**Comment by hoylemd** [comment]
I had exactly this problem last night, with the same mod: Procedural Parts.  Maybe it's that mod specifically? I just disabled it, since I don't really use it.

**Comment by mobarre** [comment]
Interesting. I checked and the last version of procedural parts was released mid decembre. So, if it is broken, it's due to last nights update of another mod. Which is precisely what bothers me.
My current mod list: http://pastebin.com/46GuXGgq

I'll try removing and reinstalling procedural parts and see what happens.

**Comment by mobarre** [comment]
Ok, same same...
Did notice other mods related to the errors I see though, most notably Realfuels. I'll attempt a reinstall.

**Comment by mobarre** [comment]
Upgrading realfuels worked.

Ok, so 13 hours ago version 10.8.3 of realfuels was released. It brings compatibility with SolverEngines 1.15, which in turn was pushed to CKAN this week-end and released 2 weeks ago. Both should have been pushed at the same time I guess.

So... We're all relying on CKAN and ModuleManagers to manage the huge amount of mods needed for things like RP-0, RO and the likes precisely because managing all the dependency issues by hand would be a pain in the ass (not to mention that RP-0 implies 22000 patches applied at startup and a loading time of a minimum of 5 minutes when the game is installed on SSD...) And yet this happens every two weeks.

Maybe the bug is the process used to push a release to CKAN. Anyone has some insight on this ?

**Comment by hoylemd** [comment]
That sounds like my situation exactly. I just ended up ditching PP and RF because they weren't adding anything to my play experience.

**Comment by plague006** [comment]
I'll try to provide some insight to this issue.

There's no release process for mod authors to push to users on CKAN specifically. A bot (@netkan-bot) periodically (every 3-4 hours, I can't recall which) runs every .netkan file (files which point to where new releases of mods should be) in the repository and scans for new releases. If one is detected it creates a .ckan file (a file that contains the full metadata for a release) and merges it into the ckan-meta repository. Once in the repository as soon as a user refreshes they can see the new release.

In the specific case of RF 10.8.3 and SE 1.15 they were released to GitHub roughly 2 weeks apart. If I had to guess at why the SE .ckan file was only created 4 days ago my guess would be that the author(s) knew they needed to be released close to each other and didn't upload a .zip in the SE release until RF was nearly ready.

In essence CKAN is like your buddy who's always on the bleeding edge of mods. Always pushing you the latest but sometimes not greatest versions of a mod. Being on the bleeding edge means you'll find the bugs that others, who wait, won't.

So while CKAN enabled the bug due to presenting you the latest release, it's no different than if you were checking for new versions daily and installed the new SE manually.

I could say something like "don't update as often" but I know too well the temptation of installing a new version of something. Maybe one day the KSP community will have something akin to Minecraft's FTB launcher where instead of individual mods, curators will test and release entire packs which are (practically) guaranteed to have a compatible and cohesive set of mods.

Enough ruminations though, I think I just fell into a bit of a writing mood. It seems this issue has resolved itself with the RF release, and due to the nature of CKAN scanning regularly for new releases, when game-breaking updates are pushed, users will be able to install them via this tool.

Closing this with my thanks for the bug report, and for the writing prompt. :smile:
