### ISSUE TITLE
Netkan Jenkins test not matching spec for initial character of name

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#1570]
As per KSP-CKAN/Netkan#2978, the build test is using a grep string that only matches mod names starting with a letter, but the spec says nothing about the initial character being special, so mod names should be able to start with digits or even dashes. Either the test or the spec should be changed. Is there a technical reason to limit the starting character to letters? Note that this is not in netkan.exe itself.

**Comment by dbent** [comment]
I'd be in support of removing that restriction. @techman83 Do you know of any particular reason why it's in place?

**Comment by techman83** [comment]
@dbent I don't know of any particular reason. @pjf may know more, the metadata.t tests were around pretty early on.

**Comment by Dazpoet** [comment]
I know for a fact I once ran into this exact issue but for the life of me I cannot find the discussion that followed, it might have been on irc.

It seems that I at least once made a mention of this issue [here](https://github.com/Dazpoet/NetKAN/commit/a875a5731d4ed338fb33dd20fc979c7c91499d94) but it seems I never bothered to explain why T_T

**Comment by pjf** [comment]
Gosh. This is in the machine-readable spec, but I can't spot it in the human readable spec. The original reasoning goes something like this:

- Debian has a pretty sweet package manager (`apt-get`), so we'll adopt their way of doing everything, since they've already been through the fire.
- Debian requires package names start with a letter.
- Let's do that!

Realistically, Debian probably has that constraint for some ancient parser that couldn't tell the difference between an integer and an identifier, or because there are situations where the two may be ambiguous.

I don't know of any situation where *we* have ambiguities between integers and identifiers, so I think realistically we can just drop this particular constraint.

**Comment by politas** [comment]
Machine-readable schema has been updated
