### ISSUE TITLE
Brainstorming: Something less than suggested

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/CKAN#1574]
Right now RO "suggests" a lot of mods. This is not terribly helpful to new players, because they think that means "I should download them all" not, as we mean it, "we support these". Further, AFAIK CKAN does not support any kind of popup on package select (a popup where we could state something like "note: CKAN will show a list of suggested mods, but all that means is RO is compatible with them".

Anybody got any ideas? :)

**Comment by nobodyhasthis** [comment]
This can also lead to a misunderstanding when #1572 Timeout error appears. Or to a crash when memory cap for mods is passed by using too many. 

I would suggest that on an initial install and first time use of CKAN. An information tool tip appears floating over the first appearance of the additional supported mods list. 

This tool tip is a reminder that these are optional and subject to pushing memory requirements. The new user can then make an informed decision on how to continue.  

As always such a pop up tooltip should have an option to dismiss it. So once it has served it's purpose it can be permanently hidden.

**Comment by dbent** [comment]
Well there is the [`supports`](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#supports) relationship which is the weakest possible relationship (one step below `suggests`). There has previously been disagreement about what `supports` actually means (#1104), but my take on it is that `supports` means "This mod has made special consideration for but in no way requires this other mod". For example, the canonical `supports` relationship in my mind would be on `Toolbar`. If a mod wants to "support" `Toolbar` is has to add some extra code, but `Toolbar` isn't in any way required.

In my mind, `supports` however *should not* be used as a general "is compatible with" relationship since all mods are *assumed* to be compatible with all other mods unless a `conflicts` relationship exists.

**Comment by dbent** [comment]
For completeness:

- `depends`: There's no point in installing this mod with this other mod. Therefore CKAN won't even install this mod without the other one.
- `recommends`: You *can* install this mod without this other mod, but it's really better that you do. Therefore CKAN will install this other mod by default. (e.g. A mod where the *only* way to access its settings is through a `Toolbar` button should `recommend` `Toolbar`).
- `suggests`: It would be a good idea to install this other mod, but you're not missing much if you don't. Therefore CKAN will offer to install this other mod but won't do so by default. (e.g. I would say mods that have example craft should `suggest` installing example craft)
- `supports`: This mod was explicitly made compatible with this other mod but in no way depends on, recommends, or suggests it. Therefore CKAN won't even mention it unless the user asks (by listing mod information). (e.g. as previously mentioned most mods and `Toolbar`).

**Comment by plague006** [comment]
I think we cover the relationships pretty well as detailed by @dbent. Where we might improve is communicating the meaning of those relationships to users.

Currently we use the phrases:
`The following modules have been recommended by one or more of the chosen modules:`
and
`The following modules have been suggested by one or more of the chosen modules:`

when listing `recommends` and `suggests` respectively. While those words have very specific meanings to CKAN (and in the English language at large), the granularity of the meanings could well be misinterpreted by users.

The very fact that `recommends` default as selected and `suggests` defaults as deselected should already create a distinction, but we could definitely reword the UI in order to reinforce it.

Something more casually worded might help:
`The following mods have been selected because they greatly enhance the experience of your selected mods:`
and
`The following are mods can enhance your experience with your selected mods, but are certainly not necessary:`

**Comment by NathanKell** [comment]
I would support something like that, yes. Or just "The following mods are recommended for use" vs "The following mods are especially noted to be compatible" or something like that.

Further evidence of this problem. User says "I only installed what RO recommends!" and posts [this list of mods](http://forum.kerbalspaceprogram.com/index.php?/topic/133422-realism-overhall-44mods-total-ram-crash/&do=findComment&comment=2440387)

And wonders why they crash.

**Comment by janbrohl** [comment]
I would understand "supports" as "is positively known (tested?) to play well with"

**Comment by HebaruSan** [comment]
This issue seems to be more about end user confusion than about a technical need for a new kind of relationship. Here's what RO's rec/sug list looks like nowadays:

![image](https://user-images.githubusercontent.com/1559108/82130267-79ee4f80-978f-11ea-9f5a-eb683dc8d209.png)

I think a few things work together to make it clearer than it used to be:

- You can see at a glance that there are two separate lists
- It explicitly says "Recommendations" and "Suggestions" above the lists
- One list of mods is checked by default and the other is unchecked

I don't think a modern user would think that the suggestions were recommendations. Also worth noting is that the user in the linked forum thread was on a pre-64-bit version of KSP; it likely wouldn't crash now.
