### ISSUE TITLE
ckan.exe picks Steam directory over current directory

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#1628]
Reported in [this forum post](http://forum.kerbalspaceprogram.com/index.php?/topic/90246-the-comprehensive-kerbal-archive-network-ckan-package-manager-v1160-13-dec-2015/&do=findComment&comment=2454837) , using CKAN v1.16.0.

I haven't verified this myself, but it seems plausible. We _should_ be checking same directory as `ckan.exe` first, then everything else from there.

**Comment by HebaruSan** [comment]
I think this was a false alarm. The code is pretty clear that `PortableDir` (ckan.exe's folder) is checked first, and `FindAndRegisterDefaultInstance` (Steam) is last:

https://github.com/KSP-CKAN/CKAN/blob/e825bdef9d52a4117e37acf6b6b74da216ee4567/Core/KSPManager.cs#L70-L105

A few ways the problem report could have been mistaken:

- Installing ckan.exe into GameData instead of game root
- Running a different copy of ckan.exe via a shortcut
- Symbolic links?

No details have been added in 2 years, so we're unlikely to see them now; closing.
