### ISSUE TITLE
Please help me untangle the ckan.schema so I can understand it better

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN#1657]
After just merging #1597 and reading on how a .schema works I thought I understood things but now I can't fathom how [this](https://github.com/KSP-CKAN/CKAN/blob/master/CKAN.schema#L263:L286) is correct.

It says that we should only use `oneOf` the things but shouldn't then each spec_version have a longer enum/arrray than the last one rather than just adding a single string to each one following the `1,` special case?

I'm guessing this makes total sense somehow but I cannot grasp it so I'm opening an issue as a reference for both myself and anybody else who can't figure this out.

**Comment by politas** [comment]
I think what it does is effectively build a single combined array, so you end up with 

    [ "GameData", "Ships", "GameRoot", "Tutorial", "Scenarios", "^GameData/",  "^Ships/(SPH|VAB)$", "^Ships/@thumbs/(SPH|VAB)$" ]

But it has to be separated out, because patterns are not literal strings, so you can't define it as a single enumerated list. An array can only be a single type, and we have a mix of different types. "OneOf" lets you mix different types.

**Comment by Dazpoet** [comment]
Sounds reasonable, I don't quite grasp the exact usage but I'm happy with getting a better understanding of the general case and as such I'll close this with great thanks for taking the time to expand on this :+1:
