### ISSUE TITLE
NetKAN ignores spec_version?

### ISSUE THREAD

**Issue by Starstrider42** [KSP-CKAN/CKAN#1691]
**CKAN Version:** CKAN v1.16.1-0-g2e91715 (beta), NetKAN v1.16.1-37-gfbdb573 (beta)

**Operating System:** Windows 10 64-bit

**The issue you are experiencing:** I recently created a NetKAN file that copies a folder to a specific subdirectory of `GameData` (KSP-CKAN/NetKAN#3833). I built it with NetKAN, and all was well. I imported the resulting `.ckan` file into CKAN, and all was well. Then I submitted it to Jenkins (http://ci.ksp-ckan.org/job/NetKAN/3063/)...
> Running basic sanity tests on metadata.
If these fail, then fix whatever is causing them first.
t/inflate.t ... skipped: Not a travis pull request
> 
> \#   Failed test 'CustomAsteroids-Pops-Stock-Inner - spec_version v1.2+ required for GameData with path.'
\#   at t/metadata.t line 90.
> 
> \#   Failed test 'CustomAsteroids-Pops-Stock-Outer - spec_version v1.2+ required for GameData with path.'
\#   at t/metadata.t line 90.

Sure enough, the spec does say that `"spec_version": 1` is not allowed with the new install statement, and changing the version to "v1.2" fixed the build. But why did neither NetKAN nor CKAN catch it?

**Comment by politas** [comment]
Since you are using a netkan and a ckan that implement all of those features, they aren't going to complain. Jenkins cares about the spec_version, because that field is basically there for alternate/forked clients.

**Comment by plague006** [comment]
Basically saying the same as @politas but in a different way:

NetKAN doesn't use `spec_version` at all because `spec_version` is the CKAN spec and NetKAN is an entirely different tool.

You local ckan.exe only scans `spec_version` to make sure it can run the file. If `spec_version` < CKAN.exe's version then it'll fail.

The way to catch when a file doesn't match the spec is to prove the file against https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md. We don't include this kind of small detail in the wiki because it's a step too far (IMO) and would create a barrier to people submitting metadata.

**Comment by Starstrider42** [comment]
It's not a bug, it's a feature. Got it.
