### ISSUE TITLE
CKAN tests mod version interdependencies incorrectly

### ISSUE THREAD

**Issue by Starstrider42** [KSP-CKAN/CKAN#1693]
Bug report as requested by @plague006 on KSP-CKAN/NetKAN#3841. 

**CKAN Version:** v1.16.1-0-g2e91715 (beta)
**Operating System:** Windows 10 KP
**The issue you are experiencing:** The Custom Asteroids config file .ckans each depend on a minimum version of Custom Asteroids, but have a much broader range of KSP versions. Currently the dependencies are:
- [CustomAsteroids-v1.2.0.ckan](https://github.com/KSP-CKAN/CKAN-meta/blob/master/CustomAsteroids/CustomAsteroids-v1.2.0.ckan): requires KSP 1.0.0-1.0.5
- [CustomAsteroids-v1.3.0.ckan](https://github.com/KSP-CKAN/CKAN-meta/blob/master/CustomAsteroids/CustomAsteroids-v1.3.0.ckan): requires KSP 1.1.0-1.1.2
- [CustomAsteroids-Pops-Stock-Inner-v1.2.0.ckan](https://github.com/KSP-CKAN/CKAN-meta/blob/master/CustomAsteroids-Pops-Stock-Inner/CustomAsteroids-Pops-Stock-Inner-v1.2.0.ckan): requires Custom Asteroids >= v1.0.0
- [CustomAsteroids-Pops-Stock-Inner-v1.3.0.ckan](https://github.com/KSP-CKAN/CKAN-meta/blob/master/CustomAsteroids-Pops-Stock-Inner/CustomAsteroids-Pops-Stock-Inner-v1.3.0.ckan): requires Custom Asteroids >= v1.3.0

The intended behavior is that Pops-Stock-Inner v1.3.0 gets installed if you have Custom Asteroids v1.3.0, and v1.2.0 gets installed if you have any older version.

However, trying to install Custom Asteroids for KSP 1.0.5 (Custom Asteroids v1.2.0), which requires Pops-Stock-Inner as a dependency, causes CKAN to report a conflict between Pops-Stock-Inner v1.3.0 and Custom Asteroids v1.2.0. There is no option to download Pops-Stock-Inner v1.2.0, even though it is compatible with both KSP 1.0.5 and Custom Asteroids v1.2.0 and would satisfy Custom Asteroids's config dependency.

**How to recreate this issue:** (I will shortly be modifying `CustomAsteroids-Pops-*.netkan` to work around this issue, so the original example can't be used. The issue should be reproducible with any mod that depends on a newer version of a currently installed mod.)

**Comment by Starstrider42** [comment]
No objections to the renaming. I wrote the original title in a behavior-oriented way because I don't know anything about CKAN's internals.

**Comment by HebaruSan** [comment]
Well for now this is just my notes-to-self, so I can pick up where I left off in the future. I could be mistaken about any of this.

This is the line where the RR effectively narrows us down to just one version of a mod, without checking reverse dependencies:

https://github.com/KSP-CKAN/CKAN/blob/c49489b061f91c5d0936de327de1aadcaba6cfad/Core/Relationships/RelationshipResolver.cs#L407-L408

We would need something like:

- `Registry.AllAvailableWithProvides` instead of *Latest*, which RR would then filter by reverse dependencies; or
- `LatestAvailableWithProvides` needs to gain the ability to filter based on reverse dependencies, including an `IEnumerable<CkanModule>` input parameter indicating the current change plan

I guess that second option sounds more reasonable.

**Comment by HebaruSan** [comment]
@Starstrider42, I think I've got this figured out as part of #2660. These are the relevant tests, if you wouldn't mind double checking that I've understood the problem accurately:

https://github.com/KSP-CKAN/CKAN/blob/d48fad4254ca5e8b7ca0195cd78375b9abf16da0/Tests/Core/Relationships/RelationshipResolver.cs#L726-L807

**Comment by Starstrider42** [comment]
I think so? You've removed the KSP versioning aspect of the original issue by forcing a specific version of `depender`, but I think that's reasonable.
