### ISSUE TITLE
Mark if index entry was added/authorized by mod author or not

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#1741]
I think it would be good to distinguish index entries added (or explicitly authorized) by the author(s)/maintainer(s) from those added by unrelated people.

Maybe add a field index_maintainer or the like.

See disussion of #838

**Comment by plague006** [comment]
Why would it be good to distinguish them?

**Comment by janbrohl** [comment]
You would know who you should contact for ckan-related issues and where to direct their donations.

**Comment by politas** [comment]
I can see at least two ways of reading such a flag, with contradictory effect:

1.   Metadata is maintained by author, so ought to be right - Problem is that we would have to exclude mods whose authors requested a CKAN submission on Spacedock.
2. Author desired mod to be on CKAN, but may not be actually maintaining the metadata themselves (an active forum thread user may be helping the modder out by doing it, or CKAN team members might be doing it)

**Comment by plague006** [comment]
Issues with CKAN metadata should come to CKAN as an org regardless of who authored the metadata. Just because a mod author originally wrote their metadata doesn't mean they're actively maintaining it or even still active in the community.

It's been hard to convey to our users and the community at large that CKAN issues should be brought to CKAN. After ksp 1.1 was released there was a mod that CKAN was installing incorrectly for over a month: the author had received multiple reports and grew frustrated to the point that they changed the ksp thread OP to indicate CKAN shouldn't be used to install the mod. Naturally doing that didn't fix the issue and just led to hate towards CKAN and frustration for the author. Within 24 hours of when we were actually informed of the issue it was resolved. The point being CKAN needs bug reports to make CKAN better. Sending them anywhere else isn't a good solution. It's equivalent to a user going to a forum thread, seeing the list of contributors and PMing them about an issue: if it's not in the thread then it's very easily missed.

**Comment by nobodyhasthis** [comment]
@plague006 Yes that is just the way it goes. Point raised is good for discussion required on Issue report #1502. Since is now against KSP forum rules to repeatedly ask for an update schedule for the reasons you have highlighted.

> 2.3 Forbidden messages
> f. Messages that repeat inquiries about updates or content from modders.

**Comment by ferram4** [comment]
> It's been hard to convey to our users and the community at large that CKAN issues should be brought to CKAN.

@plague006 , well, it's not like the way CKAN is set up and the info about it does anything to discourage the idea that mods are uploaded and maintained by their authors.  The obvious start is that users assume that CKAN is like any other hosting site and that mods only appear there if uploaded.

Then virtually all of CKAN's documentation on uploading mods encourages that interpretation; the wiki's [Adding a mod to the CKAN](https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN) page seems to assume right in the 3rd paragraph that the reader is a mod author even before getting to the "note to mod authors" section.  It does not help that while there are numerous bolded "note to mod authors" in there, there's no "note for everyone else" to draw attention to the fact that non-mod authors might be writing this.

The about page seems to imply that mods are only there by being uploaded by modders and there's no information explicitly contradicting this anywhere.  Anyone who takes the time to try and find out where to take install issues is going to come to the conclusion based on the CKAN docs.

**Comment by plague006** [comment]
When I first worked on editing that wiki page in may of 2015 I noticed that the wiki page was strongly geared towards authors. Over time I've steered it to be more neutral, but I've also become desensitized to the possessive pronouns used in lieu of its technical accuracy.

You could actually be a valuable asset in identifying especially blatant cases where we've misrepresented things. https://github.com/KSP-CKAN/CKAN/issues/1745 if you have specific files you know need to be modified.

**Comment by HebaruSan** [comment]
- All mods are authorized by mod authors nowadays
- The wiki says:
  > If you're not the author, please contact the author and ask if it's OK with them to add the mod to CKAN before proceeding. Adding a mod to CKAN brings it to the attention of more users and can affect the maintainer's support burden, so we don't add mods against their authors' wishes.
  > If the author is on the opt-out list, then please don't bother them at all!
- All metadata is "maintained by" all team members, whoever notices a problem or is approached for help or reads an issue first or has time

So this information would be both redundant and unhelpful.
