### ISSUE TITLE
Persist log data to disk with a log4net rolling file appender

### ISSUE THREAD

**Issue by Shirkit** [KSP-CKAN/CKAN#1759]
Hello,

I'd like to suggest to CKAN to generate a log file inside the CKAN folder and anything it writes to the Status log, he also appends to the log file, so that we can go for it later on to see what exactly I (the user) have chosen to update. Just broke my game while updating and now I must hunt what exactly went wrong, since I forgot what I just updated.

Thanks

**Comment by hschwane** [comment]
I just wanted to also open a ticket for a log when I found this. We only need a list which sayes what mod was updated / installed / uninstalled with timestamps. Could be inside the gui, via commandline or in a file. This would realy help to uninstall broken mods.
Thanks

**Comment by Shirkit** [comment]
So, could a hook be added so whenever something is pushed to the Status Log tab just append to a file as well? Again I broke my savegame because of updating mods and I must hunt for it again, since I updated 15ish mods =\

**Comment by HebaruSan** [comment]
I think the `CKAN/history` folder from #2239 satisfies this. Every time you install, remove, or upgrade a mod, a timestamped file is created in that folder listing all your installed mods and their versions. This allows you to check previous states of your registry and even install them, since it's done with .ckan files.

Closing as done.
