### ISSUE TITLE
Fill more fields on $vref

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#1765]
https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#vref states that only KSP version info is extracted although several other fields map well to ckan.
- NAME: name
- GITHUB: resources.repository (or even $kref for github)
- VERSION: version
- DOWNLOAD: resources.homepage

CHANGE_LOG and CHANGE_LOG_URL do not yet map to a ckan-fields but having having or linking to a changelog in ckan (resources.changelog?) seems like a good thing to me. Propably there is a reason why there is no such field but what is it?

**Comment by politas** [comment]
We really can't use the $vref to fill in the $kref, since we need the $kref to find the download where we can see the $vref. I don't think we have the ability to put a URL in a $vref, yet.

As a basic note, mod authors don't always get the .version files exactly right, or keep them updated consistently.

**Comment by janbrohl** [comment]
Theoretically $kref could be filled that way if the download-field is provided - but that would make $kref much less useful.
