### ISSUE TITLE
Allow manual downloads of mod packages

### ISSUE THREAD

**Issue by mario-ragucci-sp** [KSP-CKAN/CKAN#1788]
Hi,
CKAN v1.18.0-0-geeb9127
OS: Mac OS X (el capitan) / Windows 10

I am currently trying to install several mods via CKAN, however it is not working because of the **awful** speed a get on those downloads. I tried downloading those files via browser, and the download was bleeding fast. So my request is:
Please add the funcionality to download packages on my own and put them to a special folder so CKAN will check if the file was downloaded manually before accessing the download url (like you do it with cached downloads).

Thanks!

**Comment by politas** [comment]
Go to the Contents tab, and you can download mods there. See how that compares for speed.

**Comment by politas** [comment]
We are now adding file hashes to the local registry, so importing files downloaded outside CKAN could be added.

**Comment by HebaruSan** [comment]
I see this as an "Import downloaded mods" menu option...

1. Prompt the user to select one or more zip files they downloaded
2. Calculate their SHA1-sums
3. Search the registry for matches
4. If there are multiple (some mods share downloads, e.g. RasterPropMonitor and RasterPropMonitor-Core), ask the user which of them to import
5. Copy the zips into the cache under the names that would be used if they were downloaded by CKAN
6. If they're compatible with the current instance, prompt user whether they want to install, otherwise alert that they're not compatible

This could be a pretty nice option for getting started with CKAN if a user has a long term downloads folder where they've kept everything they've installed manually. Run CKAN, choose the import option, select your old downloads, then say Yes to install all of the ones that are compatible, and when it finishes, you are up and running on CKAN.

**Comment by Charon77** [comment]
👍  to this.
I've came up to this thread for another reason, that is
CKAN seems to suffer from the trouble of:

- slow download (halting)
- unable to continue interrupted download.

So I think this needs a fix as well.
