### ISSUE TITLE
Proposal - force ksp version max  

### ISSUE THREAD

**Issue by TeddyDD** [KSP-CKAN/CKAN#1798]
Every time new version of KSP appears most of the packages is not available to install due to `ksp_version` or `ksp_version_max`. However there is plenty of packages without `ksp_version` or with `ksp_version_min` only.

Ideally just after release of new KSP version CKAN should show no mods. This way mods could be tested for compatibility with new KSP before end users will get them.

So I propose to add `ksp_version_max` = current version of ksp to every package that don't specify `ksp_version` or `ksp_version_max`

**Comment by nobodyhasthis** [comment]
@TeddyDD honestly don't know if this helps you. I had a chat with a mod author about how to automatically bump his mods `Ksp_version_max`. this was the out come...

> Based on the suggestions by @nobodyhasthis2,  I digged through the ksp-avc and and ckan algorithms concerning versioning.
> The problem with ksp-avc is, that if the max version is lower than the current ksp version, every such mod generates an error message.
> But if there is no max version specified in the .version file (so if there is only a ksp version, but not a max ksp version), it lumps all the "outdated" mods together in one error message and displays the mod yellow.
> If the max KSP version is just set to 1.99.99, there is no error message and no color indication that the mod is outdated.
> => Thus for KSP-AVC it is preferential only specify a ksp version and simply delete the max ksp version entry.
> It is different for CKAN. If CKAN detects a max ksp version entry lower than the current one, or a ksp version entry lower than the current one, it simply refuses to install the mod.
> Normally ckan gets those infos from the .version file included in the mod.
> => **Due to the above reasons, it is beneficial (for users and modders) for ckan operations to simply set the max ksp version to 1.99.99 regardless of what is written in the .version file.**
> So that you can install a mod via ckan regardless of the current ksp version (but that can be changed by myself without having to reupload a mod, in case of real issues). And when you start the game, KSP-AVC, which is a dependency for most SETI mods, will then show you whether the mod version is actually outdated (for bug reporting/support issues).
> 
> Imho the best of both worlds. Note that this is only useful since the SETI mods do not install plugins, so there are fewer chances of small ksp updates causing issues.

**Comment by nobodyhasthis** [comment]
Also worth mentioning the `GRAS` policy that assumes mods are compatible. That was coded in as part of discussion on "fuzzy version" control. So some mods would automatically appear in a new version of KSP. 

It is also possible to automatically let them all through but it has been hit and miss with KSP versions See. https://github.com/KSP-CKAN/CKAN/pull/1499/commits/757d9cb0e60f8ec47f991a1b5a9d731bae37888f

Again sorry if this does not provide useful information. If you are not happy with my posts. I will remove them. I don't want to much up your issue report that's all. Just trying to get all information in one place to help people out when making a decision on the issue.

**Comment by politas** [comment]
@nobodyhasthis, let me just say that I have been very appreciative of your efforts recently, and you generally seem to provide useful information. I've seen a few cases that look like you've spent significant time researching an issue, and I hope you continue to add value to the CKAN project. 

Be a little bolder with your contributions, you're on the right track.

**Comment by politas** [comment]
@TeddyDD, I'd be surprised if there are many .netkans left that don't have either a ksp_version or ksp_version_max set, but if you can find any, they should certainly get _something_ set. See how many you can find, it may be plausible to investigate them in detail rather than a blanket "set to current KSP version."

**Comment by BobPalmer** [comment]
I would agree with setting such information if i is absent (ideally, via an intelligent programatic default, not through changing the metadata), but disagree with this bit from the post by  @nobodyhasthis  

"Due to the above reasons, it is beneficial (for users and modders) for ckan operations to simply set the max ksp version to 1.99.99 regardless of what is written in the .version file."

If a version is specified, then it should be respected.  While the pack may very well work on a new version of KSP, it's not a bad idea to make sure it actually does so (I for one do this).  So changing this field when something is present (as opposed to having an intelligent default) would be a bad idea, and a bit overreaching.

**Comment by BobPalmer** [comment]
As an addendum.  The rub with making assumptions (I assume with the goal to speed up migration when a new KSP version comes out) is that it pushes all of the support issues from CKAN (where is mod X?  When will CKAN be updated?') squarely back to the modders (But CKAN said this works in version X - why are the wheels exploding?).

**Comment by nobodyhasthis** [comment]
@BobPalmer in regard to just ` max_ksp_version`. I took that information from a modder that had a problem updating. To put it in context. The whole quote is there. Looking at the other mods it seems to be used quite few times. So this seems to be one method that some modders use. Good or bad. That what some mod authors are pushing out. 

Now I am not suggesting this is the right way to do it. Just reporting what I have discovered. If this is a bad habit that is creeping in. The CKAN team need to review it. So for better or for worse here it is in the issue report. It goes against what the OP is suggesting so seems relevant. 

As far automatic updates goes. Which is something is based on the game becoming more stable. It is long story. With a massive debate from last year. There is an opt out function. `strict `version mode. Written into the code so it can be done on a per mode basis. I think an example of a mod that would use this was Contract Configurator. Due the Squad changing this part of the game recently. It has to be version specific. I could be wrong. It all happened a long time ago an I can't remember the whole conversation. There is also the global setting noted above. So far it only ever be activated once. KSP 1.0.3 > KSP 1.0.4. Since then the option has never be used.

Please note. All of the above may be inaccurate information. Although code is there it might not be in use yet. I am just offering up an abridged version of a long story. There could be a heavy amount of editing based on feedback from the CKAN team. The reason to mention all of this here is that is the opposite behaviour that the OP expects would happen. Which leads to questions.

@politas how far did the project go with the idea on 'fuzzy version' options. It might be best if the design choices where made clear to people that have not be following along the whole forced update discussion. last year. Also the whole idea of mod authors setting`max_ksp_version` as shown above. What should happen?

Oh and thanks for earlier support. However still feel free to delete my posts. If the information does not fit in with the solution. What ever helps get the right information out there. I just want to help close them. So what ever it takes.

**Comment by BobPalmer** [comment]
Yet proper use of ksp_max_version is a good thing.  Many mods require recompilation or at least some checking each new version, so a very common thing to do is make sure they don't all go out as being flagged compatible when in fact they are not.  My only point is that use of this is up to the modder in question.  It should not be overriden by CKAN.

**Comment by TeddyDD** [comment]
> don't all go out as being flagged compatible when in fact they are not.

That's my concern.  Whole fuzzy version stuff and packages that assume compatability with future versions of KSP,makes CKAN maintainers life easier. However this might lead to issues for users and modders. This is related I think #1679

**Comment by nobodyhasthis** [comment]
@TeddyDD I agree with you. However in previous conversation it was found that automatic updates makes modders life easier. Remember it is all based on a future scenario and not the current one. The point where a majority of mods do not break when KSP updates. This not hypothetical. There is well documented historic example. (Ref https://www.reddit.com/r/KerbalSpaceProgram/comments/3beh00/why_are_there_so_few_ckan_mods_for_104/) Right now it might not be the case but does appear heading that way if you believe the developers notes, 

However unfortunately there is a class of mods that require version locking. To a specific version of KSP. Some will require recompilation. Every time there is KSP update. Perhaps a good current example here is the introduction wheel parts. The example of a mod that is very stable would be the various flag mods. They are _almost_ guaranteed to work with the next version of KSP. I know that is a very simplistic example but it does show there is a scale of upgrade difficulty. The key thing is the definition of a KSP minor update. To some it is a simple cosmetic change to others it represents a brand new game where previous rules no longer apply. 

The key point is I think we can all agree on. Is the choice of how to proceed in each case. Is in the hands of the mod author. They are subject matter experts on the future requirements of their mods. They should have freedom of choice. What this means that any global choice to set `ksp_max_version`  can't be used. We need to respect what is recommended. Even if it a different solution each time.

My own concern is how many mod author don't know about the choices available to them. How many know they can get KSP-AVC and CKAN working together using the technique above if that is what appeals to them. How many know how to set the game comparator if that works better for them. If we don't present all the evidence and choices available we are doing mod authors a disservice. 

The suggestion that this related to #1679 is correct. If that is what it takes to gather mod author choices. I am all for it. Note however that this is often a single conversation. When the whole repo is looked at. Some `.netkan` are really old and they be working successfully for a long time. On the part of most mod authors. It should be one message to pick a choice and the metadata flags are set for them. After that is all should just happen with bots and no micro management.

**Comment by politas** [comment]
My understanding (and if I'm wrong perhaps @BobPalmer can correct me, is that mods with DLLs are _far_ more likely to break with a new version of KSP than part only mods.

I would like to get into a conversation with the Kopernicus team to find out about their efforts in the realm of backwards compatibility. It may be that Kopernicus planet packs should be GRAS for future upgrades, since Kopernicus does the hard part of maintaining compatibility with KSP.

Of course, there's always the issue of people upgrading their KSP and still having mods installed that may now be broken. There doesn't seem to be a way of preventing Steam from auto-updating KSP, for instance.

**Comment by nobodyhasthis** [comment]
@politas I think you are correct here. Simple parts mods tend to be ok but those with plugins are more risky. However there is a few edge cases where special consideration is required. Some of this is going to be a bit tricky talk about. I don't want to get us in a situation where @BobPalmer can't give advice for obvious reasons. Please forgive me. I am just trying to share some of my experiences in hope that it helps a bit.

There some mods that have lots of parts that work just fine. Expect when you go near the wheels. Now it is clearly understood that it a new system and it takes time to adjust to. The advice direct from the mod author is yes list the mod as fully compatible. Squad could still change things. Once things settle down the mod will get fixed up. Right all the other parts are ok. Except wheels.

Another mod author I am working with has done his own version of the Remote Tech configuration files. As part of a game play overhaul system. Including some Antenna Range stuff. Nothing too heavy. This is just a set of MM patches. I know this because sometimes. I submit them myself. It has gotten to the point where I have my own version of the mod. Now is this all going to be compatible with the next version of KSP. I don't know. My gut reaction is to advise version locking on the mod. We need to see the new changes after KSP updates and come back with an update plan.

So parts mods mostly ok. Plugins are tricky. A few special cases where the stock game development changes things around. So not the generic answer we looking for.

**Comment by BobPalmer** [comment]
Not sure why I would not be able to give advice, @nobodyhasthis ?

But tbh this whole topic looks like things are being unnecessarily overcomplicated.  If a mod has a max version in place, respect it.  It's there for a reason, regardless of the kind of mod it is (parts mods can also break as partmodules change).

From a CKAN perspective, ones without a version or max version could be considered fine, though I expect this could be done programatically.  In thinking, it may even be worth it to add an anotation whether something is assumed to be compatible (no version info) vs. known to be compatible (the modder has updated the version compatibility).

**Comment by nobodyhasthis** [comment]
@BobPalmer. I agree with everything you wrote here. Sorry for for my remark about you giving advice. I was self conscious about writing about an upcoming to change in KSP. Since some cases your not just seen as a modder but also part of the game development team. Sorry just did not feel it was fair to pick out something from the development notes then ask for advice. I apologize if this wrong.

**Comment by HebaruSan** [comment]
Regarding metadata, I would say the first principle is that it should be **accurate**. If any metadata currently misrepresents the author-declared compatibility of a mod (so authors have a chance to test and confirm compatibility before users start installing on that version), that should be fixed.

> Ideally just after release of new KSP version CKAN should show no mods. This way mods could be tested for compatibility with new KSP before end users will get them.
> 
> So I propose to add `ksp_version_max` = current version of ksp to every package that don't specify `ksp_version` or `ksp_version_max`

This would not be accurate. There are part mods and simple MM patches that reasonably can be expected to remain compatible forever; a one-size-fits-all approach such as suggested in the OP would burden authors of such mods with extra maintenance and support requests from users as they struggle to satisfy CKAN's demands for metadata updates.

Closing this for now. If there's some aspect of this that is still a "live issue" now, please let us know and we can re-open.
