### ISSUE TITLE
CKAN Leadership

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#1800]
I started the KSP-CKAN project almost two years ago. It was very much a work of passion; the initial core was written in 300 hours over five weeks. That was sixty hours a week, more than a full-time job, but I was happy to do it. This was a project I was convinced would succeed, because I wasn't breaking new ground. I was taking proven successes from the Perl and Debian projects, modernising some of the systems, and applying them to gaming.

Skip forward to today, and we have somewhere in the realm of a hundred thousand users. Twenty thousand people have downloaded the CKAN client in the last week alone. We have hundreds of contributors, and have been responsible for _millions_ of mods getting installed. If we assume that the time people save on installing mods is spent playing the game, then I believe we can measure the CKAN's success _centuries_ of human joy delivered.

The CKAN hasn't just been successful, it's been successful far beyond my wildest dreams. For a project that wasn't breaking new ground, it's broken a _lot_ of new ground.

The CKAN has grown into an amazing team of developers, indexers, infrastructure specialists, automation specialists, documenters, and contributors who have been keeping things going. The sheer number of people working on the CKAN is something I'm delighted and humbled by.

But for some time, I've not really been one of them.

Many of you have noticed that my participation has dropped off over the last year. I've been around less, I've been contributing to fewer discussions, I've been writing less code, and making fewer plans.

The truth is, working on the CKAN has become increasingly more difficult for me, and even though it's something I care passionately about, it's been an increasing source of stress and concern. I've started to filter my mail, to be scarce on IRC, to avoid the forums entirely. It's impacted my sleep, and my ability to concentrate. And for all this, I've still not been able to participate properly where it counts.

And that's a very, very hard thing for me to admit to. There are a hundred thousand users out there for whom I very much want the best, and to step down in any capacity feels like letting them down. But to stay in them would be putting my health on the line, and I think would run the very real risk of making things worse.

As such, I'm stepping down from being involved in policy discussions. I'd love to continue help with the tech side of things, but while I'll help with handover where it's needed, I think realistically I'll need to be taking a break from everything for a while.

Having said that, there is one last matter of policy I would like to address. As project founder I've held the implicit position of also being the one who's ultimately responsible for any decisions that are made. That's no longer a role that's appropriate for me to hold.

While I'm very supportive of flexible organisation structures, and I have deeply encouraged this within the CKAN itself, I do feel it's required for one person to be the Mission Director. A person who is ultimately responsible, and thus who can break deadlocks and keep things moving where they might otherwise stall. The Mission Director need not be intimately familiar with the code, but they do need to be across both the technical and social issues that exist, and they need the respect of the people they're working with.

For whoever does become the new Mission Director, I hope to humbly ask three things. Firstly, that you keep the Code of Conduct, the CKAN should be a place that provides a friendly, safe, and welcoming environment for all. The second is that you appoint and encourage deputies, they're essential for making sure you don't burn out, and essential for helping others grow and learn. Finally, I'd ask the position of Mission Director be one that's re-evaluated each year; it won't be an easy role, and that yearly re-evaluation is an important chance for you to ask yourself if it's a role in which you wish to remain.

Choosing a Mission Director isn't something for me to decide, it's a decision to be made by those who will be working with them¹, but I do hope that I can provide a nomination for the role. As someone whom I feel has an excellent grasp on both the technical and social sides of the project, and who has shown both conviction and foresight, I would like to nominate @politas as new the Mission Director.

Thank you, so much, to the hundreds of people who have contributed to the CKAN project over the last two years, be that advice, documentation, code, metadata, community management, or just a friendly face. Together we've made something amazing, and I am honoured to have worked with you.

~ Paul
## 

¹ Primarily, @KSP-CKAN/contributors and @KSP-CKAN/wranglers .

**Comment by pjf** [comment]
Oh, one last thing. I'm hopping on a flight from Melbourne to New York in a few hours. Please don't take my lack of replies as anything other than I'm a little closer to space than usual right now.

**Comment by politas** [comment]
Would be really good to have some input from the rest of the team on this. I understand that some people may have just been too busy to deal with all this, and others may have been actively avoiding the conflict, but I've been feeling a bit "out on a ledge" for the last few days.

**Comment by politas** [comment]
Between fork and a federal election this weekend, I'm not going to be doing anything by way of changing things until Monday at the earliest. Hopefully by then my status can be either supported or disputed.

**Comment by pjf** [comment]
> Hopefully by then my status can be either supported or disputed.

That doesn't sound like you're declining the nomination! Thank you!

**Comment by Ippo343** [comment]
I approve @politas ' nomination.

**Comment by dewiniaid** [comment]
I'm not on the CKAN team, but I support this.  With the current ongoing situation, @politas has been quite adept at handling the issues and staying levelheaded about it.

**Comment by Cphoenix** [comment]
> With the current ongoing situation, @politas has been quite adept at handling the issues and staying levelheaded about it.

My thoughts exactly.

**Comment by NathanKell** [comment]
I am not sure what to count myself as in this discussion, and apologies if I am stepping on toes by responding, but I want to add a few words here.

First, I want to give heartfelt thanks to @pjf for all he has done, is doing, and will continue to do, and for being a really, really good human being (in general and about this). :)

Second, I want to praise @politas. I have had nothing but positive interactions with politas over the years, have nothing but respect for politas's contributions across all levels of the CKAN, and think politas would serve very well indeed as Mission Director.

**Comment by PapaJoesSoup** [comment]
I also feel the decision is a good one.  I hope Politas accepts.  I will support him as much as I can.  I'm not a major contributor in the community, but I do feel He has conducted himself with great personal conviction.  I have stated my feelings about CKAN and do not wish to see it fail.  It is a solid addition to the KSP community and has proven its worth, even if there have been issues.

WEll done.e

**Comment by anxcon** [comment]
level headed, tries to make all happy, agreed would do great at the job

@politas while i support you, i do say think it over, don't feel like the fans are cornering you :)

**Comment by PapaJoesSoup** [comment]
Agreed, it is a heavy burden.  But, someone must do it for the health of CKAN.

**Comment by plague006** [comment]
Sad to see you step down @pjf, but totally understand your reasoning.

**Comment by nobodyhasthis** [comment]
@pjf  Yes that is right. I am going to say it again. Thank you very much!. Indeed thank you for everything you do. Even for the things not related to CKAN. 

Although the news of your stepping down may have be a surprise to some. Or overshadowed by recent events on the KSP forums. I think it is fair to say it has been coming for a while now. You have always been really open about your feelings on your blog page. Which I first came across way before KSP was the thing. At least for me. Found it whilst doing research for a business degree. Which required about 50% psychology research. Rather than actual business studies, Plus, I think now. That I needed help in my own way and was not self aware of this. As with all good things open source. It took me to other places of learning that I would have never found on my own. For science !

If I learned anything along the way. It is that personal health comes first before any project. Something that we should all remember.  

So yes. Thank you very much @pjf

**Comment by plague006** [comment]
Over the last couple of months I've been withdrawing my presence from CKAN as I've found myself in conflict with @politas over even small changes to metadata and this has been adding undue stress to what used to be a very enjoyable pass-time.

My jaw hit the floor when I didn't see @pjf nominating @techman83 or @dbent, who both represent ideal candidates in my eyes, but such is the way of things. As it seems the winds will be pushing @politas into a leadership position I think it's time I leave the team. Special thanks to @Dazpoet who was an amazing mentor and guide.

**Comment by anxcon** [comment]
@plague006 not to "blow wind" in any direction with this statement, more a statement on logic. i only really saw 2 people even around during this mess, @pjf who got quiet (regardless the reason, no blame) when it really hit the fan, and @politas who tried to put the flames out seemingly alone. And when any project, software dev group, gaming server, anything, passes on the torch, such things should be taken into account. is @politas the only choice due to that? certainly not

**Comment by Ippo343** [comment]
I also think that we will need to address the policy we use to handle the mission director's role.
Here are my thoughts:
- @pjf proposed a 1 year term, which sounds reasonable to me;
- the role should be elective;
- imho, to be eligible the candidate should have contributed, at any level, to the project. All contributions should count (not only github contributions) as one user might have been very active on the forum or on the channel without ever pushing a commit;
- imho, the vote should not be restricted to the contributors, but also allowed to forum users; therefore, the vote should be held on the forum;
- however, the director should not be a dictator or boss, but (as @pjf said) its role should only be to have the final say in disputed matters.

Request for comments :)

**Comment by BobPalmer** [comment]
Also not a member of this project, but would like to add support for @politas, especially considering his immense aid in helping us through recent events.

**Comment by politas** [comment]
@Plague006, I'll be very sorry to lose your input to the project. I'd always considered our disputes to be minor ones, and you mostly had the better position when I thought about it. You've made enormous contributions to making CKAN work, and I hope you are proud of your achievements. 

I'd also like to thank you very much for all the help and advice you gave me as I was learning my way about here.

**Comment by Blu3wolf** [comment]
>imho, the vote should not be restricted to the contributors, but also allowed to forum users; therefore, the vote should be held on the forum;

Other than that one, all those proposals seem reasonable.

**Comment by NathanKell** [comment]
Yeah, tbh that seems like a _really_ bad idea.

**Comment by politas** [comment]
I was going to say I was uncomfortable with voting open to the forum, if only because I've been so visible there recently.

**Comment by Blu3wolf** [comment]
...thats a less than reassuring reason to have. 

Do you not need no other than simply 'forum users is an uncontrolled group with no controls over double voting, that is not a group with a vested interest in the election of a mission director for CKAN'? CKAN team members are essentially voting for someone to be a tiebreaker for them - that decision should rest with the team, not with a forum of thousands who dont have to work with whoever is elected. 
Sure, let forum users have their say - but they (we) shouldnt have the controlling interest in this.

**Comment by NathanKell** [comment]
Quite.

**Comment by politas** [comment]
My point is that I wouldn't like to have any voting skewed by a group of non team members who have only heard of me and don't know what other team members have been doing. 

Ok, so I'm accepting @pjf's nomination. Are there any other nominations? Can someone step up as electoral officer?

**Comment by Blu3wolf** [comment]
We can certainly agree it would skew the outcome, anyway. 
I suppose you could take @plague006 s comments as being a support for nominating @techman83 and @dbent for the role. Unless a team member wants to make that nomination though, and either of those personages accept, that would make you the de facto Mission Director @politas , from lack of competition.

**Comment by Divstator** [comment]
You might want to consider a liaison position for someone. I was very minor contributor to TES5Edit and Sharlikran more or less filled that role. It really helped to keep the "noise" level down so I could concentrate on what I was doing instead of becoming involved in less productive discussions. It can be difficult trying to balance where the project is going and keeping it on the rails, and also trying to deal with the "politics" involved. Politics are difficult enough as it is.

**Comment by nobodyhasthis** [comment]
# **Project Elrond**  
(aka The Martian / Lord or the rings meeting when we need it)

### In regards to a leadership discussion. Can I ask a silly question about the size of the role changes. What step up, down or sideways we are talking about?

Yeah. That is a strange way of thinking. I know. Let me talk about the position and not the people involved. Getting into a whole, "who did what and when" discussion. Is not something that is for me. We can get all sorts of user data out of Github. Yet even going over that to prove the point is useless. In fact I think this might lead to "mug slinging" and is not going to help. I don't think going down that road helps here.

This is a organization of volunteers. Spending their own free time. Sometimes without any tangible reward. Working on parts of project that they feel most comfortable with. The actual roles and responsibilities are flexible. If they are not flexible now they should be made so. People should feel that they can come and go. People should be allowed to change roles. Putting pressure on anyone to do something. Or making demands against any kind of schedule or job description. Is wrong and directly against the Code of Conduct of the project.

 A persons private life will change things around.  Sometimes people seem to be here playing around with KSP full time. Sometimes they mysteriously to drop everything and disappear for months. That does not affect anyone and is not noticeable. If your identified as a leader and off you go. Crap happens in your absence.

## **So who is in change around here?**
The does not have to be such a role most of the time. Everyone has their own set of technical skills. Strength and weakness. Just do what you can. When you can.

So people can grab a bit of of the project. Offer up a solution or advice and get feedback. This is kind of already built into the github workflow. There is tag for setting priorities. Ways to self assign tasks for team members. Sometimes stuff will get put up and nothing will happen. Please don't take offense. Look at the number of team members vs the list of outstanding work. 

On certain running issue reports. The leader is by default the the guy doing the heavy coding. Simple because he is the poor soul that has to submit a finished PR. They put code out there for public scrutiny. Give them the room please. Looking over their shoulder saying. Oh look you missed a bit. It is going to get a one figured salute and it blocks progress. 

## **The one ring to rule them all and in the darkness bind them.**
Unfortunately. there is some really tough decisions to be made. Sometimes there has to be a hero. Not the hero we want but hero we need.

### Sometimes we have two programming solutions to a problem. How do we pick one?

Lets talk about a simple example that will not upset people. That does not involve code. Hopefully. Sometimes the policy solution is counterintuitive. Oh boy do I get the depth of the problem here. I have got an outstanding issue report that has a whole list of reasons not leave it open. Where i do not support a certain course of actions. I can't close it and yet can't help but dismiss all suggested solutions.  I am now stuck in the hell of trying to repeatedly helping mod authors and end users that very rarely find the trap and fall in. 

So it is a catch 22 problem. 

It is going to come down to a pick of the lesser of two evils for some smarter than me to come out with a better solution. Any solution picked will upset people. Pick a sacrifice. There is no win/win. 
Even then it has to put put at the back of the queue when there more important stuff to be done. It is a low value task where the ROI is poor for people smarter than me. Sooner or later somebody is going to have to make a profession design decision. Or just flip a coin and pick a solution and close the issue.

### Then there is the question of an emergency situation. Once that requires an immediate response. One that we just don't have time to talk about?

The whole recent argument of delisting mods is a good example. I only want to comment on one aspect. The time between responses between everyone involved. It was a fire raging out of control on the KSP forums but a slow burner on Github. The very person that people wanted to respond was busy. As in I am just about pack up my life and travel to a conference on the other side of the planet. Plus there is another more personal matter to deal with. At least that is how I saw it. Please just don't ask me to justify that. I really don't want argue the semantics of all. It feels like we will be picking the bones out of train wreak. When things are moving too fast and people are losing it on line. Somebody has to yell all stop! With the authority to pull that stunt off.

### What happens if there is a flame war here on Github and people do need to take a time out?
 There are other better places to talk about sensitive topics. Github is not really a chat forum but neither should be an excuse to dump the problem onto the KSP forums. Somebody is going to to have to fix this communication dilemma. Especially if it is interfering with everyone else. Who just wants to keep on collaborating. This might mean responding to everyone and having authority to tell them to move along. Sometimes without taking sides in the argument.

Lets put this in a monty python style justification here. If two people want to have an argument over a dead parrot. Please don't expect us to help much. We too busy laughing or simply ignoring it. Please take it someplace else. Besides the parrot was nailed onto the perch. The point is I have now got the reader thinking of silly situations rather than dwelling too much on the recent events. I hope. Please don't go back there. It is not healthy. Lets move on in peaceful cooperation. 

## **## The council of Project Elrond.**
The after action report. First thing to do is take that bloody ring back off their finger. Then give us an honest appraisal of what happened. Failure **is** an option. If we want to change the decision made. After a really good long heart to heart talk. It is ok. If we to have rewrite another project policy statement. Raise an issue and work the problem. Admittedly this sometimes has to be done after a train wreck.

 Sorry but the ring bearer carries a heavy price. Project accountability. Getting bashed with the Code of Conduct. The risk of doing the wrong thing. Possible public humiliation.  A risk of mental health damage. Seriously, they might need therapy. 

## **## Then return to a leaderless project management environment.**
Ok enough of that. Who wants to do stuff. Best cool idea wins today. Tomorrow we get to decide again. Lets play.

**Comment by nobodyhasthis** [comment]
Also worth mentioning that apart from trying to knock up a leadership policy. Now is the time for everyone to accept the most import policy in the project https://github.com/KSP-CKAN/CKAN/wiki/Code-of-Conduct. This is also the rules of the ban hammer should the leader elect to use that. Also set a principles everyone should know.

**Comment by Dazpoet** [comment]
As someone who hasn't been very active I have a heard time saying yay/nay on who should steer the ship (is that even a saying in english?) but a great big thank you to @pjf who made me feel extremely valuable even though I "just" started out editing the wiki long ago.

Now for some reasoning: From what I've seen on irc and by looking in a few places on the forums it seems @politas is currently active and trying to untangle some messes. A giant plus for him, in my view, is that @pjf have named him and to me that means a lot. As such I vote yay, assuming I'm allowed to vote with me being somewhat unactive atm, goddamn rl!

I'm going to assume that our CoC will remain as is, as @nobodyhasthis points out above, with the change of leadership? To me that might be one of the most important parts.

**Comment by politas** [comment]
I am certainly fully behind the CoC. It is one of the things that encouraged me to be active in this project, and the lack of similar has turned me away from other projects. Really, apart from the titular change, the only real change has been to one policy, and it's only a small modification (albeit one that some consider to have significant impact). I'm really hoping some other team members can find some time to do a few merges and advise fixes to submitted metadata, at least. I haven't had time to play KSP in over a fortnight (as much thanks to electioneering as CKAN stuff).

**Comment by solarsootysmudge** [comment]
@politas Noticed you recently updated contact details on the CoC. Should the worst happen people know there is help. Must say thanks for this and for stepping up to a very big job.
