### ISSUE TITLE
CKAN no longer detects or honors version from readme.txt

### ISSUE THREAD

**Issue by cgruber** [KSP-CKAN/CKAN#1903]
**CKAN Version:** 

v1.20.1 (though it also was failing in v1.18.1)

**Operating System:** 

Mac OS X 10.11.6

**The issue you are experiencing:** 

CKAN lists the version as 1.2.0.1479 no matter what happens to the readme.txt file.   Changing the version in the readme.txt file doesn't affect it.  Removing the Version line from that file has no effect.  Deleting the readme.txt has no effect.  Somehow CKAN is obtaining the version number from another source, and refusing to honor the version in the readme. 

I've tried reinstalling the game, I've tried blowing away the CKAN directory.  I can't seem to find any way to make it recognize even the missing readme let alone respect the version setting.

**How to recreate this issue:** 

Alter the version in the readme to an older version (say, 1.1.3) and do `ckan list`

**Comment by politas** [comment]
This is by design. Squad advised us that readme.txt was not a reliable indicator of the correct CKAN version. As of 1.18.1, CKAN switched to using the buildID.txt file as a first preference, and 1.20.1 further changed to use the highest version number between buildID.txt and buldID64.txt.

If you wish to convince CKAN that you have a different version of KSP installed, you could either edit your buildID.txt and/or buldID64.txt to match [the table we maintain](https://github.com/KSP-CKAN/CKAN-meta/blob/master/builds.json), or rename the buildID.txt file and CKAN will fall back to the readme.txt.

**Comment by cgruber** [comment]
Ahh.  Perfect.  I looked for documentation about this on the wiki and
didn't see it.  Thanks!
