### ISSUE TITLE
Add "Expert Mode" toggle (install outdated mods)

### ISSUE THREAD

**Issue by Metadorius** [KSP-CKAN/CKAN#1931]
CKAN is great instrument for installing and managing mods, but it lacks one much needed function - installing any listed mod, not only those mods that has been "updated". I propose adding the "expert mode" toggle that allows one to install any mods. If user toggles it, the attention "you're doing this at your own risk etc. etc." will pop out.

I'll be very grateful if this function will be added to CKAN :)

**Comment by politas** [comment]
You can do it via the command line. That's expert mode.

**Comment by Metadorius** [comment]
Why I should trade comfortable GUI for ability to install "outdated" mods when I can have both?

**Comment by politas** [comment]
Because none of the current coders are interested in adding that feature to the GUI, so you actually can't have both. If you'd like to develop the feature and submit a code PR, we always welcome positive contributions. In the meantime, we have a whole bunch of bugs and features that aren't already available that we want to work on first.
