### ISSUE TITLE
Deselect all button.

### ISSUE THREAD

**Issue by Necessarycoot72** [KSP-CKAN/CKAN#1945]
This isn't relay an issue but a suggestion. I have a lot of mods and i would like trim it down (long load time) so I thought I would deselect all of but I couldn't find a button. So I had to painstakingly deselect 100 mods so I could start from scratch. 

I hope this is the right area to put this. O never relay understood how to navigate GitHub.

**Comment by ayan4m1** [comment]
Historically, I think the reason this was never added is that every single install/uninstall check toggle triggers a fairly large amount of work in dependency resolution. It's unfortunately more complicated than it might appear to the end user, but I think it's a very good idea because if we can get there it will mean we have improved the architecture of the application such that clicking a single cell doesn't trigger ten thousand lines of code. @politas can you comment regarding how aggressively you want to target the list view performance?

**Comment by politas** [comment]
I suppose we could have a '"clean out your KSP" button with a confirmation dialogue that bypasses the dependency checking and simply deletes all installed files and clears the installed mods part of the registry. It's a bit hacky, though.
