### ISSUE TITLE
Don't fail all updates if one download fails

### ISSUE THREAD

**Issue by Svish** [KSP-CKAN/CKAN#1954]
When updating several mods, sometimes one fails to download (probably because of my garbage internet connection). It would be nice if it actually continued and completed the ones that did download OK, rather than seemingly aborting the whole process.

Currently I get an error message, and then only have a Cancel-button which takes me back to the list of mods which looks the same as before. I.e. the ones with new versions are still not listed as up to date.

So yeah.. would be nice to instead of getting an error message and a Cancel-button, a summary of which ones failed and which ones were OK. And every mod that was downloaded OK should've been updated too, maybe except if they depend on one that failed.

**Comment by theimportantperson** [comment]
In the meantime, filter the repository by "cached mods" after that.  Then, you can just reselect the mods you've already downloaded but didn't install

**Comment by politas** [comment]
In order to install some mods of a selected set, we would need to recalculate the dependencies to see if the cached mods are consistent, which would slow things down considerably.

**Comment by gajbooks** [comment]
At the very least, an automatic retry or two would not go amiss. It's virtually impossible to download significant numbers of mods on a slow internet connection overnight because of all the download failures which require user interaction. (I have this issue as well)

(I don't want to assume anything about how the program is structured, but shouldn't verifying dependencies be relatively straightforward? Read cached mods, traverse up the tree of dependencies and verify that each of those mods is also cached? I'm probably vastly oversimplifying here, so don't take this too seriously.)

**Comment by politas** [comment]
The next release will be taking the download/caching process out of the time limited installation unit, which will ease this issue.
