### ISSUE TITLE
When selecting a mod, all other mods go black.  When unselecting the same mod, stays black

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1967]
Steps to reproduce:
1. Start CKAN
2. add "tac" to filter by mod name
3.  Select Filter(compatible)
4.  Select 1.2 in compatible ksp versions
5.  Select TAC Life Support (TACLS)

See the images on the following images:

![ckan1](https://cloud.githubusercontent.com/assets/1630166/21568975/c2af4e5c-ce86-11e6-8b5b-302667e8416a.png)
![ckan2](https://cloud.githubusercontent.com/assets/1630166/21568976/c6089acc-ce86-11e6-96fe-efec2e25fb7f.png)
![ckan3](https://cloud.githubusercontent.com/assets/1630166/21568977/c83ed392-ce86-11e6-939a-5a505330101e.png)

**Comment by linuxgurugamer** [comment]
No need to select anything other than the current in the compatible ksp versions

**Comment by Rohaq** [comment]
This is happening to me, and seems to occur when the selected mod conflicts with another mod (see attachment). Can you click away from the TAC mod and confirm it's background has turned red?

I think it's related to this change, which uses SystemColors..ControlText instead of Color.White: https://github.com/KSP-CKAN/CKAN/pull/1926/files?diff=unified - Running the following powershell module shows this as black on my system: https://gallery.technet.microsoft.com/scriptcenter/Get-SystemColors-using-WPF-d7c31a8c

![6urwgxa 1](https://cloud.githubusercontent.com/assets/246865/21571190/b130cc6c-cec4-11e6-9639-f935c7ff8ca6.png)

**Comment by linuxgurugamer** [comment]
No, that does not happen.

But it is a conflict, USI-LS has a conflict with TACLS

**Comment by politas** [comment]
Right, yes, I can reproduce this on Linux when selecting conflicting mods, too.
