### ISSUE TITLE
Latest Version of CKAN is Infected with Trojan SONAR.hueristic.156

### ISSUE THREAD

**Issue by Kamiyosha** [KSP-CKAN/CKAN#1973]
so, I've had CKAN for a good year or so now, and this latest update (v. 1.22.1) keeps getting murdered by my computers antivirus software (Norton One). when I get the details as to why, the AV tells me that the software contains SONAR.hueristic.156, which is a Trojan horse that seems to find its way into a lot of crowd sourced websites like this. I don't want to shut off my AV just to run a program, so would you look into this for me and see what exactly is going on? I would hate for you guys to start suffering hidden virus tags being added to your website, your one of the good ones.

**Comment by politas** [comment]
I'll get onto Norton

**Comment by politas** [comment]
In fact, it isn't even accurate to say that SONAR.hueristic.156 is an "infection", since it is a behaviour detection, rather than specific code.

In any case, Symantec have verified my whitelisting submission and "as such this detection will be removed from [their] products." May take up to 24 hours for the update to come through.

**Comment by Kamiyosha** [comment]
Ah thank you! See, google said it was a trojan, which is why i was very concerned about it. I thank you again for your timely response and digging you did to see this issue done with.
