### ISSUE TITLE
Can't close CKAN if not connected to the internet while refreshing mod list

### ISSUE THREAD

**Issue by fat-lobyte** [KSP-CKAN/CKAN#1981]
**CKAN Version:** 
v1.22.1-0-g174271a

**Operating System:** 
Windows 7, 64 Bit

**The issue you are experiencing:** 
CKAN is not closable with the "X" while the "Updating repositories" operation is running. If no internet connection is present when refreshing, sometimes this operation never finishes (not even when restoring the internet connection). Since the Cancel button is greyed out and the X-Button on the window does not react, there is no way to cleanly shutdown CKAN. You are required to kill CKAN via the task manager.

Additionally, if CKAN is then killed, the CKAN.ModuleNotFoundKraken is shown at every subsequent start, until a refresh is successful.

**How to recreate this issue:** 
1. Start CKAN
2. Disable your computers internet connection
3. Click refresh
4. Observe that there is no way to escape CKAN now.
5. You are trapped forever.

**Comment by LordFlashmeow** [comment]
The Kraken has caught up with you!
In addition, the exception comes up when you select a mod or change the filter, too.
It's a real pain when you're offline and want to check what mods you have installed.

Also happening with v.1.22.3 on Windows 10

I would suggest that this is a bug, not an Enhancement.

**Comment by politas** [comment]
Can you check if the crash after killing the app is still happening on Windows 10? We seem to have fixed the recovery on Linux at least.

**Comment by LordFlashmeow** [comment]
After killing the app and reopening it, the app doesn't crash, it just gives the unhandled exception error when you try to do anything.

**Comment by politas** [comment]
Is that with v1.22.6 of the CKAN client? Can you post the unhandled exception error message details?

**Comment by HebaruSan** [comment]
This happens because GUI cancels closing if the main menu is disabled:

https://github.com/KSP-CKAN/CKAN/blob/2f3d817f14bc399337ff5dd12f9ee3a32f9bb566/GUI/Main/Main.cs#L435-L442

And it disables the main menu during registry update:

https://github.com/KSP-CKAN/CKAN/blob/2f3d817f14bc399337ff5dd12f9ee3a32f9bb566/GUI/Main/MainRepo.cs#L28-L38
https://github.com/KSP-CKAN/CKAN/blob/2f3d817f14bc399337ff5dd12f9ee3a32f9bb566/GUI/Main/MainRepo.cs#L45-L48

It also disables the main menu when you click Apply in the change set tab to start an install:

https://github.com/KSP-CKAN/CKAN/blob/2f3d817f14bc399337ff5dd12f9ee3a32f9bb566/GUI/Main/MainChangeset.cs#L34-L36

I would have to investigate to determine whether closing the app in these situations would cause problems. Hopefully judicious use of transactions and exception handling would at least not corrupt the registry if operations don't complete.

**Comment by HebaruSan** [comment]
This would be good to address with https://github.com/KSP-CKAN/CKAN/issues/1238, the user ought to be able to cancel out of updating with a broken network connection, and an unreachable repo should revert you to whatever registry you had before.
