### ISSUE TITLE
Linux users, please oh please yum install libcurl-devel

### ISSUE THREAD

**Issue by radistmorse** [KSP-CKAN/CKAN#2000]
Just a little nitpick: yum was replaced by dnf for almost two years already. So it should be dnf install libcurl-devel

**Comment by politas** [comment]
Thanks for the advice. I've updated the latest release notes and will use the new code going forward.

**Comment by techman83** [comment]
Note, Fedora isn't the only distro and from my quick search it was the first to default it. Is it supported in all RPM based distros? Users may be using an older LTS style release eg. Ubuntu 14.04 (I realise it's apt based, but my rpm knowledge is limited) and it's still widely used.

Be worth ensuring we aren't creating a support burden. dnf is technically superior, but that doesn't help us if it's not universal yet. If it is universal across distros within our support scope, carry on :-)

**Comment by politas** [comment]
The note is specifically referring to Fedora

**Comment by radistmorse** [comment]
when it comes to RPM, there are two distros that use it: RHEL and fedora. RHEL has derivatives, mostly based on CentOS (which is basically a non-commersial version of RHEL). There are two point to note:

1. Recent RHEL uses dnf, which means that all the derivatives do too.
2. Of all these distros only fedora is considered a desktop OS. I can't think of a person who in the right mind would try to launch KSP on RHEL.

**Comment by techman83** [comment]
Excellent, my non Debian knowledge has increased. Thanks for the clarification @radistmorse

**Comment by Commissar0617** [comment]
@radistmorse I would.... for... reasons

**Comment by politas** [comment]
Sounds like we're cool with just mentioning dnf going forward.

**Comment by ayan4m1** [comment]
Depending on distro you could be using any of the following for package management:

* yum
* apt
* dnf
* portage
* pacman
* zypper

And this list is incomplete, there are a few less common ones like Entropy...

Might be worth refactoring the docs so they ask the user to "use the appropriate package management command" or similar. Personally I don't care if it stays as `dnf` everywhere but we should ensure the references are consistent, especially because the package names being mentioned are also likely to be somewhat distro- and distro-version-specific.

**Comment by politas** [comment]
We give a couple of examples, for the most-used packaging systems. I think that's enough to get the point across.

**Comment by politas** [comment]
Our `"Installing CKAN on <Linux version>"` pages could use an update, certainly.
