### ISSUE TITLE
Search Boxes out of order when pressing tab. 

### ISSUE THREAD

**Issue by Marsfan** [KSP-CKAN/CKAN#2007]
Just a minor aesthetic issue, but the search boxes (mod name, author name, description) are out of order when pressing tab. If one is in the mod name box, pressing tabs goes to description, then jumps back to author name. 

CKAN 1.22.1
Windows 10 64bit

**Comment by politas** [comment]
Slight complexity in fixing this due to the weird reversion bug we have every time someone uses the VS interface editor on the main window. It should be a simple fix, and even the reversion bug is only a code compilation warning that doesn't have an end-user impact, so this should be relatively easy to fix.
