### ISSUE TITLE
KSP folder not recognized, and inability to download/update mods

### ISSUE THREAD

**Issue by DarthGabrich** [KSP-CKAN/CKAN#2025]
CKAN Version: 1.22.1

Operating System: Windows 10 

The issue you are experiencing: I am not able to download new mods, or update the ones I already have installed

CKAN error codes (if applicable): "Failed to connect to repository. Exception: Trying to write C:/Kerbal Space Program/GameData/GroundConstruction/Icons/applauncher-icon.png but it already exists."

This happens every time I open up ckan, and it means I can not add a mod. Also, I tried to select a ksp install, I can't choose my KSP folder because I need a "buildID*.txt" file... (this does not seem normal)

Thanks for the help,
PS: I managed to install a few mods the first time I got ckan, but nothing since

**Comment by politas** [comment]
There was a change in the last CKAN release that means you now select the BuildID*.txt file rather than the folder to add a KSP instance. It is intended to allow people to browse parts of their filesystem that were not previously accessible by changing the system call we use. You should have either a BuildID.txt or BuildID64.txt in your KSP folder. Select that file and you will be able to add your KSP instance.

That's a bit of an odd exception message. Try deleting GroundConstruction and reinstalling it.

**Comment by DarthGabrich** [comment]
thanks a lot man, problem fixed!
