### ISSUE TITLE
Mods crash game before the title menu!

### ISSUE THREAD

**Issue by kerbalkommander** [KSP-CKAN/CKAN#2030]
This might need to be on the KSP Forum, so let me know if so, but my KSP crashes _before_ reaching the title screen. My first, and last, mod combos are in these files, respectively:

[output_log.txt](https://github.com/KSP-CKAN/CKAN/files/907557/output_log.txt)
[output_log.txt](https://github.com/KSP-CKAN/CKAN/files/907558/output_log.txt)

I would really appreciate if someone could tell me how to fix! (I need mods! Game without mods just isn't the same!)

Thanks to any replies (even rude/unrelated ones, as they may bring the attention of... someone important),
-KerbalKommander

**Comment by politas** [comment]
Are you on the Pre-release  1.2.9 version on Steam? I had the same result when I discovered Steam had remembered my previous Pre-release signup. 1.2.9 is _very_ mod-breaking.

**Comment by kerbalkommander** [comment]
No, I use the Steam 'stable' variant, to prevent uber-crashes. However, the game _was_ notoriously crashy (despite excellent stability) before the updates that seem to have caused this.

**Comment by politas** [comment]
`AssemblyLoader: Exception loading 'InfernalRobotics': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 `

That loks like your problem - Check your Infernal Robotics installation against the zip file. if CKAN has installed it incorrectly, let us know, otherwise, take it up with the IR devs.

**Comment by Olympic1** [comment]
The last Infernal Robotics release was for KSP 1.1.3. Since then there were only pre-releases for KSP 1.2.x but those don't get indexed.

**Comment by kerbalkommander** [comment]
So, in short, wipe IR from the entirety of existence (on my machine)? I had already suspected IR as the cause, but always good to get a second opinion. Thanks guys (and/or girls)!

**Comment by politas** [comment]
Sounds like the answer!
