### ISSUE TITLE
metapackage installs recommends of dependencies, even if they're listed as conflicting

### ISSUE THREAD

**Issue by lamont-granquist** [KSP-CKAN/CKAN#2039]
With this metapackage i'm trying to install EditorExtensionsRedux, but definitely not install KSP-AVC

```
{
    "spec_version": "v1.6",
    "identifier": "test",
    "ksp_version_min": "1.2.2",
    "name": "test",
    "abstract": "test",
    "author": "lamont-granquist",
    "license": "GPL-3.0",
    "kind": "metapackage",
    "depends": [
      {
        "name": "EditorExtensionsRedux",
      }
    ],
    "conflicts": [
        {
            "name": "KSP-AVC"
        }
    ],
    "version": "0.0.1"
}
```

what i get is:

```
% ckan install test
About to install...

 * Editor Extensions Redux 3.3.12
 * The Janitor's Closet 0.2.17.1
 * Filter Extensions - Plugin 2.8.1.2
 * Module Manager 2.7.5
 * Filter Extensions - Default Configuration 2.8.1.2
 * KSP AVC 1.1.6.2

Continue? [Y/n]
```

I'm both surprised to see the rest of the recommended modules there since the wiki states that "Metapackages will not show suggestions and recommendations from the mods within them", and doubly-surprised to see that the conflicts is ignored.

This is the output with `--no-recommends`:

```
% ckan install EditorExtensionsRedux --no-recommends
About to install...

 * Editor Extensions Redux 3.3.12

Continue? [Y/n]
```

**Comment by politas** [comment]
The CLI will install recommends by default, if you don't use `--no-recommends`
So what's happening here is that EditorExtensionsRedux is recommending JanitorsCloset, which in turn is recommending KSP-AVC.

In order to check incompatibilities, we bundle all the modules we are installing after following the depends (and recommends by default for the CLI) into a collection and then check them. During that process, any "metapackage" is dropped from consideration, since it is not installing any files. This effectively means that "conflicts" relationships are not valid for metapackages. We should probably clarify that in the spec.

I will point out that if we were checking conflicts on metapackages, the installation of the metapackage you have created would simply fail without `--no-recommends`, since you would be attempting to install a set of packages including a conflict. The CKAN client is certainly not smart enough to follow some "recommends" but not others based on "conflicts" relationships.

**Comment by lamont-granquist** [comment]
Okay, the wording in the wiki seems a bit off then, so maybe its a doc bug?  Also, failing hard on the conflicts would be fine, I went down the road of constructing things around always using `--no-recommends` and if it just fails to install without that, it'll prevent me from accidentally messing up the install if I haven't had enough coffee in the morning and forget.

**Comment by lamont-granquist** [comment]
And so obviously there's a thing that I'm trying to do here -- which is control the recommended packages of dependent packages via some setting in the metapackage, which seems like useful use case, but the UX is pretty clunky.  I don't really have a good suggestion for UX though without introducing more knobs and switches.  I can see how metapackages were probably removed from conflict detection for a reason.

**Comment by politas** [comment]
Yes, I can see that's what you'd like to do, but the client just won't support it. Have you tested it in the GUI?

**Comment by lamont-granquist** [comment]
I'm on Mac, abandoned the GUI long ago, don't think I currently even have it working right now...

**Comment by politas** [comment]
Ok, I tested it, and adding a metapackage in the GUI operates as if run `--no-recommends`. 

My recommendation would be to specify all the recommended mods you want to be included, and use the `--no-recommends` option when installing.

**Comment by lamont-granquist** [comment]
Yep that's where I wound up.
