### ISSUE TITLE
CKAN will not run on command line or GUI in macOS Sierra

### ISSUE THREAD

**Issue by TheEntangledHatMan** [KSP-CKAN/CKAN#2069]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
v1.22.3+64309722a446

**Operating System:** 
macOS Sierra 10.12.5 (16F73)

**The issue you are experiencing:** 
CKAN always outputs error:
`2397 [1] ERROR CKAN.KSP (null) - Could not find KSP version`

**How to recreate this issue:** 
Download CKAN.exe on macOS Sierra 10.12.5 (16F73) and latest Mono (5.0.1.1) and run the following command in Terminal:
`cd ~/Downloads`
`mono ckan.exe ksp list`

**CKAN error codes (if applicable):** 
2397, CKAN.NotKSPDirKraken

The full command line output:
[CKAN Error.txt](https://github.com/KSP-CKAN/CKAN/files/1065506/CKAN.Error.txt)

**Comment by MICROhub6** [comment]
I've been trying get CKAN to work recently and I've done basically the same things you have here, but instead of typing "mono ckan.exe ksp list" I have just been typing "mono ckan.exe". This is what it says to do here: https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-OSX
I added "ksp list" to the end of mine and the only thing I got was a line that said
"Name Version Default Path"
and then a line under that: "----  -------  -------  ----"
So try just typing "mono ckan.exe" and it might work. Right now I'm having a completely separate issue after I open CKAN which is trying to find the KSP file.

**Comment by politas** [comment]
Ok, so the trouble you are both having is that CKAN can't find the location of your KSP game directory. You'll need to find the full path to your game directory and run this command:

    mono ckan.exe ksp add <name> </full/path/to/ksp/>

Where <name> is a meaningful name for the specific ksp installation. Then you should be able to launch ckan normally.

**Comment by MICROhub6** [comment]
Ok, thanks! This worked. I wasn't familiar with the command line interface for this program and its commands. I created a separate issue for this that I can know close. However I've been trying to forget the first install that I added and add a different one. I can't seem to forget the first one or add another one. Both are in /Applications.
