### ISSUE TITLE
[Feature] Color Outdated

### ISSUE THREAD

**Issue by VasVadum** [KSP-CKAN/CKAN#2093]
I'd like to suggest that CKAN be altered to color outdated installed mods orange, like KSP updating to 1.3 would make a.. 1.22 mods be colored orange to let the user know which mods are out of date.  I have 61 mods, and had to carefully go through mods and try to figure out which ones were out of date.

Perhaps a system built into CKAN that allows CKAN users to reort a mod as functional or disfunctional with their current game version.  A new column after "comment" at the end that'd have a colored thumbs up/down icon (green/red), with a number next to it in green showing how many people said it works, and red showing how many people said it doesn't work.  This would help in automating a little bit of CKAN not requiring so much work being done inside it all the time to mark things again later on by hand.  The CKAN users would just have to hopefully be honest and others would have to decide whether or not to trust the word of others.

**Comment by politas** [comment]
We have various filters which make the basic request pretty simple. You can click also on column headings to sort by a particular column. The easiest way to find the info you are seeking here is to select the "incompatible" filter, then click on the "Installed" column header to put all your installed mods at the top of the list.

For the expanded system, I am leery of the prospect of having users effectively vote on the compatibility (and thus suggested availability) of mods. We don't currently upload any data from users, and changing that would require significant discussion

**Comment by HebaruSan** [comment]
Voting is a creative solution to crowd-sourcing metadata integrity checks, but implementing it would present many design decisions relating to the scope of a given vote that have no good general answers.

- Suppose a mod is marked as compatible with both KSP 1.3.0 and KSP 1.3.1. You're using 1.3.0, I'm using 1.3.1. I click a down thumb because I found a problem; should you see that vote? How could either user know whether a problem is version-specific?
- Suppose a mod has many current downvotes because of a problem with its metadata, which is then corrected. Should the downvotes be cleared? What if the problem was intrinsic to the mod rather than the metadata, and again how could a user know the difference?

I do kind of like it as a "where there's smoke there's fire" approach though. If we could sort the bot status page by the number of downvotes in the past 48 hours, issues could be identified before formal reports are made (with the caveat that fixing them won't always be a CKAN team task).

**Comment by HebaruSan** [comment]
Ignoring the voting part for the moment, I think this need is satisfied by the KSP-AVC-like warning from #2601; a user who upgrades from KSP 1.2.2 to KSP 1.3.1 would be warned about any modules that are no longer compatible when they click Launch KSP:

![image](https://user-images.githubusercontent.com/1559108/80557920-1ea21c00-899e-11ea-974e-faabde08c3f5.png)
