### ISSUE TITLE
Spacedock.info Connection Refused

### ISSUE THREAD

**Issue by amdorj** [KSP-CKAN/CKAN#2104]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
CKAN v1.22.3 KSP 1.3.0.1804
**Operating System:** 
Windows 8.1 x86_64 (NT 6.3, Build 9600)
**The issue you are experiencing:** 
Spacedock.info fails to load. In CKAN, it displays an error saying "Unable to connect to the remote server
When download link is opened in Google Chrome v60.0.3112, the "Connection Refused"(ERR_CONNECTION_REFUSED) error page is displayed.
**How to recreate this issue:** 
Try to download any mod hosted on SpaceDock.info, such as Interstellar Fuel Switch or Fuel Tanks Plus.
**CKAN error codes (if applicable):** 
Unable to connect to the remote server

Edit: new error codes being reported

**Comment by StollD** [comment]
You should probably report these kind of issue to the [#spacedock](http://webchat.esper.net/?channels=spacedock) IRC channel on irc.esper.net, or to the [SpaceDock forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/159581-spacedockinfo-mod-hosting-site), since the CKAN team can do nothing about it.

In other news: SpaceDock should be back online

**Comment by amdorj** [comment]
SpaceDock is back online, please close this issue.
