### ISSUE TITLE
ckan just won't start

### ISSUE THREAD

**Issue by Schnobs** [KSP-CKAN/CKAN#2129]
**CKAN Version:** v1.22.2 Mahia

**Operating System:** Debain

**The issue you are experiencing:** 
Download/unpack ksp 1.3.1
prompt$> wget https://github.com/KSP-CKAN/CKAN/releases/download/v1.22.3/ckan.exe
prompt$> mono ckan.exe
..."nothing" happens.

**How to recreate this issue:** 
repeat the above steps.

**CKAN error codes (if applicable):** 
none.

---
It's not quite that nothing happens. When I terminate it with Ctrl-C and try to run it again, I'm told that registry.locked has been created. I don't see any other output anywhere, though.

The fun part is that I can run the very same version of ckan from my ksp1.3.0 directory, select the new 1.3.1 install, and manage mods. The versions are identical:

prompt$> md5sum ckan.exe  ../ksp131/ckan.exe 
eb7a7acb24738b6fb2b535c8e46f8722  ckan.exe
eb7a7acb24738b6fb2b535c8e46f8722  ../ksp131/ckan.exe

I'm aware that "nothing happens" doesn't make a good bug report. Any advice on how to investigate this further?

**Comment by politas** [comment]
Do you have mono-complete installed?

**Comment by Schnobs** [comment]
Yes.

As said above, a workaround exists: I can run CKAN from my previous KSP directory and use it to manage the mods of the new install.

The problem only occurs when I want to run the ckan binary from the folder of my current KSP install. Which strikes me as a bit odd.

**Comment by politas** [comment]
So you have two copies of ckan.exe? I think that may be your problem. What desktop environment do you use?

**Comment by politas** [comment]
Let me explain my Ubuntu-based setup. I have ckan.exe stored in a completely unrelated directory (In fact I use my local build directory in order to test the development branch) I then have a ~/bin/ckan shell script that contains this:

    env GTK2_RC_FILES=/usr/share/themes/Green-Submarine/gtk-2.0/gtkrc mono /path/ckan.exe "$@"

With that, I have no problem using CKAN on any copy of KSP I have created. I run without a default ksp instance, so every time I launch, I get the "Choose KSP instance" dialog, and I can run CLI ckan commands just by typing `ckan <command> <data>`. The "env GTK2_RC_FILES" is probably not required. I added it at some point in an attempt to change the appearance of the CKAN window, and I don't think it actually worked.

**Comment by Schnobs** [comment]
Sounds like a good scheme. Given that my currently working CKAN is in an inconvenient place, how do i clean up my system so I can put it elsewhere?

**Comment by politas** [comment]
Clean out ~/.mono/registry/CurrentUser/software/ckan/ and put the ckan.exe anywhere you like.

**Comment by Schnobs** [comment]
Thank you very much. 
(as far as I'm concerned, this can be closed)
