### ISSUE TITLE
Updater can't deal with spaces in path

### ISSUE THREAD

**Issue by Xandaros** [KSP-CKAN/CKAN#2140]
**CKAN Version:** 1.22.4

**Operating System:** Arch Linux with Linux 4.13.4

**The issue you are experiencing:** 
I opened CKAN and was told there was an update. I opted to install said update and it seems to have worked fine. However, I believe the updater was meant to start CKAN again after the update, but all I got was a message on the terminal:
```
Cannot open assembly '/media/ssd1/steam/SteamApps/common/Kerbal': No such file or directory.
```

This looks to me like it did not quite understand the spaces in the directory name. (The full path would probably be `/media/ssd1/steam/SteamApps/common/Kerbal Space Program/ckan.exe`

**Comment by HebaruSan** [comment]
There's a 2 year old commit that looks suspiciously like it was intended to fix this by putting quotes around the path: https://github.com/KSP-CKAN/CKAN/commit/8b882ceb460cffdd3dd08359c7311988a3ba3aad

On Unix we would use one of the array-oriented versions of `exec` so there would be no parsing involved. Maybe there's a similar way to handle command line parameters in mono...

**Comment by HebaruSan** [comment]
That commit happened after the CKAN-autoupdate repo was retired -- _but ckan.exe is still using it!_

https://github.com/KSP-CKAN/CKAN/blob/6aac4882af4cfd089d03ef4f3eb4143d14036efa/Core/Net/AutoUpdate.cs#L24-L25

When you try to auto-update, it downloads the `ckan_update.exe` from the latest release on that repo, from **[June 30, 2015](https://github.com/KSP-CKAN/CKAN-autoupdate/releases)**, and runs it. No fixes since that date have had any effect. So to fix this issue, we would need to update that code to use the most recent version of `ckan_update.exe` somehow. But I don't think it's currently uploaded anywhere, so we would probably have to modify the travis-ci config to start building and uploading it.
