### ISSUE TITLE
Feature request: reinstall

### ISSUE THREAD

**Issue by Real-Gecko** [KSP-CKAN/CKAN#2154]
Would be nice to have "Reinstall" button, so that mod is removed and unpacked again, just in case user messes up with mod files.

**Comment by politas** [comment]
Is removing and installing as a two step process  that much of a headache? We can clutter up the UI with separate buttons for every possibility, I suppose...

**Comment by Real-Gecko** [comment]
Sometimes it happens that other mods depend on mod in question, so uninstalling it will trigger uninstallation of dependants. I agree that button is not quite a good idea, maybe right click dropdown?

**Comment by politas** [comment]
Would you be happy with a Command Line implementation only?

**Comment by politas** [comment]
Another possibility is to start using the Mod Versions panel to give us extra functionality - Install a specific version, reinstall current version, set AD version, download selected version...

**Comment by Real-Gecko** [comment]
Shame to ask, but what is Mod Versions panel?

**Comment by linuxgurugamer** [comment]
The panel on the right, where it shows you information on the mod, the tab is Versions

**Comment by Real-Gecko** [comment]
Yep, I think that'll be pretty cool.

**Comment by Olympic1** [comment]
I worked on a right click menu and could add this option to the menu. But we'll need a process for the `reinstall`. I thought of the following:

We uninstall the mod, so that we have clean install, and then install the mod again. When doing this it will remove its dependants, so could this be possible without removing its dependants?

**Comment by Real-Gecko** [comment]
Well, maybe something like a dirty hack: remove mod folder, unpack mod from cache like it's done while installing the mod?

**Comment by politas** [comment]
Should be able to do it like an upgrade, but to the same version instead of the new version.

**Comment by solarsootysmudge** [comment]
As much as like the comments and suggestions so far. I got to bring up the whole policy of not deleting folders on uninstall thing again. I believe that that effects the above conversation and should be considered further.  

CKAN can't never be trusted to do a full reinstall with every mod without end users making a choice of how to handle config files created by the mod at run time. There are mods that install files **after** the CKAN process is completed. The policy rule has been if CKAN did not install it those extra files. It can't remove them.

Removing and installing as a two step process that is easy to do. However some mods make it more complicated. Once the mod is uninstalled in CKAN. The end user must manually check if the mod folder still exists.  Depending on the mod the files left behind can be considered safe to leave in place or they must be manually removed. After this manual folder check. The mod can be reinstalled. How often does the extra mod created files problem come up. I think it is still rare and always has been. None the less it has been the root cause of a whole bunch of arguments over the years. 

Still I think it is worth considering if config files created by the mod at run time can any impact on putting in a button that does an a reinstall action. How to handle an automated action where these extra files exist after mod removal?

**Comment by 7ranceaddic7** [comment]
How to handle an automated action where these extra files exist after mod removal?

Ask the user, "Do you want to remove all files and folders associated with this mod?"

**Comment by linuxgurugamer** [comment]
I support this, for the following reason:

Example:  I uninstalled Tweakscale, but MM was still applying various Tweakscale patches.  Turns out that the directory was still there, and MM saw it.

I think that the extra mod-created files can be a real issue, especially if someone is trying out a lot of mods trying to settle on a good mix.

When asking the question, you will have to consider the fact that more than one mod may be removed at the same time.  So the question would either have to be global, for all mods being removed, or asked for each mod being removed.

**Comment by HebaruSan** [comment]
The discussion of uninstalling with mod-generated files is probably best had at #653. That issue is much broader than a reinstall feature, and whatever solution is figured out in the general case would apply here the same way.

**Comment by solarsootysmudge** [comment]
The best place to look is my rather verbose research at #1610. Where I did do a deep dive into all the passed issues including #653. The short answer is. It is a bigger can of worms that first appears. It has never been completely solved but I do think it was made as easy to fix as possible for end users. 

Longer answer: Since then we first talked about this there have had two merges that have made this even more rare. Links to those also included at the end of #1610 too.

Force reinstall on dependency change. Some mod authors would change them without a version bump in the mod. Leading to state where the local client files did not update even although metadata was changed in the main repo. Might be worth looking at this one for new ideas for reinstall use cases.

There was also the removal of an mod empty folder added in. As @linuxgurugamer  says above this is the biggest problem. MM can install patches based on `FOR` or `NEEDS` logic. Leaving a just a folder is enough to get bad installs. The catch here is if the mod author has created an extra file at run time. The new feature will not delete the folder. 

@7ranceaddic7 I agree that the answer could be as simple as.  Ask the user, "Do you want to remove all files and folders associated with this mod?" Then following through on folder removal regardless of what it contains. Whilst the counter argument has always be "CKAN will never delete files it does not install"

So far the biggest progress made is when documentation was put up explaining how to do a proper clean reinstall. The ability to export a mod list and use that to rebuild everything is powerful. If most end users followed that advice there. A lot of support issues would be solved. Again #1610 links to it.

**Comment by solarsootysmudge** [comment]
Also worth reading the comment at the end of #1720 where a suggested merge did not not think about the implications of #1610.

**Comment by HebaruSan** [comment]
Wherever the best place is, the point was: it's not here. :) :(

**Comment by politas** [comment]
This has been implemented in #2202
