### ISSUE TITLE
Circular logic flaw

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-CKAN/CKAN#2257]
There may be just a wee bit of circular logic going on somewhere in CKAN 1.24.0-PRE

![screenshot from 2018-01-17 09-20-13](https://user-images.githubusercontent.com/4062616/35056901-153aa914-fb68-11e7-80d1-0a814fef51d4.png)

**Comment by HebaruSan** [comment]
The circularity is in the data; those two mods mutually conflict with one another. We could arbitrarily cut it off at some point, but then it wouldn't be giving an "accurate" representation of the relationships at that level (since a conflict would be hidden for the final node). Is there any harm in letting the user amuse themselves by endlessly expanding nodes? :smile:

**Comment by 7ranceaddic7** [comment]
I was tempted to see how far I could take this "user amusement functionality". :smile:  Fortunately, it's early in the day and I can curtail my CDO (for the rest of you, that's OCD ... with the letters in the proper order).

**Comment by HebaruSan** [comment]
Anyway, thanks for reporting this. Probably worth fixing.

**Comment by HebaruSan** [comment]
This issue will auto-close if/when that fix is merged, but until then, it's best to leave it open in case some kind of problem prevents that from happening.
