### ISSUE TITLE
First time run crash

### ISSUE THREAD

**Issue by technogeek157** [KSP-CKAN/CKAN#2280]
## Background
**CKAN Version:**
1.22.6

**KSP Version:**
1.3

**Operating System:**
Win 7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

## Problem

**What steps did you take in CKAN?**
Launched CKAN.exe from releases(not pre-release)

**What did you expect to happen?**
CKAN to start up normaly

**What happened instead?**
Error code(see below)

I tried searching, and previous issues had to delete the registry. It doesn't exist in the folder it should. I also tried deleting the folder, to no avail.

EDIT: I would really like this working, so I can play realism overhaul without installing individual mods :)

**CKAN error codes (if applicable):**

```
Unhandled exception:
System.TypeInitializationException: The type initializer for 'Newtonsoft.Json.JsonWriter' threw an exception. ---> System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.CompilerServices.RuntimeHelpers.InitializeArray(Array array, RuntimeFieldHandle fldHandle)
   at Newtonsoft.Json.JsonWriter..cctor()
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.JsonWriter..ctor()
   at Newtonsoft.Json.JsonTextWriter..ctor(TextWriter textWriter)
   at CKAN.RegistryManager.Serialize()
   at CKAN.RegistryManager.Save(Boolean enforce_consistency, Boolean recommmends, Boolean with_versions)
   at CKAN.RegistryManager.LoadOrCreate()
   at CKAN.RegistryManager..ctor(String path, KSP ksp)
   at CKAN.RegistryManager.Instance(KSP ksp)
   at CKAN.Main..ctor(String[] cmdlineArgs, GUIUser user, Boolean showConsole)
   at CKAN.CmdLine.MainClass.Gui(GuiOptions options, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args) 
```

**Comment by HebaruSan** [comment]
Please answer the questions in the template instead of deleting them. We need that info to help or investigate.

**Comment by technogeek157** [comment]
Sorry, but what template?

**Comment by technogeek157** [comment]
Oh, duh, sorry.

**Comment by technogeek157** [comment]
This work?

**Comment by HebaruSan** [comment]
Yes, that gives us a starting point. Thank you.

**Comment by HebaruSan** [comment]
Amusingly, a google search for this error turns up #1976 and not much else. Unfortunately that issue was closed by its author on the same day it was opened without further discussion, so it doesn't yield any clues.

This exception happens in the static constructor of `Newtonsoft.Json.JsonWriter`, which just calls another static function to build some arrays:

https://github.com/JamesNK/Newtonsoft.Json/blob/39f2db6f2da4b395e6da8b83a2b72ea6e174dffc/Src/Newtonsoft.Json/JsonWriter.cs#L114-L117

https://github.com/JamesNK/Newtonsoft.Json/blob/39f2db6f2da4b395e6da8b83a2b72ea6e174dffc/Src/Newtonsoft.Json/JsonWriter.cs#L79-L112

This code isn't doing anything particularly complex, and if there's really a problem with it, it ought to happen for all users. This makes me suspect a problem with the .NET version. Do you have .NET 4.5 installed?

https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Windows

**Comment by technogeek157** [comment]
Fixed it! I was dumb and didn't have the .NET framework installed :). I'm sorry, I just got a new pc and forgot I hadn't installed it yet!
