### ISSUE TITLE
NullReferenceException occurs when i click settings>CKAN setting

### ISSUE THREAD

**Issue by junwooPark** [KSP-CKAN/CKAN#2300]
Background
----------

**CKAN Version:**  1.24.0 (i downloaded bruce 20 min before)

**KSP Version:** 1.3.1

**Operating System:**  windows 10 (64bit)

Problem
-------

**What steps did you take in CKAN?**
execute ckan.exe after i deleted CKAN folder and reset all
and i click immediately settings > CKAN settings 

**Screenshots:**

![image](https://user-images.githubusercontent.com/10040797/36603939-ab314810-18ff-11e8-891b-70a13dc1052f.png)

and if i click continue...
![image](https://user-images.githubusercontent.com/10040797/36603964-be26ea92-18ff-11e8-8529-39101e14dabd.png)

and i clicked check for updates

![image](https://user-images.githubusercontent.com/10040797/36603996-d1b8708a-18ff-11e8-9c06-295fa3c18fcb.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Thanks for the report, I think I know the cause...

**Comment by weltall2** [comment]
Glad I refreshed before I posted this too. Thanks so much for the quick solution HebaruSan. No more problems after running that command once =) Have a great week!

**Comment by linuxgurugamer** [comment]
Worked for m e as well

**Comment by VasVadum** [comment]
Another workaround till this is fixed officially (Cause I downloaded ckan again today and have this same error), if you don't know command line just click "Continue" on the error message, the settings window will show 0.0.0 as a version number, but you can add a new auth token there by clicking new and type in some stuff.  Restart the client and all is good.

This is for those who don't know command line or don't want to run command line.

But as of today, after this issue was closed 4 days ago, the bug is still there.

**Comment by HebaruSan** [comment]
> But as of today, after this issue was closed 4 days ago, the bug is still there.

The issue status reflects whether the developers still need to work on it. We already have a fix for this ready for the next release.

**Comment by VasVadum** [comment]
Ah, alright.  :P  Well, there's the other workaround for people who don't know command line and such.

**Comment by gjnelson7030** [comment]
Recently encountered this problem with CKAN v1.24.0, and this fixed it crashing when trying to access "settings". Thanks for posting this quick fix!
