### ISSUE TITLE
Feature Request: Set "Compatible KSP Versions" override per-mod

### ISSUE THREAD

**Issue by Rohaq** [KSP-CKAN/CKAN#2398]
It's cool that we can add "Compatible KSP versions" in the Settings menu, since many mods will continue to work between minor KSP patches, but in cases where individual mods don't work with new versions, it would be good to be able to set the "Compatible KSP versions" on a per-mod basis.

Ideally, any mod without this set should follow the global "Compatible KSP versions" list as set in the CKAN settings menu, but if set on the individual mod, this should act as an override.

For example:

1. I'm on KSP 1.4.2
2. In CKAN, in the global "Compatible KSP versions", I've ticked "1.4", and "1.4.1", since most mods will continue working between minor patch versions.
3. I discover an individual mod with a max KSP version of "1.4" doesn't work.
4. For that individual mod, I should be able to set the "Compatible KSP versions" to untick "1.4", and perhaps "1.4.1" to prevent it from being listed as compatible. All other mods without overrides follow the global list.
5. Some kind of visual cue should probably be added to the mod list to highlight mods that have individual overrides set - e.g. different coloured text, or background colour. - so that users can easily find mods they've overridden later.

Alternatively, I might find a mod marked with a maximum version of "1.3.1" that still works fine in 1.4.2, and the ability to allow that older version of the mod to be marked as compatible would also be good.

It would also be useful if the override UI had an "Install When Compatible" tickbox - Essentially removing the mod from KSP until a later update marks it as compatible with the detected version from the KSP install, at which point it gets ticked for install when CKAN loads/refreshes - but that's probably leaning into a second feature request.

**Comment by Ruedii** [comment]
The best way to implement this is a series of two alterations:|
 
 - The show incompatible mods buttons should prompt you for the earliest version to filter for.

 - Instead of hiding the checkbox, when you check the checkbox you should be prompted if you want to override KSP version compatibility.

 - A flag needs to be set when doing this that allows the mod to be updated without checking version compatibility.

**Comment by politas** [comment]
Ok, a few questions that may help explain why we aren't jumping on this idea:

- Do we store these exceptions in a new per-mod/per-ksp install structure? Or per-version/per-mod/per-install?
- When the mod version upgrades, do we prompt for review of the settings for each mod?
- If the mod is uninstalled, do we throw away the mod's specific KSP version? If not, how long do we maintain the data?

It's worth pointing out that CKAN doesn't uninstall mods simply because they are not matching the current KSP version, so you can change the KSP compatibility settings, install a specific mod, then change back.

**Comment by politas** [comment]
Over six months without a response from the issue creator. Closing vague feature request.

**Comment by cumber** [comment]
I came here to request something similar.

The problem I faced is that, as a very new user to CKAN, most of the mods I wanted to install were not marked as compatible with the latest KSP version, but it turned out that they actually are. But in order to install them I need to tell CKAN that *all* mods going back to KSP 1.4 are actually compatible with 1.7, which is far more general than the information I actually want to tell CKAN. I just want to take a risk on certain particular mods (based on e.g. forum reports or friends' recommendations).

It seems like a very simple and small feature for me to be able to override the compatibility check to install one particular mod, instead of for all mods.

In response to @politas' questions of last year, I think taking the existing list of compatible versions and adding an ability to set that per-mod is over-complicated for what this actually needs. It's pretty much redundant to set which KSP versions an individual mod is compatible with; the "true" answer to that is invariably "I don't know", but I just want to try this mod, so I would always set my current KSP version as being compatible with the mod I'm trying to install. Asking the user for a list of KSP versions they want to force the mod to be compatible with is an over-complicated way to meet the user's goal; just a simple "Force install" right click option would do (or something equivalent, like being able to tick the install checkbox and click through a warning prompt).

It sounds like there wouldn't actually be any need to save any information "blessing" that particular version, if CKAN doesn't attempt to uninstall mods that were installed in the past but would not now pass the compatibility check.

So specifically:

> Do we store these exceptions in a new per-mod/per-ksp install structure? Or per-version/per-mod/per-install?

I don't see any need to store anything more than the installed version, as is already done.

> When the mod version upgrades, do we prompt for review of the settings for each mod?

What currently happens when you have an incompatible mod installed, and then a new version of the mod is released? I don't see any need for the behaviour here to be any different than if we follow the work-around @politas suggested of changing the compatibility settings, installing a specific mod, then changing the compatibility settings back.

> If the mod is uninstalled, do we throw away the mod's specific KSP version? If not, how long do we maintain the data?

No need to store anything as far as I can see; if I uninstall an incompatible mod and later want to install it again, I'll just use the override again.

**Comment by DasSkelett** [comment]
Many thanks for your well written text, appreciate that.

However, I have to kinda disappoint you, you can't convince us any more,
because [we already have this feature](https://github.com/KSP-CKAN/CKAN/pull/2821) by now. :)
It will be included in the next release.
