### ISSUE TITLE
Windows error after KSP reinstall: Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by Topperfalkon** [KSP-CKAN/CKAN#2443]
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.4.3.2152

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
KSP has been recently reinstalled

Problem
-------

**What steps did you take in CKAN?**
(After reinstalling KSP)

1. Open CKAN (running from Download folder, not KSP folder)
2. CKAN notifies me that the KSP version has been updated, and raises the Compatible Ksp Versions window
3. Click Save

**What did you expect to happen?**
I expect my preferences to be saved

**What happened instead?**
An error is thrown: Object reference not set to an instance of an object

**Workaround**
Moving ckan.exe to KSP's root folder seems to have resolved the issue

**CKAN error codes (if applicable):** 
N/A, but see Windows exception message below

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.KSP.SaveCompatibleVersions()
   at CKAN.CompatibleKspVersionsDialog.SaveButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by HebaruSan** [comment]
Possibly caused by `Version()` being null here:

https://github.com/KSP-CKAN/CKAN/blob/5c5cb60976eabba3f15c34d02b140e31fda5ad13/Core/KSP.cs#L123-L134

That can happen if we can't find `buildID.txt` or `readme.txt` in the game dir. 

... and indeed, I can reproduce this if I:

1. Have exactly one game instance
2. Set at least one additional compatible version in the compatible versions dialog
3. Remove `buildID.txt` and `readme.txt`, _without_ removing the KSP folder or the CKAN folder
4. Launch the GUI

**Comment by HebaruSan** [comment]
@Topperfalkon, thanks for the bug report. What does your reinstall process look like? It looks like you deleted some of the game files but not the main game folder, and then installed the new version somewhere else, since the version info is missing but the CKAN configuration data is still there. We can work on making this code more robust, but you should be able to work around the problem in the meantime by deleting the (old!) main game folder.

**Comment by Topperfalkon** [comment]
I uninstalled then reinstalled through Steam's UI. I've noticed that Steam doesn't always properly delete folders when you tell it to uninstall games, and it doesn't always detect certain files are missing either.

**Comment by Topperfalkon** [comment]
I tried deleting buildID.txt (well, renaming) and validating files, but seems to have brought it back.

**Comment by HebaruSan** [comment]
So the file was there before? That should make the reported error impossible.

After it brought it back, does the error still happen?

**Comment by Topperfalkon** [comment]
It's still happening if I open the copy of CKAN that isn't in the install folder, but not the one that's in the KSP root folder. I'm not sure why there's a difference, given that they were literally the same executable

**Comment by HebaruSan** [comment]
Hmm, that suggests there are two different game folders involved here; presumably the one whose root folder you're looking at is the one in Steam, and CKAN thinks it knows about some other one.

Can you post a screenshot of the Select KSP Install window (via the File menu)?

![image](https://user-images.githubusercontent.com/1559108/39970630-48a12e1e-56de-11e8-9f8b-f4d9534d82ae.png)

**Comment by Topperfalkon** [comment]
![image](https://user-images.githubusercontent.com/1361479/39971025-615eaf4a-56ec-11e8-8ad5-c9c8a285babb.png)

This is from the working ckan.exe in the KSP folder, the other executable is being blocked from proceeding by this error, so I can't tell if it knows about a different install

**Comment by HebaruSan** [comment]
Hmm, that "NONE" shouldn't look like that; it should have the actual version of the game, like this:

![image](https://user-images.githubusercontent.com/1559108/39971626-f120e624-56ed-11e8-880c-f81504751123.png)

(My previous screenshot said NONE because I had deleted the buildID.txt and readme.txt files.)

All signs still point to the "working" version being in a folder other than your main Steam folder. Can you show a screenshot of that folder?

**Comment by Topperfalkon** [comment]
Cool, that makes a lot more sense now. 

Would be nice to have a bit more hardening for handling edge cases like this. Perhaps forcing the Select KSP Install window to display if it can't find the buildID.txt?

Also teaches me to pay more attention when I'm reinstalling things on Steam that they're going to the right place!

**Comment by HebaruSan** [comment]
> Would be nice to have a bit more hardening for handling edge cases like this. Perhaps forcing the Select KSP Install window to display if it can't find the buildID.txt?

Yeah, I agree. Added that to #2444.
