### ISSUE TITLE
CKAN.NotKSPDirKraken: Could not find KSP version in buildID.txt or readme.txt

### ISSUE THREAD

**Issue by Drakkith** [KSP-CKAN/CKAN#2504]
Background
----------

**CKAN Version:** 
1.25.2

**KSP Version:** 
1.3.1

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes. I've installed and deleted several mods manually.

Problem
-------
CKAN encounters an unhandled exception when opening and will not open. I've already deleted every all CKAN references in my registry and I can't find anything related to CKAN when I use a registry cleaner.

**What steps did you take in CKAN?**
 I "forgot" an install of KSP, which may have been the trigger for the issue.

**CKAN error codes (if applicable):** 

Unhandled exception:
CKAN.NotKSPDirKraken: Could not find KSP version in buildID.txt or readme.txt
   at CKAN.KSP.CkanDir()
   at CKAN.Main..ctor(String[] cmdlineArgs, KSPManager mgr, GUIUser user, Boolean showConsole)
   at CKAN.GUI.Main_(String[] args, KSPManager manager, Boolean showConsole)
   at CKAN.CmdLine.MainClass.Main(String[] args)

**Comment by Drakkith** [comment]
What's a 'default instance'? I just have the .exe file that you download. Everything else that it installs has been deleted as far as I can tell.

**Comment by HebaruSan** [comment]
Instance of the game, the thing you said you "forgot". Does CKAN know of a copy of KSP on your system?

**Comment by HebaruSan** [comment]
OK, is buildID.txt or readme.txt present in your Steam copy of KSP?

**Comment by Drakkith** [comment]
I'll have to check my desktop when I get back home (currently out of town until tomorrow), but I'm nearly certain I finally just deleted KSP entirely from both locations (steam and non-steam). Not just an uninstall, but a complete deletion of the folder once the uninstall was complete, so there shouldn't be any ckan files left.

However, I was having the same problem on both my desktop and my laptop and it looks like grabbing a registry cleaner fixed my laptop's problem with ckan. But having to mess with your registry to fix the problem is obviously undesirable.

**Comment by twotone48166** [comment]
Not sure if should have started a new post or not but I'm having the same issue. New install of KSP from steam. No past installs of either KSP or ckan from what I could find. Ran the game then tried to run the ckan.exe file I had downloaded. it gives me the "Unhandled Exception" error...heres a screenshot of it
![error](https://user-images.githubusercontent.com/42505829/44305016-25f4d380-a33b-11e8-874d-79a0901804d2.png)

**Comment by HebaruSan** [comment]
Hi @twotone48166, that's a different unrelated issue, see #2483. I'm going to go ahead and prune your comment to prevent confusion on this issue.

**Comment by Drakkith** [comment]
Uh oh, looks like things weren't fixed on my laptop after all. Just had this exception occur while CKAN was updating the registry after installing some mods:

_System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Drakkith\AppData\Local\Temp\CdFileMgr\c87286f1-c6be-41.json'._

I can't even find the AppData folder that's supposed to be there unless it's hidden or something.

**Comment by HebaruSan** [comment]
That's #2342, being fixed in #2492. Your OS is deleting that CdFileMgr folder while we're still trying to use it.

Back to the original issue, of the several places that catch `NotKSPDirKraken`, the only ones in GUI are in the choose KSP install window. So if your default game folder becomes invalid (i.e., you delete it and/or its files), that exception will be thrown and not caught. I think we can avoid that by checking `CurrentInstance.Valid` here...

https://github.com/KSP-CKAN/CKAN/blob/37c8477acccd8cebe204da4905cd67760e6bdb31/GUI/Main.cs#L187-L190

**Comment by Drakkith** [comment]
Roger. Glad to know that #2342 is being fixed.
In the meantime, is there anything else you need from me about the original issue?

**Comment by HebaruSan** [comment]
Hmm, digging a little deeper, we *are* already checking `CurrentInstance.Valid`, in `KSPManager.GetPreferredInstance`. So an invalid instance shouldn't be getting returned, and it should already be prompting you to select a valid game folder.

Ahh, I think it's because your Steam folder exists and is invalid. If you have no known game folders, it'll automatically check the Steam folder first, and that logic is missing some of the newer validation checks (it looks for GameData but not the versioning info), so an invalid Steam folder can slip through. I think I see a good spot to fix that.
