### ISSUE TITLE
Allowing older versions be compatible has mod version for older KSP version override the current

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#2581]
Very specifically, SXTContinued.

This was tested on a 1.5.1 install.

Did a Refresh, typed "sxt" in mod name, and the latest version shows up, 0.3.24.1
Added 1.4 to compatible KSP versions, and it then shows (oddly): 03.23.7 (sic)

Proper behaviour would have the latest one available shown

**Comment by HebaruSan** [comment]
Looks like that's because that version is missing a period:

![image](https://user-images.githubusercontent.com/1559108/48667008-83c4c300-eac4-11e8-835f-8131530abbab.png)

So when the versions get compared, the first part of 03.23.7 is 3, and the first part of 0.3.24.1 is 0, and 3 > 0.

The fix here would be to the mod and metadata, not CKAN.

**Comment by linuxgurugamer** [comment]
Crap.  I'l just do an epoch, or can you fix the meta data?  This is a problem on Spacedock, most likely I made a typo putting in the version.  Cause there is no way that error can be made in the .version file

**Comment by HebaruSan** [comment]
Yes, we can fix the metadata. Do you want to fix it on SpaceDock first, or is it OK as-is?

**Comment by linuxgurugamer** [comment]
I can't do anything on spacedock other than deleting it and adding it back, which causes other problems.  It can be left as is, as long as the meta data is correct.
I assume that the metadata specifies the specific file to download?
