### ISSUE TITLE
Feature Request: Ability to install any specific version of a mod

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/CKAN#2714]
Background
----------

**CKAN Version:** 1.26.0

**KSP Version:** 1.4.5

**Operating System:** W7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** Yes

Problem
-------

**What steps did you take in CKAN?** Clicked on a mod version which is listed as incompatible with my current install, but in fact does work.

**What did you expect to happen?** A dialogue window to offer me the option to install the mod version.

**What happened instead?** Absolutely nothing.

**Comment by DasSkelett** [comment]
If you mark the KSP version the mod is released for as compatible, it should work.
If not, it doesn't, and it shouldn't.
But I agree that there should be some message showing up.

**Comment by Blu3wolf** [comment]
It's a feature in the CLI. It would make my life much easier if it were a feature of the GUI also.

It's about reducing the number of clicks required to achieve a simple task that CKAN is designed for.

In the case of marking a newer version as blanket compatible, CKAN is also going to want to update ALL mods, not just the ones I know work.

**Comment by Blu3wolf** [comment]
Also, should this have the GUI tag? Its not an issue in the CLI.

**Comment by DasSkelett** [comment]
That's a good point.
Because there's a bit of philosophy involved, I would like to hear another opinion on this (pinging @politas).

**Comment by Blu3wolf** [comment]
concrete user story here: I currently have Mk2 Stockalike Expansion installed, version 1.8.2. 

1.8.3 fixes a couple of compatibility patches, but its also marked as only compatible with KSP 1.5 onwards. I cant install the version I want, using the GUI - only with the CLI.

**Comment by HebaruSan** [comment]
> Its not an issue in the CLI.

> I cant install the version I want, using the GUI - only with the CLI.

That's approximately half true:

```
$ ckan compat list
Version     Actual
----------  ------
1.4.5.2256  True
1.4         False

$ ckan install Mk2Expansion=2:1.8.3
Module Mk2Expansion 2:1.8.3 required but it is not listed in the index, or not available for your version of KSP.
If you're lucky, you can do a `ckan update` and try again.
Try `ckan install --no-recommends` to skip installation of recommended modules.
Or `ckan install --allow-incompatible` to ignore module compatibility.
```

The cmdline _does_ check for compatibility when attempting to install a specific version, just like GUI, but there's a flag `--allow-incompatible` that can bypass that check (as of #2228). So the question is whether/how to add a bypass mechanism for GUI.

**Comment by frankhaugen** [comment]
This should definetively be a feature. I see no reason why I shouldn't be able to specify the versions

**Comment by Blu3wolf** [comment]
oh, reasons exist. I dont consider them good reasons, but there are pros and cons. 

They lean in the direction of policy items for CKAN though, so hashing them out here is probably not really needed.

**Comment by HebaruSan** [comment]
Listing use cases would be much more helpful than snide griping, guys.

**Comment by Blu3wolf** [comment]
Believe I've done just that, 3 weeks ago in this very issue.

**Comment by HebaruSan** [comment]
I'm sorry you feel that way, but don't let the point being made escape you:  Enhancements are worked on when a developer feels like it, which in turn depends on a combination of perceived importance, risk, and difficulty; not whether someone "sees no reason why not" or thinks concerns raised by others are "not good reasons."

The angle I was pointing to earlier is perceived importance. If there's a lot of useful stuff that this would allow, that would make it a more attractive project to work on. So far we have one scenario.

**Comment by Blu3wolf** [comment]
Trust me when I say this is a point which I understand fully

**Comment by politas** [comment]
So, if I understand this correctly, we have provided multiple methods for people to install mods marked as incompatible, but it's a little inconvenient for a single mod, and you can imagine an easier way to achieve your goal if the interface worked differently. Is that a fair assessment of the situation?

**Comment by tofof** [comment]
The core expectation raised - that it should be possible to click on a mod from the 'incompatible' filter in the gui and, on a per-mod basis, make an exception and install the mod anyway - is a very reasonable one.

There are many mods I have personally installed that are not flagged compatible with 1.7.2.  Some are quite prominent (Alternate Resource Panel) yet in a limbo between maintenance and adoption. Some are so simple as to be robust to new versions with no updates (Crowd Sourced Science, Chatterer Extended). Others have been adopted and require no changes but are presumably without the version number bump because of time (FlagRotate and any of two dozen other LinuxGuruGamer-adopted mods). 

The current system requires me to flag as far back as KSP 1.1 to get the gui to install the mods I want. **This has the effect of making the 'compatible' filter worthless.**  It would be far superior to be able to leave only, say, 1.6 and 1.7 checked but allow me to install exceptions manually, through the gui.  I can't even temporarily enable compatibility of a specific version, install the mod in question, then disable it. 

Similarly, mods included in a .ckan list that are outside of the versions flagged compatible by the user are **silently** dropped during installation.  While this is its own defect, it is related to this same UI flow -- CKAN should prompt and allow installation instead of silently dropping.

**Comment by HebaruSan** [comment]
@tofof, your wall of text reads like this issue has been closed as "won't fix".
It hasn't. It's still open, could still be worked on.
