### ISSUE TITLE
Newly Compatible shows all mods, not just those newly compatible

### ISSUE THREAD

**Issue by oldlost** [KSP-CKAN/CKAN#2716]
Background
----------

**CKAN Version:**
1.26.0

**KSP Version:**
1.6.1

**Operating System:**
Windows 10 Pro 64 bit

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
Filter "Newly Compatible" shows same number of mods as "All".

**What steps did you take in CKAN?**

1. Started ckan.exe
2. Let it refresh repository of mods
3. Pressed Filter button

**What did you expect to happen?**
What used to happen in previous version: Newly Compatible only showing those mods that have recently (since last refresh) become compatible with the current version of KSP.

**What happened instead?**
Filter shows all mods.

**Screenshots:**

![image](https://i.imgur.com/lqVRSiZ.png)

**CKAN error codes (if applicable):**
None

**Comment by thorman123** [comment]
I am having this same issue. here is proof
![Annotation 2019-04-03 154138](https://user-images.githubusercontent.com/21047353/55511766-fde68600-5626-11e9-99d8-f1c20a916441.jpg)

**Comment by DasSkelett** [comment]
Can confirm this happens if you have auto-update on launch activated. Hitting refresh again (with already up-to-date repository) still says the same number.
If you deactivate auto-update, the bug doesn't occur.

**Comment by HebaruSan** [comment]
Probably caused by #2694; before that change, GUI loaded all rows of the mod grid fully before auto-updating, and then did it again after, and this filter was based on the difference between those two loads. Now we only load the rows once for efficiency, before that load there are **no** rows, so when we do add rows they all appear to be new.

https://github.com/KSP-CKAN/CKAN/blob/3bc537637e8f4452c9787699045d61b4d869061f/GUI/MainModList.cs#L212-L241

Should be possible to make this use the registry instead of grid rows.
