### ISSUE TITLE
[Feature] Automatically switch to the modification list after inserting text into the filter

### ISSUE THREAD

**Issue by Artemonim** [KSP-CKAN/CKAN#2826]
Problem
-----------
Modifications can be selected with the mouse, or by using the arrow keys and the space bar. However, when interacting with filters, it is impossible (as far as I know) to select list items using the keyboard — the active window is the filter window.

Suggestion
-----------
When a user inserts text into one of the list filters, he or she is likely to see the modification he or she needs. I suggest, when inserting text in any of the filters, switch the user to the list of modifications (make it active for the keyboard) — you can immediately mark the desired modification with a space, or, if you are unlucky, get to it with the arrow keys (or using the mouse).

Why?
-----------
I believe this will increase the comfort of using CKAN for people who are used to using hotkeys to the maximum.

**Comment by DasSkelett** [comment]
> I suggest, when inserting text in any of the filters

So you mean after pressing enter, right?

**Comment by HebaruSan** [comment]
There is definitely some keyboard accessibility missing here. I can tab off of the name field to the mod list, but I have to press tab **12 times** to get there. However as @DasSkelett noted, "when inserting text in any of the filters, switch the user to the list of modifications" won't work either, because it will interrupt someone typing a longer string.

In ConsoleUI pressing tab works because there are fewer controls on the screen, and there's an extra down arrow key binding for this.

I like the idea of pressing enter or down arrow, and maybe we can clean up the tab order so it goes filters &rArr; mod list &rArr; mod info.

**Comment by HebaruSan** [comment]
Since 2 of the tab keypresses are to move through the author and description filters, maybe this should be combined with #2736, since having one search box would bring the tabs required from 3 down to 1.

**Comment by DasSkelett** [comment]
> Since 2 of the tab keypresses are to move through the author and description filters, maybe this should be combined with #2736, since having one search box would bring the tabs required from 3 down to 1.

I was also considering combining this with #2736, so that's a definitive yes from my side. And cleaning up the tab order sounds like a good idea too.

**Comment by Artemonim** [comment]
Usually, I paste the text from the forum or modification site through the clipboard into the filter. Usually, only one or several similar positions remain in the list. Usually, I need to press the space bar to enable/disable the modification. Just because I just pasted text with Ctrl+V and my thumb is next to the space bar button.

I do not have user statistics of CKAN usage and I judge only by myself. Also, I completely forgot the word "paste" when describing this feature and wrote "inserting". Shame on me.

**Comment by Artemonim** [comment]
Just decided to check — it turns out that from the filters to the list of modifications you can go with Ctrl+Tab in one action :D
