### ISSUE TITLE
Make `copyright` file in .deb package machine-readable

### ISSUE THREAD

**Issue by bfrobin446** [KSP-CKAN/CKAN#2851]
Problem
-------
On Kubuntu 19.04, there's a GUI for opening .deb packages that claims that the license is "proprietary".

![screenshot of .deb app](https://i.imgur.com/xRIJXvq.png)

It would be better if apps that read .deb metadata would display the correct license for the product.

Suggestions
-----------
What CKAN can do is update the `copyright` file to use the [recommended format](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/). I'll try to get a pull request in this weekend.

**Comment by bfrobin446** [comment]
The app that I was looking at, `gnome-software`, apparently doesn't parse the Debian `copyright` file anyway. There ought to be something we can put in the .deb that GNOME will parse, but I couldn't find anything definite in the amount of time that I was willing to put into it.

**Comment by HebaruSan** [comment]
> `gnome-software`

What's odd is that if it wasn't able to find a license it all, it should be saying Unknown instead of Proprietary. So it must be finding a license for it somehow, but not the correct one (MIT).

https://gitlab.gnome.org/GNOME/gnome-software/blob/master/src/gs-details-page.c#L1108-1122

`gs_app_get_license` relies on a `gs_app_get_instance_private ` function that isn't defined anywhere that I can find (a search finds only callers):

https://gitlab.gnome.org/GNOME/gnome-software/blob/master/lib/gs-app.c#L2236-2242

**Comment by HebaruSan** [comment]
I think this is where it runs `dpkg-deb` to extract info about the .deb:

https://gitlab.gnome.org/GNOME/gnome-software/blob/master/plugins/dpkg/gs-plugin-dpkg.c#L50-89

... and that code simply doesn't do anything with the license at all. Doesn't attempt to extract it from the package, doesn't set it, doesn't set a default, nothing. If that's the case, then nothing that CKAN does could change the License field shown above. I'd be curious if you can find examples of other .deb packages that don't say Proprietary.

That's not entirely the fault of `gnome-software`; according to the man page of `dpkg-deb` and `dpkg-query`, they don't seem to have a way to extract the license:

- http://man7.org/linux/man-pages/man1/dpkg-deb.1.html
- http://man7.org/linux/man-pages/man1/dpkg-query.1.html

```
                  Architecture
                  Bugs
                  Conffiles (internal)
                  Config-Version (internal)
                  Conflicts
                  Breaks
                  Depends
                  Description
                  Enhances
                  Essential
                  Filename (internal, front-end related)
                  Homepage
                  Installed-Size
                  MD5sum (internal, front-end related)
                  MSDOS-Filename (internal, front-end related)
                  Maintainer
                  Origin
                  Package
                  Pre-Depends
                  Priority
                  Provides
                  Recommends
                  Replaces
                  Revision (obsolete)
                  Section
                  Size (internal, front-end related)
                  Source
                  Status (internal)
                  Suggests
                  Tag (usually not in .deb but in repository Packages files)
                  Triggers-Awaited (internal)
                  Triggers-Pending (internal)
                  Version
```

I see no harm in supporting that new format for the `copyright` file, but fixing the original screenshot in this issue is probably not possible.
