### ISSUE TITLE
[Bug] Unhandled exception when selecting / adding astronomer's visual pack

### ISSUE THREAD

**Issue by NateCroix** [KSP-CKAN/CKAN#2852]
Background
----------
* Operating System: Windows 10 Pro 1803
* CKAN Version: 1.26.4
* KSP Version: 1.7.3.2594

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
CKAN gives an unhandled exception when clicking the checkbox to add astronomer's visual pack, or any of the texture files. This does not happen with other mods in the "compatible" list

**Steps to reproduce**
* Install `EnvironmentalVisualEnhancements-HR` (or any other module providing `EnvironmentalVisualEnhancements-Config` other than AVP)
* Go to... the compatible list in CKAN
* Filter by mod names containing "astrono"
* Click on... "astronomers visual pack"
* An exception is thrown while it's trying to alert you to the conflict

**CKAN error code (if applicable):**

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: rowIndex
   at System.Windows.Forms.DataGridView.InvalidateRow(Int32 rowIndex)
   at CKAN.Main.ConflictsUpdated(Dictionary`2 prevConflicts)
   at CKAN.Main.set_Conflicts(Dictionary`2 value)
   at CKAN.Main.<UpdateChangeSetAndConflicts>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.Main.<ModList_CellValueChanged>d__284.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

**Comment by HebaruSan** [comment]
Doesn't happen with the given steps to reproduce; probably depends on user's installed module list.

The given call stack points to one of these `InvalidateRow` calls:

https://github.com/KSP-CKAN/CKAN/blob/6bbcf0b213598d96ad324b066b8637c93efe210a/GUI/Main.cs#L95-L136

We're getting the row from `mainModList.full_list_of_mod_rows` and then passing its index to `ModList`; since these aren't the same then they might get out of sync.

**Comment by matthewjd24** [comment]
I have the same issue. It appears it only happens when you filter the mods for Astronomer's Visual Pack, if you just scroll down to it and select it there's no error.

**Comment by HebaruSan** [comment]
> it only happens when you filter the mods for Astronomer's Visual Pack

Still doesn't happen for me. I can filter and check the box without an error. Probably depends on user's installed module list

**Comment by HebaruSan** [comment]
@NateCroix or @matthewjd24 , do you have any of AVP's conflicting modules installed?

![image](https://user-images.githubusercontent.com/1559108/63656639-febeb680-c785-11e9-914c-ac51969d1029.png)

That's why it's calling `InvalidateRow`, there's a conflict that would prevent AVP from being installed.

If I install one of those, *and then* filter by "astrono", clicking the checkbox finally gives me the error!

![image](https://user-images.githubusercontent.com/1559108/63656667-7bea2b80-c786-11e9-9ddb-2114b88f35c9.png)

I'll make some updates to the OP...
