### ISSUE TITLE
Expand KSP-AVC support

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#286]
Right now we have very rudimentary support for AVC. It would be great if given a KSP-AVC URL we could use that for detecting new releases.

This would be a `$kref`, rather than a `$vref` field.

**Comment by pjf** [comment]
re-opening after repo merge

**Comment by HebaruSan** [comment]
ExtraPlanetary Launchpads is an informative case study of how this could be useful. @taniwha hosts the downloads at taniwha.org rather than the usual hosting services. Currently this means that when a new version is released, the mod's netkan has to be updated manually (see https://github.com/KSP-CKAN/NetKAN/pull/5978).

The downloads include a KSP-AVC file, which has a "URL" property pointing to the latest KSP-AVC file hosted on taniwha.org.

The [KSP-AVC spec](http://ksp.cybutek.net/kspavc/Documents/README.htm) includes a `"DOWNLOAD"` property.

> DOWNLOAD - Optional
> Web address where the latest version can be downloaded.
> This is only used from the remote version file.

If this property was populated in EPL's version file, and if CKAN was updated to support it, then that ought to be enough to get new versions into CKAN automatically:

1. The NetKAN-bot downloads the currently indexed version
2. The NetKAN-bot checks the included KSP-AVC file
3. The NetKAN-bot checks the `"URL"` property of the included KSP-AVC file
4. The NetKAN-bot downloads the remote KSP-AVC file
5. The NetKAN-bot checks the `"DOWNLOAD"` property of the remote KSP-AVC file
6. If it's different from the URL downloaded in step 1, then we have a new release; restart the process at step 1 using that URL
