### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by CKANNoob** [KSP-CKAN/CKAN#2900]
Background
----------
* Operating System: HP Spectre x360
* CKAN Version: v1.26.4
* KSP Version: 1.8.0.2686

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
None that im aware of.

Problem
-------
**Describe the bug**
I reinstalled both KSP and CKAN and since then, this issue has arrived; Tweakscale constantly displays a "Sanity-check failed message" on the title screen which results in the in-game menu scale slider to disappear and is replaced with a white box that can't fine tune the scale of parts, its also under lapping other buttons.
I've tried deleting the cache and reinstalling mods from both CKAN and KSP but the sanity checks still fail after trying.

Any help would be greatly appreciated :)  

**Steps to reproduce**
* load up KSP from desktop or CKAN Program
* See error in top right corner of the main menu

**Expected behavior**
to function as it did before i reinstalled KSP

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
The CKAN team does not investigate or fix in-game bugs. Normally I would advise checking with the author of the misbehaving mod, but in this case there's a good chance that you're running out of date mods since most mods with DLLs broke with KSP 1.8.0, so you should probably just wait patiently for an update of your mods.

... confirmed, TweakScale isn't updated for 1.8.0 yet:

![screenshot](https://i.imgur.com/kioFzwH.png)

**Comment by HebaruSan** [comment]
Side note, the latest release isn't indexed due to a problem described here:

- net-lisias-ksp/TweakScale#81

**Comment by CKANNoob** [comment]
thanks for the speedy reply anyway!
