### ISSUE TITLE
Is it possible to build a self-hosted mirror site for CKAN-meta?

### ISSUE THREAD

**Issue by Villivateur** [KSP-CKAN/CKAN#2909]
Players from some areas of the world suffers from low speed downloading KSP mods with CKAN. I wonder if I can build a mirror site for them.

It seems that I can sync the mods package from the metadata JSON files, store them to my mirror site, and replace the "download" value in each JSON file. Then I can change the metadata repositories in CKAN settings.

Is it possible?

**Comment by HebaruSan** [comment]
The metadata is distributed under the permissive CC0 license, so mirroring it and changing it would be allowed:
- https://github.com/KSP-CKAN/CKAN-meta/blob/master/LICENSE.md

But you would need to check individual mods' licenses to make sure you are allowed to redistribute them. Some of them do not allow that.

**Comment by Villivateur** [comment]
Thank you. I will do more research on it.

**Comment by techman83** [comment]
All open source mods are already archived to archive.org already and there is logic to use that as a source when necessary. But as @HebaruSan said, as long as you comply with the licensing requirements of the mods, you are free to do as you please.

Adding it as an official metadata mirror, no. The metadata no longer matches the official metadata. But as we already have strong cryptographic hashes in our metadata, we could allow for third party configurable mirrors for the binary downloads. It would take some work and we would have to be more strict in checking that downloads match our metadata. Ensuring the mirror is kept up to date without being unkind to the hosts, that would require some thought. Linux distros already do this, so that might be a place to get inspiration from.

**Comment by Villivateur** [comment]
I've done building a mirror site. And I will publish my scripts for mirroring mods to GitHub soon.

**Comment by HebaruSan** [comment]
Sounds like this was resolved. Please let us know if you have any further questions.
