### ISSUE TITLE
[Feature] Make mod installation not fail if an unowned identical craft file already exists

### ISSUE THREAD

**Issue by RemiWoler** [KSP-CKAN/CKAN#3029]
Problem
-------
**Is your feature request related to a problem? Please describe.**
CKAN provides the safety feature to never overwrite files it did not install itself. I believe this is a very good thing, and may have helped me in past years when I restored GameData from backups instead of using CKAN.

It is however possible that craft files, normally provided by a mod, are present before the mod is installed through CKAN. I *believe* this is a side-effect of Steam, which appears to keep the saved crafts in the cloud and "restores" them when you install KSP fresh through Steam. Extremely helpful for custom crafts, but not so helpful for mod-provided craft files, as the mod can now no longer be installed through CKAN without manual user intervention

Suggestions
-----------
**Describe the solution you'd like**
While the never-overwrite feature of CKAN should stay, I think it could be improved for specific cases like the .craft files. I think the ideal approach for this is:

1. Identify the situation where a mod-provided file already exists and is not "owned" by CKAN (this part already exists and works as expected/intended)
2. IF the file is a .craft file, handle it as a special case (this could apply to other cloud-saved files, if applicable)
3. Verify that the existing .craft file is an exact duplicate of the to-be-installed .craft file (a checksum like sha256 of both files should prove or disprove that the files are identical)
4. IF the files are identical, skip creating the mod-provided file, as an exact duplicate already exists.
5. IF the files are NOT identical, abort/roll-back as usual, to not overwrite any user-modified files.
6. "Own" the file, as if the file was mod-provided, so mods can be installed without external user intervention.

**Describe alternatives you've considered**
Keep the safety-net as-is, but in the case of craft files in the VAB/SPH directories, inform the user that this can be caused by cloud-syncing. Currently it instructs the user to remove the mod that placed the file, even if no such mod exists.

**Additional context**
The .craft files are provided by mods as "documentation" and/or as example, i.e. for reference. While some users may alter them and save them under the same name, I believe most users use them for reference only, if at all. The checksum would prevent users from losing data in the first case, while most users would benefit from an even smoother mod-installation process when cloud-syncing is also active. 

This improvement would eliminate issues like #2894 . In my case, it was the same mod (ID: Mk2Expansion, 2:1.8.7) and same files, though I immediately identified this as a mod-provided craft by it's name. Since this is a pretty fresh installation, I can't think of any other way that I got the .craft files (and nothing else from the mod) except for Steam's cloud-sync.

**Comment by HebaruSan** [comment]
Related to #2186 (effectively a special case of that issue).

I've been very hesitant to touch those core safeguards of the install process, but this sounds fairly useful to me. I'd suggest the following tweaks:

- Don't make it specific to craft files (too much low level domain knowledge integrated into what's otherwise a generic tool)
- If matching files are found, add a screen explaining what we found and letting the user choose whether to abort the install or adopt the files, similar to #2962
- If non-matching files are found (i.e. user made changes or a different version of the file was installed), show them on that screen with extra alert text

**Comment by RemiWoler** [comment]
I'm not aware of how generic CKAN is, I only use it for managing KSP mods (and no manual mods or other mod-manager). I intentionally made it specific for .craft files supplied by mods, as they effectively function as documentation instead of functionality. "Owning" an identical "readme.txt" is a lot less dangerous than, say, a .dll. 

Having some support/end-user-interaction experience, I think giving the option to do a *potentially* destructive action **will** cause users to do it anyway. If I had a $1 for every support case where even `--force --yes-i-really-mean-it --yes-i-really-really-mean-it` being used without fully understanding the impact, I could probably hire a developer to implement this improvement :). 

I thought this was a safe exception since it concerned documentation/examples only, but if *I* had to choose between the generic solution or keeping the current safety net as-is, I would keep it as-is. Alerts/warnings just don't work on humans, and deleting/renaming the .craft files is enough for CKAN to install the mod as usual.

Feel free to merge into the related issues or close this issue, if it's too domain-specific to have an exception for.

**Comment by HebaruSan** [comment]
> I'm not aware of how generic CKAN is

All I meant by that was that CKAN currently makes no assumptions or distinctions about the files it's installing based on file name or anything else. It extracts them from the ZIP into GameData and that's it. So adding a place where we change what we do based on file extension is something that should be considered carefully.

I expect that as soon as this was done, we would receive requests to implement it for many other file types. Why should I have to delete an identical README.txt manually but not craft files? What about LICENSE.md? What about a .version file? What about some .cfgs? At that point we have to question whether craft files are actually special, and I don't think they are. Hence dropping the file-type-specific aspect.

But I like this idea because it specifies a useful component required to solve the bigger problem. We've had requests going back ages to take over manually installed mods as CKAN-managed (linked previously), but I had been thinking of that in terms of a big utility that identifies every manually installed mod and does some kind of special processing on them. That's a big task, but you've pointed out a way to take a smaller bite out of it by treating overwrites of identical files specially, which fits cleanly into the existing installation flow, and which we can build into a more powerful tool later on.

**Comment by HebaruSan** [comment]
Horrendous proof of concept UI:

![image](https://user-images.githubusercontent.com/1559108/80651344-62972e80-8a3b-11ea-8b33-5e310e4e1ad3.png)

(We really need a left-aligned YesNoDialog.)

**Comment by HebaruSan** [comment]
Slightly better:

![image](https://user-images.githubusercontent.com/1559108/80651774-231d1200-8a3c-11ea-91a8-36704453d7e4.png)
