### ISSUE TITLE
CKAN cant detect my KSP Version

### ISSUE THREAD

**Issue by Marcus2709** [KSP-CKAN/CKAN#3040]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.27.2
* KSP Version: 1.2.2

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

No

Problem
-------
**Describe the bug**
I have 3 KSP Versions. One Version in 1.9.1 another is 1.3.1. The Problem is that if i start ckan for my RSS Save File (v. 1.2.2) it shows 1.9.1.

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

Please fix this so i can use CKAN.

**Screenshots (if applicable)**

![Screenshot_1](https://user-images.githubusercontent.com/64438094/80416585-a9b6df80-88d4-11ea-9692-d26304e39781.png)

![Screenshot_2](https://user-images.githubusercontent.com/64438094/80416628-bdfadc80-88d4-11ea-8187-26af2a4dff61.png)

![Screenshot_3](https://user-images.githubusercontent.com/64438094/80416661-c94e0800-88d4-11ea-91df-91210519f6bd.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
So CKAN starts with the 1.9.1 instance selected because it is detected as portable install, because the ckan.exe is located inside the 1.9.1 game directory.
For managing the RSS instance in CKAN, you have to add it via `File > Manage KSP instances > New KSP instance > Add instance to CKAN` (`Datei > KSP-Instanzen verwalten > Neue KSP-Instanz > Instanz hinzufügen`) and navigate to the RSS directory.

Afterwards you can always switch to it again via the instance management dialog.

Alternatively, you can place a symlink to ckan.exe inside the RSS instance's folder. When you launch ckan.exe via this link, it should automatically switch to the RSS instance thanks to https://github.com/KSP-CKAN/CKAN/pull/3005 .

I hope I understood your problem correctly, if not, please give a more detailed description of what you did (step by step), what you expected to happen, and what happened instead.

**Comment by Marcus2709** [comment]
Da ich wie gesagt mehrere Ksp Versionen habe, habe ich zwei von denen in einen anderen Ordner getan. Die RSS Version ist bei Steam. Außerdem ist die CKAN Datei auch bei der RSS Version. Jedoch habe ich in den anderen Versionen auch die CKAN Datei. Kann da vielleich daran liegen?

**Comment by DasSkelett** [comment]
> Jedoch habe ich in den anderen Versionen auch die CKAN Datei. Kann da vielleich daran liegen?

Mehrere CKAN-executables machen eigentlich nichts.

Sobald du eine ckan.exe in dem Ordner einer KSP-Instanz liegen hast und diese exe startest, dann wählt CKAN automatisch die Instanz aus, in der sich die exe befindet (wird dann als `potable` angezeigt).
D.h. wenn du die ckan.exe im RSS-Ordner doppelklickst, dann sollte auch automatisch die RSS-Instanz ausgewählt sein. (Genause gilt, wenn du auf die ckan.exe in der 1.9.1 Instanz klickst, ist automatisch die 1.9.1-Instanz ausgewählt)

Versteh ich dich richtig, dass CKAN aber _trotzdem_ immer mit der 1.9.1-Instanz startet, _auch wenn_ du die ckan.exe im (und vom) RSS-Ordner startest? Das wäre dann ein Bug.

Hast du denn alle ckan.exe schon auf 1.27.2 geupdated? Wenn die unterschiedliche Versionen haben, kann das auch die Ursache sein.

**Comment by Marcus2709** [comment]
Achso danke. Ich habe bisher nur die ckan Datei im RSS Order geupdatet. Funktioniert jetzt wieder. Vielen Dank.

**Comment by DasSkelett** [comment]
Ahhh!
Wie gesagt, du kannst auch nur eine einzige Datein benutzen (und die z.B. auf dem Desktop ablegen), indem du Instanzen via `Datei > KSP-Instanzen verwalten > ...` hinzufügst. Dann musst du nicht dran denken, alle upzudaten.

Gerne!

**Comment by DasSkelett** [comment]
(For the record in English, in case others encounter a similar problem)
Issue resolved, the problem were multiple ckan.exe files with different versions in different KSP directories, and the logic for portable instances having changed in v1.27.2.
Solved by updating each ckan.exe to the latest version.
