### ISSUE TITLE
[Bug] after update to dyson Ckan give a C++ runtime error "attempt to load c run library library incorrectly"

### ISSUE THREAD

**Issue by aggie88** [KSP-CKAN/CKAN#3115]
Background
----------
* Operating System: Win10
* CKAN Version: 1,28.0

* KSP Version: 1.10.0

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

Problem
-------
**Describe the bug**
Error message pop ups in screen ask you to click ok, when you do so ask you to select ksp version after you do so ckan starts

**Steps to reproduce**
* Go to... Ckan icon
* Click on...ckan icon
* See error

**Expected behavior**
* ckan start

**Screenshots (if applicable)** atttached
![Ckan error ](https://user-images.githubusercontent.com/20476306/87588511-cc75ba80-c6b1-11ea-8ffa-1d5f0cb30f1a.JPG)

**CKAN error code (if applicable):**none
```
Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at CurlSharp.NativeMethods.curl_global_init(Int32 flags)
   at CurlSharp.Curl.GlobalInit(CurlInitFlag flags)
   at CKAN.Curl.Init()
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

**Comment by HebaruSan** [comment]
Do you have this problem with the pre-release?

https://github.com/KSP-CKAN/CKAN/releases/download/v1.28.0-PRE1/ckan.exe

**Comment by aggie88** [comment]
I used ckan auto update function about 10 minutes ago


Rafael A. Acevedo
LTC(R), FA, AUS

________________________________

**Comment by HebaruSan** [comment]
@aggie88 please answer the question, **do you have this problem with the pre-release?**

https://github.com/KSP-CKAN/CKAN/releases/download/v1.28.0-PRE1/ckan.exe

**Comment by aggie88** [comment]
How do I know is the pre release?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aggie88** [comment]
[cid:image003.png@01D65ABF.C52AD3E0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aggie88** [comment]
[cid:image003.png@01D65ABF.D52DF2E0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by HebaruSan** [comment]
> How do I know is the pre release?

I linked to it twice. Once more:

https://github.com/KSP-CKAN/CKAN/releases/download/v1.28.0-PRE1/ckan.exe

**Comment by aggie88** [comment]
No i do not have the problem with the pre-release

Rafael A. Acevedo
LTC(R), FA, AUS

________________________________

**Comment by Dominiquini** [comment]
I'm having this problem too!

The error message:

```
Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at CurlSharp.NativeMethods.curl_global_init(Int32 flags)
   at CurlSharp.Curl.GlobalInit(CurlInitFlag flags)
   at CKAN.Curl.Init()
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

[ckan.exe.11500.dmp.zip](https://github.com/KSP-CKAN/CKAN/files/4928349/ckan.exe.11500.dmp.zip)

The previous version (DRAKE - v1.28.0-PRE1) works well!

Thanks.

**Comment by 7ranceaddic7** [comment]
I am not experiencing this problem with 1.28.0

![image](https://user-images.githubusercontent.com/4062616/87613535-6cd3db00-c6c2-11ea-8e6b-fb9c1db5dd3a.png)

Just performed an update on Persistent Thrust with no issues.
![image](https://user-images.githubusercontent.com/4062616/87613625-ab699580-c6c2-11ea-9a2d-d9950167f37c.png)

**Comment by blackhack** [comment]
> I'm having this problem too!
> 
> The error message (showed in Command Prompt):
> 
> ```
> Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
>    at CurlSharp.NativeMethods.curl_global_init(Int32 flags)
>    at CurlSharp.Curl.GlobalInit(CurlInitFlag flags)
>    at CKAN.Curl.Init()
>    at CKAN.CmdLine.MainClass.Main(String[] args)
> ```
> 
> [ckan.exe.11500.dmp.zip](https://github.com/KSP-CKAN/CKAN/files/4928349/ckan.exe.11500.dmp.zip)
> 
> The previous version (DRAKE - v1.28.0-PRE1) works well!
> 
> I'm using Windows 10 x64.
> 
> Thanks.

I'm having this exact same error. The pre-release works fine though.

**Comment by krisavi** [comment]
> I'm having this problem too!
> 
> The error message (showed in Command Prompt):
> 
> ```
> Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
>    at CurlSharp.NativeMethods.curl_global_init(Int32 flags)
>    at CurlSharp.Curl.GlobalInit(CurlInitFlag flags)
>    at CKAN.Curl.Init()
>    at CKAN.CmdLine.MainClass.Main(String[] args)
> ```
> 
> [ckan.exe.11500.dmp.zip](https://github.com/KSP-CKAN/CKAN/files/4928349/ckan.exe.11500.dmp.zip)
> 
> The previous version (DRAKE - v1.28.0-PRE1) works well!
> 
> I'm using Windows 10 x64.
> 
> Thanks.

Same issue here. It prompted for upgrade and after upgrading on launch it gives that error.

**Comment by DasSkelett** [comment]
> However after building manually it was working fine, maybe something went wrong during build or uploading to download location.

It's not (exclusively, at least) a build error. As you can read in @7ranceaddic7's comment, it does work fine on some, maybe even most systems. Including mine.

@HebaruSan found some information indicating that this is a issue caused by stray, duplicate `msvc*.ddl` DLLs in PATH:
* https://gis.stackexchange.com/a/96109
* https://kb.froglogic.com/squish/qt/troubleshoot/r6034-application-made-attempt-load-c-runtime-library-incorrectly/#cause-4---stray-msvc-runtime-dll-files
* https://support.esri.com/en/technical-article/000013127

Just the usual Windows DLL hell, so much about paid OSes and their "higher quality".

Likely not something CKAN can do anything about, except cach the exception, ignore it and make sure curl never gets called on broken systems (we only use it as fallback anyway).

However it's interesting that it works for you after you built it yourself. Did you change your environment in some way for this, like changing PATH, or installing Visual Studio, or other development tools/dependencies that might affect which DLL is loaded?

**Comment by Dominiquini** [comment]
I edit my shortcut to ckan.exe to clear the PATH variable before executing it and works now!

`
C:\Windows\System32\cmd.exe /c "SET PATH= && START /D ^"C:\Program Files (x86)\CKAN" ckan.exe"
`

Thanks

**Comment by krisavi** [comment]
I just installed Visual Studio 2017 Community Edition. Had to modify cake build just a bit to get it to build because I apparently have multiple MSbuild systems installed and it was installing with some version that had issues building. Adding VSWhere to the mix helped it to find latest MSBuild version and use it to build correctly.

Odd is that it was able to run without problems after I built it, while the downloaded version had still issues. Path for both of them should be the same. 

It might be due to the VSWhere and adding settings.ToolPath for the MSBuild parameters, but I doubt it has anything to do with it. While writing took another look at it and might even know where difference comes from. The ToolPath is directing to using x64 MSbuild. Not sure what is used for the downloaded version. If it is x86, then it might explain the path and dll-s loaded.

**Comment by HebaruSan** [comment]
Interesting, this setting is present in every project except Core, but only for Debug builds, not Release:

https://github.com/KSP-CKAN/CKAN/blob/ccc87fa9053008a055e3e4042c16e021a982c5a2/GUI/CKAN-GUI.csproj#L27

@krisavi, is that the setting you're changing?

**Comment by krisavi** [comment]
Nope, I have not changed that one. The MSBuild I am using is x64, the one that is not working for me and seems outdated is 32 bit.

**Comment by Dominiquini** [comment]
I tested again and found that the problem could be solved removing a file (libcurl.dll) from my PATH. But it is installed with Apache and I prefer to simply keep that change in the shortcut by clearing the PATH variable.

**Comment by krisavi** [comment]
Yeah, from my testing I found libcurl.dll to be in path as well. 
Found reason why my own built version worked and the differences there. 
Dev team is aware of the findings already and I am sure they will get to the solution of it. May it be exception handling, running as 64bit where possible, dropping curl or some other solution they come up with.

**Comment by kg200dead** [comment]
The path reset trick alone didn't help (PC Windows 10), but ditching an old (probably out of date) copy of Anaconda [lots of path additions and lots of msvc*.dll] and an outdated java (that's probably unrelated, but once you've started cleaning things...) made it work.
Without the paths heads up, I wouldn't have considered the programming bits and bats as a thing, so thanks, and hope this "further things to consider" helps people.

**Comment by antonxt** [comment]
> The path reset trick alone didn't help (PC Windows 10), but ditching an old (probably out of date) copy of Anaconda [lots of path additions and lots of msvc*.dll] and an outdated java (that's probably unrelated, but once you've started cleaning things...) made it work.
Same story. After I uninstalled Anaconda, CKAN works normally again

**Comment by ErikSwan** [comment]
I can confirm that uninstalling Anaconda fixed this issue for me.

**Comment by zilti** [comment]
I don't even know what Anaconda is and have nothing with this name on my PC, but after auto-updating, I get

```
Unbehandelte Ausnahme: System.BadImageFormatException: Es wurde versucht, eine Datei mit einem falschen Format zu laden.
 (Ausnahme von HRESULT: 0x8007000B)                                                                                        
    bei CurlSharp.NativeMethods.curl_global_init(Int32 flags)                                                               
    bei CurlSharp.Curl.GlobalInit(CurlInitFlag flags)                                                                      
    bei CKAN.Curl.Init()                                                                                                    
    bei CKAN.CmdLine.MainClass.Main(String[] args)
```

**Comment by LucasSeren** [comment]
> I can confirm that uninstalling Anaconda fixed this issue for me.

Same here, thank you!

**Comment by CodeShane** [comment]
Same BadImageFormatException with Curl.Init using CKAN v1.28.0 Dyson.
Removing Anaconda from system path worked for me.

**Comment by 14lokk1** [comment]
Is there a workaround without removing anaconda? I actually need to use Anaconda for other purposes on my PC.

**Comment by tsssp** [comment]
Same problem. Removing anaconda does not seem to be a good solution.

**Comment by krisavi** [comment]
It seems they need to ship new version soon with the code changes. Forcing users to remove anaconda and other tools they might use for development is not a good idea of course.

> Is there a workaround without removing anaconda? I actually need to use Anaconda for other purposes on my PC.

From what I tested, then building the app on your own seems to work and also the "prefer 64bit" options while building seemed to be quite ok as well. I am using on my machine the version I built myself, because had libcurl.dll in one of the folders in path. Removing or renaming the file or removing the path helped. 
As temporary workaround something like `C:\Windows\System32\cmd.exe /c "SET PATH= && START /D ^"C:\Program Files (x86)\CKAN" ckan.exe"` seemed to have worked for some people.
