### ISSUE TITLE
[Feature] Better handling of installation failures

### ISSUE THREAD

**Issue by CritHappens7410** [KSP-CKAN/CKAN#3145]
## Problem

Ex. I'm always frustrated when... i get 99% of the way through installing mods which can sometimes take 30-60 minutes and then it has an error and undoes everything it had previously done.

## Suggestions

- allow the mods it completed installing to stay so i don't have to spend hours installing to then find a conflict or an error remove said mod from the list and try again over and over and over
- maybe make a hotkey to select multiple mods like holding shift does in most operating systems when selecting files
- make the check all check box do something so i can manually deselct the couple mods i don't want rather than having to click 175 check boxes one at a time

**Comment by DasSkelett** [comment]
Well that text could've used some punctuation...

The reason we remove all mods again if the installation of a single one fails is to not leave GameData in an unstable state, where some mods are installed but their dependencies aren't for example.

The easiest way to avoid waiting hours just to discover one mod can't be installed is just installing them in smaller groups.

> or at least make the check all check box do something so i can manually deselct the couple mods i don't want rather than having to click 175 check boxes one at a time.

Which one do you mean? The one of the recommendations tab? That one does work.

The one on the mod list only works for deselecting, but we could think about enabling it for selection in cases where there are less than x mods currently shown.
We shouldn't allow it always since selecting ~1000 mods at once would not make sense, probably crash CKAN, and not work anyways due to conflicts.

**Comment by 7ranceaddic7** [comment]
This is why I use what I call the "telephone keypad method." Envision a telephone keypad, and the letters were the each one.

Step 1 (keypad 1) - create a fresh stock install.

STEP/Keypad 2 (ABC) - Tickoff any mods beginning with A, B, or C and only accept "depends" items. Install.

STEP/Keypad 3 (DEF) - Tickoff any mods beginning with D, E, or F and only accept "depends" items. Install.

Repeat thru STEP/Keypad 9.  Profit.

It takes maybe 5 to 10 minutes longer but ensures a good install.

**Comment by HebaruSan** [comment]
> why not allow the mods it completed installing to stay

Because those mods can have dependencies that failed to install. CKAN tries to ensure that it never creates a bad install like that.

> so i can manually deselct the couple mods i don't want rather than having to click 175 check boxes one at a time

This is probably the place where we can make the biggest difference; it sounds like it's saying that the change set is cleared after a failed install, and we should be able to preserve it so the user can adjust it and try again.

@CritHappens7410, can you please give an example of a specific time when you had this problem, so we can try it out and test out strategies for improvement? If we have to guess what you're encountering then the chances that our efforts will help you are much reduced.

**Comment by AaronLS** [comment]
"Error during installation!" needs to also include the underlying error.  For example, I know CKAN will fail if it attempts to overwrite an existing file.  It needs to actually communicate what file it was attempting to write when it failed, and what the underlying error was.

**Comment by HebaruSan** [comment]
@AaronLS thanks for contributing, but this issue is about recovering from errors during the installation process. If you have a scenario where an error is not printed when it should be, please start a new issue covering that.

**Comment by HebaruSan** [comment]
OK, I just tried this out, and the changeset is **not** cleared after a failed install. The mods I selected still have their checkboxes checked, and I can even use the Retry button in the Status log tab to try again. So far there is no apparent need to re-check 175 checkboxes after an install failure, so it's not clear what the complaint is here.

@CritHappens7410 if you are able to clarify, please reply and we can re-open this.
