### ISSUE TITLE
[Feature] User Guide on "packaging methods for ckan" request

### ISSUE THREAD

**Issue by aazard** [KSP-CKAN/CKAN#3159]
OS: Windows 10
Kerbal Space Program version(s): v1.3.1 to current (v1.10.x)

## Problem

Attempts to save a few 100mb per ckan network download via compression/recompression of up;pad zip and/or zipped files inside that archive.

I recently had an issue trying to preserve disk-space and bandwidth use over ckan with PPMd compressed zip files (via 7Zip) for this mod:

- https://spacedock.info/mod/2524/HumanStuff

As far as I can tell, CKAN docs lack a description of compression methods that it allows other than generically mentioning "zip".

## Suggestions

It is my suggestion that a brief "best practices for mod uploaders" doc.

Perhaps a foreword, any highlighted warnings and point form suggested practices with very short text example

### Describe alternatives you've considered

Asking in forums, but this is not a permanent solution for user documentation.

**Comment by HebaruSan** [comment]
This is somewhat intentional; CKAN tries to follow mod authors' lead in most things rather than dictating how they should create their mods. If the community accepts something as a common practice, it would be silly for CKAN to try to ban it.

A good rule of thumb is to create simple, normal ZIPs that work for most users in general. Note that [your PPMd ZIP](https://spacedock.info/mod/2524/HumanStuff/download/v1.0.5.1) did not meet this condition, as it was also impossible to unzip in most other applications, so even non-CKAN users would have had issues with it:

![image](https://user-images.githubusercontent.com/1559108/94192747-e5170380-fe9e-11ea-8af4-47f61d2dbacb.png)

![image](https://user-images.githubusercontent.com/1559108/94192777-ed6f3e80-fe9e-11ea-8a7b-2cf4913adfa9.png)

**Comment by HebaruSan** [comment]
The best place to add some documentation about this would probably be in the Troubleshooting section of the Adding-a-mod wiki:

- https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN#troubleshooting

**Comment by HebaruSan** [comment]
Added a section here:

- https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN#how-to-package-mods-for-ckan
