### ISSUE TITLE
Search UI feedback

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#3163]
Using CKAN 1.28.0

Not sure how much feedback you've gotten, but I really don't like the search being at the bottom of the window.  It's counter-intuitive.

I much preferred the older method of having the text fields at the top.  

I would be ok with the search being moved to the top, adn to have it as a drop-down, not a pop-up list.

**Comment by HebaruSan** [comment]
> Not sure how much feedback you've gotten

As far as I know this is the first. Thanks for reaching out.

**Comment by HebaruSan** [comment]
Firefox:

![image](https://user-images.githubusercontent.com/1559108/94623537-f0ee3580-02a3-11eb-99b5-e790e17d8df6.png)

**Comment by HebaruSan** [comment]
Libreoffice:

![image](https://user-images.githubusercontent.com/1559108/94623639-2eeb5980-02a4-11eb-989d-158634f08cb5.png)

**Comment by ValiZockt** [comment]
I also think it was better when located at the. Both LibreOffice and Firefox have it located at the bottom as it isn’t as nearly as important as in CKAN, mostly every time you start up CKAN you’re going to search something. It’s bit like moving the URL/address bar to the bottom in Firefox. 
I guess In the end I think it’s just something people aren’t used to.

**Comment by HebaruSan** [comment]
For what it's worth, I did try to keep it at the top initially in #3041, but I could not figure out how to create a custom "dropdown" in WinForms that floats over the grid with editable controls in it, and a simple expand/collapse on the top was really jarring because it caused the top of the grid to move up/down. Moving it to the bottom allowed those changes to be finished up and released.

Now that we know there's a preference for top, this is something we can return to. Reviewing Mono's C# source for the ComboBox control might reveal how to overcome the technical challenges.

**Comment by HebaruSan** [comment]
Some progress...

![image](https://user-images.githubusercontent.com/1559108/95794730-3819f480-0cae-11eb-8a4c-5c7bf7d8e016.png)

Any other search related suggestions while I'm at it? This would be a good time to add more filters if there are any others that could be useful, for example.

**Comment by HebaruSan** [comment]
Fixed in #3175
