### ISSUE TITLE
[Bug] NetKAN leaving stale tmp files around

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/CKAN#3168]
Problem
-------

NetKAN is leaving around stale files in CdFileMgr, leading to disk usage issues.

```
netkan@945a9d40d33e:/tmp/CdFileMgr$ du -hs *
1.6G    136049aa-d02d-4a.tmp
1.6G    190528d6-ffe7-44.tmp
1.6G    197cb16c-7bd8-49.tmp
91M    241da6c0-ee1f-45.tmp
91M    283785f4-c7a7-4e.tmp
91M    28df1ab1-cafd-4b.tmp
1.6G    2fabe926-dd25-46.tmp
91M    322b5b76-38b6-46.tmp
91M    3892e70d-d10d-41.tmp
1.6G    3d4376f1-748f-4f.tmp
1.6G    45782341-d73b-4c.tmp
91M    4c1f0f27-b592-4c.tmp
1.6G    5803da08-e7fb-4b.tmp
91M    610da03d-dba6-49.tmp
91M    67901f4e-6360-4a.tmp
91M    9e59cf92-ea96-48.tmp
91M    b8ec7a18-6db6-4e.tmp
1.6G    bcd5650b-fc6c-47.tmp
1.6G    c3fceeff-78d4-48.tmp
91M    c44a1bbb-b313-42.tmp
1.6G    c68dc340-e109-4b.tmp
1.6G    cc9752a0-ce66-4d.tmp
91M    d34b2f4a-ab1b-49.tmp
91M    e115d711-0f3f-44.tmp
1.6G    e529f468-8441-4c.tmp
1.6G    f0b979c7-b3b7-48.tmp
91M    f5d8bc81-dd90-45.tmp
```

**Comment by HebaruSan** [comment]
From chat, looks like the cache filled up, so we started failing when we tried to move from `/tmp` to cache.
We should catch that and delete the .tmp.

**Comment by DasSkelett** [comment]
Additionally, to solve the underlying problem of the full cache, we could think about being smarter when cleaning the cache. NetKAN will only ever need the latest version of a mod, so we could remove all the other ones, which could help with frequently updating mods. Right now, this would remove about 12 GB from older HumanStuff releases alone.

However since the cache filenames from netkan don't include version numbers (and even those would be unsafe to parse because of hyphens in identifiers/epochs/version strings), I don't know how we could achivee that yet.
