### ISSUE TITLE
[Bug] DLL for module ModuleManager found at GameData/ModuleManager.4.1.0.dll, but it's not where CKAN would install it

### ISSUE THREAD

**Issue by Lkz3879** [KSP-CKAN/CKAN#3221]
Background
----------
* Operating System: win 8.1
* CKAN Version:  1.29.2
* KSP Version: 1.10.1.2939

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no

Problem
-------
**Describe the bug**
I tried to update CKAN via the CKAN interface

**Steps to reproduce** click on the 
* Go to...
* Click on "add new update" button
* See error : 

"About to install:

 * Module Manager 4.1.4 (cached)
DLL for module ModuleManager found at GameData/ModuleManager.4.1.0.dll, but it's not where CKAN would install it. Aborting to prevent multiple copies of the same mod being installed. To install this module, uninstall it manually and try again.
Error during installation!"

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
> Have you made any manual changes to your GameData folder (i.e., not via CKAN)?
> no

I take it this should say "yes", as Module Manager was manually installed?

**Comment by Lkz3879** [comment]
I can't remember if i manually installed the previous version.

The path is: 

"D:\Microsoft Games\FSX\steamapps\common\Kerbal Space Program\GameData"

Is that too long?

**Comment by HebaruSan** [comment]
The length of the path is fine. The error is caused by CKAN wanting to overwrite Module Manager with a diifferent version; you have 4.1.0, and CKAN wants to install 4.1.4. When we added this error message in #3043, we assumed without realizing it that the file names would be the same (as it is for many other mods), but that assumption does not hold in this case. Now that we know about this, we can probably find ways to make it work better; thanks for the report.

In the meantime, there are a few workarounds you might try. First, if you use CKAN to install Module Manager **4.1.0** specifically, then the filenames should be the same, which would bypass the error. You can do this by selecting Module Manager in the mod list, then opening the Versions tab at the right and checking the checkbox next to the 4.1.0 version. After this, CKAN would be able to upgrade to Module Manager 4.1.4 automatically.

Alternately, you could try doing as the error message suggests and removing your copy of Module Manager 4.1.0. Then CKAN would be able to install it without being obstructed by an older version.

**Comment by Lkz3879** [comment]
Hello,
Thanks your help, this was the working option for me:
" You can do this by selecting Module Manager in the mod list, then opening the Versions tab at the right and checking the checkbox next to the 4.1.0 version. After this, CKAN would be able to upgrade to Module Manager 4.1.4 automatically."

have a nice day,
Luc

 

    Le dimanche 6 décembre 2020 à 18:28:06 UTC+1, HebaruSan <notifications@github.com> a écrit :  
 
 


The length of the path is fine. The error is caused by CKAN wanting to overwrite Module Manager with a diifferent version; you have 4.1.0, and CKAN wants to install 4.1.4. When we added this error message in #3043, we assumed without realizing it that the file names would be the same (as it is for many other mods), but that assumption does not hold in this case. Now that we know about this, we can probably find ways to make it work better; thanks for the report.

In the meantime, there are a few workarounds you might try. First, if you use CKAN to install Module Manager 4.1.0 specifically, then the filenames should be the same, which would bypass the error. You can do this by selecting Module Manager in the mod list, then opening the Versions tab at the right and checking the checkbox next to the 4.1.0 version. After this, CKAN would be able to upgrade to Module Manager 4.1.4 automatically.

Alternately, you could try doing as the error message suggests and removing your copy of Module Manager 4.1.0. Then CKAN would be able to install it without being obstructed by an older version.

**Comment by WGINC** [comment]
I had this too, but on the macOS version, it also does not work (with the same problem) with Interstellar KSP extended.

**Comment by HebaruSan** [comment]
Hi @WGINC, this problem is not possible with KSPIE because it does not contain the version number in its plugin's filename. If you can share the actual text of the error message you're getting, we should be able to investigate it.
