### ISSUE TITLE
[Bug] Auto-updater removes ckan.exe after "updating"

### ISSUE THREAD

**Issue by Krzeszny** [KSP-CKAN/CKAN#3245]
Background
----------
* Operating System: Windows 10 64-bit
* CKAN Version: Freedman or Eddington (not sure)
* KSP Version: 1.11

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes, I use a few non-CKAN mods such as Sounds of Space.

Problem
-------
**Describe the bug**
Auto-updater removes ckan.exe (and possibly removes its own executable.)

**Steps to reproduce**
* Have an outdated CKAN (I had either v1.28.0 or v1.29.0 before this happened)
* Open the outdated CKAN and let it auto-update

**Expected behavior**
The executable should be removed _before_ the new executable starts downloading.

**Screenshots (if applicable)**
-

**CKAN error code (if applicable):**
No logs available.

**Comment by HebaruSan** [comment]
Thanks for the report. Investigation notes:

The auto updater is _supposed to_ delete the old ckan.exe, but then it's supposed to move the downloaded new ckan.exe to where the original used to be:

https://github.com/KSP-CKAN/CKAN/blob/ad3ccbe585b34ba5954793efb9bea10c43c5b6f6/AutoUpdate/Main.cs#L50-L72

So in this case the `Move` step must have failed or not run at all. Permissions? Disk space? Downloaded file deleted by something else while we waited?

One funny thing about that code, if the `Delete` call fails exactly 7 times and then succeeds on the 8th try, the `retries` mechanism would _still_ react as if there was a failure and quit without moving or launching, since it doesn't short circuit itself on success. Not sure how likely that is to happen (exactly 7 seconds of delay would be rare, but so is this bug report), but that logic could still use some improving.

Maybe as a first step toward solving this, we could add some more error detection and reporting to the auto updater. C# has a `System.Windows.Forms.MessageBox` class that should work even if we don't have a full GUI running.
