### ISSUE TITLE
[Bug] MechJeb2 and Real Chute are missing?

### ISSUE THREAD

**Issue by RegularLoser** [KSP-CKAN/CKAN#3257]
## Background

* Operating System: Windows 10
* CKAN Version: v1.29.2
* KSP Version: 1.11.0.3045

I've installed maybe 2-3 mods manually and revived some kerbals.

## Problem

Missing Mods.

MechJeb2 and Real Chute are gone. Parachutes disappeared as well?

**Comment by HebaruSan** [comment]
What do you mean by "missing"? You can't find them in CKAN?

**Comment by simoncozens** [comment]
Same here. But I think this is because of version compatibility. The latest release of mechjeb2 in the repository has `"ksp_version_max": "1.10.90"`, so you will not see it in the list if your KSP version is 1.11. (Even though apparently it works fine, just with a warning.)

**Comment by simoncozens** [comment]
(` ckan install --allow-incompatible MechJeb2` worked fine.)

**Comment by DasSkelett** [comment]
So it's not missing for you @simoncozens, it's just not compatible with your KSP version.

Alternatively to passing `--allow-incompatible`, you can also add 1.10 to your compatible game versions: `ckan compat add 1.10` or [here](https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions) are instructions for the GUI.

Be advised that not all mods for 1.10 work flawlessly on 1.11, so better to check the forum threads of those mods first.

Since the forum thread matches our metadata with 1.10 still being the max version for MechJeb (same for RealChute, don't see a mod called "Parachutes"), I don't think there's any action needed on our side. And when the max version changes I'm confident that we get a PR by Sarbian as usual.

![grafik](https://user-images.githubusercontent.com/28812678/104029617-7bf79980-51ca-11eb-8dbf-c5c778d8dc3c.png)

---

@RegularLoser I'm assuming you meant the same with "missing", so I'm going to close this issue now.
See the link above for instructions on how you can install these mods regardless.
If you meant something else, feel free to reopen this issue but please give us more information.
