### ISSUE TITLE
[question] How can I help to translate CKAN?

### ISSUE THREAD

**Issue by vinix38** [KSP-CKAN/CKAN#3270]
Hi, I would like to help and translate CKAN in French, but don't know how.
I followed what the wiki says: I forked the repository and went into the localization folder. At this point, I'm instructed to copy the English folder, rename the files accordingly and start translating. However, I ran into an issue: there are only four files there, which, it seems, do not contain anything translatable. In other languages' folder, there are 27 files, with an actual complete translation. 
The thing is, I can only translate from English, as my knowledge is limited.
I suppose the English files can be generated in some way, but I do not know how.
So, the actual (probably annoying) questions:
- do you think it is possible to translate CKAN with little knowledge in coding?
- is there a way for me to obtain those files?
- if not, do you think you could send them to me in some way?
- did I miss something in the wiki?
- do you like chocolate?

**Comment by HebaruSan** [comment]
Hi, thanks for wanting to help out!

For a quick reference, see #3014 for how we got a Chinese translation; you'd want your changes to look something like that.

> * do you think it is possible to translate CKAN with little knowledge in coding?

Yes, it should be possible to accomplish it just by creating new .resx files. You'll need help to generate builds to _test_ your changes, but that's pretty easy for us to provide for you. We can get into that once you feel you have enough completed to want to test it.

(We will want to make one code change to add `fr-FR` to the language settings choices, but you don't have to worry about that.)

> * is there a way for me to obtain those files?

Sure! The en-GB translations are the default (en-US just contains a few Americanese overrides like "favourites" → "favorites"), so they live alongside the source files rather than in a Localization folder. A search for `*.resx` files in the https://github.com/KSP-CKAN/CKAN/tree/master/GUI folder should find them:

GUI/Controls/EditModSearchDetails.resx
GUI/Controls/EditModpack.resx
GUI/Controls/AllModVersions.resx
GUI/Controls/ManageMods.resx
GUI/Controls/ChooseRecommendedMods.resx
GUI/Controls/ModInfo.resx
GUI/Controls/EditModSearch.resx
GUI/Controls/HintTextBox.resx
GUI/Controls/Changeset.resx
GUI/Controls/ChooseProvidedMods.resx
GUI/Controls/Wait.resx
GUI/Controls/DeleteDirectories.resx
GUI/Properties/Resources.resx
GUI/Properties/Resources.de-DE.resx
GUI/Properties/Resources.en-US.resx
GUI/Properties/Resources.zh-CN.resx
GUI/Main/Main.resx
GUI/Dialogs/CompatibleGameVersionsDialog.resx
GUI/Dialogs/EditLabelsDialog.resx
GUI/Dialogs/NewUpdateDialog.resx
GUI/Dialogs/AboutDialog.resx
GUI/Dialogs/SettingsDialog.resx
GUI/Dialogs/NewRepoDialog.resx
GUI/Dialogs/ErrorDialog.resx
GUI/Dialogs/RenameInstanceDialog.resx
GUI/Dialogs/YesNoDialog.resx
GUI/Dialogs/PluginsDialog.resx
GUI/Dialogs/GameCommandLineOptionsDialog.resx
GUI/Dialogs/CloneFakeGameDialog.resx
GUI/Dialogs/SelectionDialog.resx
GUI/Dialogs/AskUserForAutoUpdatesDialog.resx
GUI/Dialogs/ManageGameInstancesDialog.resx

> * did I miss something in the wiki?

I don't think we have a translation guide currently. That's a good idea, we can make a note to add it.

> * do you like chocolate?

Chocolate's not bad, but I spend all year long looking forward to Concord grape season.

**Comment by HebaruSan** [comment]
Hi @vinix38, thanks for letting us know about the problems with the translation instructions. They should be somewhat better now if you check again:

- https://github.com/KSP-CKAN/.github/blob/master/CONTRIBUTING.md#translating

**Comment by vinix38** [comment]
Thanks a lot for your detailed explanations, translation work has started :)

**Comment by DasSkelett** [comment]
> EDIT:
> ![image](https://user-images.githubusercontent.com/68441743/104894319-d3d59380-5974-11eb-9114-3447dd233889.png)
> I'm quite sure there is a part of it I must not translate, which words exactly?

This string is basically just a placeholder, it gets overwritten at runtime by the following string, with `{0}` being reblaced by the actual module identifier:
https://github.com/KSP-CKAN/CKAN/blob/e50b21d977101f3bfbd1876a292d0dab651a9170/GUI/Properties/Resources.resx#L272

**Comment by vinix38** [comment]
Ok, translation is finished! There might be some incoherencies here and there, but they will only be visible during use. 
Here is my repository:
https://github.com/vinix38/CKAN
Should I make a pull request to a branch?

**Comment by HebaruSan** [comment]
Yes, please! You can submit it to merge into KSP-CKAN/CKAN's master branch.
