### ISSUE TITLE
Yellow Text in Launcher

### ISSUE THREAD

**Issue by LordOther** [KSP-CKAN/CKAN#3357]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.30.0
* KSP Version: 1.11.2.3077

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**
Whenever I load up CKAN the words; File, Settings, Help, Launch Game, Refresh, Add Available Update, Apply Changes, and Filter are all in a bright yellow and completely unreadable unless I hover over them

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/77178781/116352682-27991980-a7bb-11eb-9278-25d12147ed55.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
Hm, I have a hard time thinking of any ways CKAN could possibly cause this.

Do you only experience this with CKAN? Or does the same happen for other apps as well?
Did this begin only recently, or has this been the case since you started using CKAN? If this only showed up recently, do you remember anything that changed on your system, like Windows updates, installing new software, ...?
Do you have any software installed (not KSP mod, actual programs installed on your system) that could interfere with the rendering of applications? Some kind of theme changer, post-processing stuff, "graphics enhancer", or whatever exists in Windows land?

**Comment by HebaruSan** [comment]
I'm guessing the OP accidentally ended up in the legacy Windows color settings and accidentally changed this one to yellow:

![image](https://user-images.githubusercontent.com/1559108/116408702-a70e0380-a822-11eb-98f2-09428a06f1a1.png)

**Comment by LordOther** [comment]
This never happened on my old computer and CKAN worked perfectly, I got a new computer and wanted to play CKAN and KSP with a better graphics card and better computer in general, but this yellow text is the first thing that greets me. I also am having trouble with making certain mods work, like toolbar, but I am chalking that up to wrong versions or me having downloaded wrong. This yellow text tho, I've never had that happen on my other computer.

**Comment by HebaruSan** [comment]
@LordOther that's kind of our point, if this was caused by something CKAN did wrong, it _would_ happen on your other computer as well as other people's computers. Are you able to check your Windows color settings?

**Comment by LordOther** [comment]
Yes I switched the colors and nothing changed, still bright yellow. I'm uninstalling CKAN and KSP to see if something went wrong when downloading

**Comment by HebaruSan** [comment]
What did you switch, exactly?

**Comment by LordOther** [comment]
Anywhere I could find colors or themes I changed but nothing happened. But was able to fix it by turning high contrast mode for my computer on and off, so nevermind, my computer was just being an asshole for some reason

**Comment by HebaruSan** [comment]
Cool, glad you got it working!
