### ISSUE TITLE
[Bug] Briefly summarize your issue here

### ISSUE THREAD

**Issue by NetherCraft1B** [KSP-CKAN/CKAN#3391]
* Operating System: Windows 10
* CKAN Version: 1.11.2.3077
* KSP Version: 1.11.2.3077

Problem: Failed to download https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz: Невозможно соединиться с удаленным сервером

**Comment by HebaruSan** [comment]
There was a big outage of many many web sites due to a problem at a CDN. Guessing that's what got ya.

https://www.cnn.com/2021/06/08/tech/internet-outage-fastly/

**Comment by NetherCraft1B** [comment]
Well thank you and when will I be able to properly install SKAN?

**Comment by NetherCraft1B** [comment]
I'm sorry, but can I ask you something? And when can I install SKAN?

**Comment by DasSkelett** [comment]
Do you still get this error? If so, it's probably not caused by the Fastly outage, since that should be resolved since quite some time.
Instead it might be caused by some rogue firewall or "anti-virus protection" software blocking access to GitHub for applications. Try disabling everything you can.

**Comment by NetherCraft1B** [comment]
![Безымянный](https://user-images.githubusercontent.com/85560399/121320315-ddb16080-c92e-11eb-9fe8-bcf5068ae8bc.png)

**Comment by NetherCraft1B** [comment]
I do not know what to do I tried different browsers and disabled antivirus programs but it did not help

**Comment by NetherCraft1B** [comment]
I did everything according to the instructions I was looking for this problem but it seems that I only have it

**Comment by DasSkelett** [comment]
Yes, this is a problem on your side. Something on your PC, or in your network, or in between your network and GitHub is blocking access to GitHub for CKAN.
But it's probably on your PC, specifically blocking the CKAN client, since you can still access GitHub via browser.

I'm sorry, but there's nothing we can do. It's not a CKAN bug or some other problem with CKAN or GitHub itself, because in this case everyone, or at least more people would report this problem.

Since I don't know your PC, I can't help you fixing it. I can only point you towards the usual suspects, that is some sort of firewall or antivirus software. If you can, maybe try to connect your device to a different network, maybe a hotspot from your smartphone, and see if that works. Or try starting CKAN on a different device, that might not have whatever interfering software you have installed. If possible, set up a completely fresh installation of Windows, e.g. in a VM, and see if it works there.

**Comment by NetherCraft1B** [comment]
Thank you very much now I will try to do my best...

**Comment by NetherCraft1B** [comment]
Hello, thank you, but nothing helped me and I can't play with mods in KSP, good luck and goodbye ...

**Comment by NetherCraft1B** [comment]
Hello once again I tried all the possible ways of VPN, Disk cleanup, reinstalling the game, restarting the computer, restarting the Wi-Fi modem, cleaning the computer with an antivirus, checking for viruses, reinstalling SKAN, reinstalling the browser but nothing helped what should I do I really want to play with mods in KSP?

**Comment by techman83** [comment]
@NetherCraft1B - Are you able to download the file directly? https://github.com/KSP-CKAN/CKAN-meta/archive/master.zip on the machine running CKAN?

That message is normally pretty clear 'Unable to connect to remote server'. Not much that CKAN can do for this issue, either something is getting in between CKAN + Github or you can't access Github at all. Ensure your time and date is accurate, this can often mess up SSL.

**Comment by NetherCraft1B** [comment]
![dssd](https://user-images.githubusercontent.com/85560399/121513887-2b9c9600-ca0d-11eb-8107-38159f8c39da.png)

**Comment by DasSkelett** [comment]
One thing I remember from a previous case of another user:
Check the `C:\Windows\System32\drivers\etc\hosts` file and see if there are entries for codeload.github.com and other GitHub-related domains. If yes, remove them.

**Comment by NetherCraft1B** [comment]
THANK YOU THANK YOU YES I NEEDED TO DELETE THESE FILES THANK YOU THANK YOU THANK YOU FOR THE ADVICE IT WAS CORRECT!!!

**Comment by NetherCraft1B** [comment]
I don't know how to thank you enough...

**Comment by techman83** [comment]
Maybe you can answer how they ended up there in the first place? Were there a lot of entries in the hosts file? Did you follow a guide for blocking ads?

**Comment by Nekonyakami** [comment]
I have the same problem, but now the SCAN does not want to run without an admin and now this file is not there
