### ISSUE TITLE
[Bug] --allow-incompatible does not wrok

### ISSUE THREAD

**Issue by Trolldemorted** [KSP-CKAN/CKAN#3405]
Background
----------
* Operating System: W10
* CKAN Version: CKAN 1.30.4
* KSP Version: 1.12

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** no

Problem
-------
I want to force-install RemoteTech on 1.12, but ckan ignores the --allow-incompatible flag.

**Steps to reproduce**
```
PS C:\Users\Benni> ckan install --allow-incompatible RemoteTech=v1.9.11
RemoteTech dependency on ModuleManager 2.3.1 or later version (any) not satisfied
If you're lucky, you can do a `ckan update` and try again.
Try `ckan install --no-recommends` to skip installation of recommended modules.
Or `ckan install --allow-incompatible` to ignore module compatibility.
```

**Expected behavior**
The `--allow-incompatible` flag is honored, or not suggested

**Comment by HebaruSan** [comment]
It does work, but it's only intended to affect the modules specifically named on the command line (otherwise the floodgates would be open and there would be no way to control what incompatibilities were ignored).
`ckan install --allow-incompatible RemoteTech=v1.9.11 ModuleManager` would probably do what you want.
Or just mark 1.11 as compatible.
https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions
