### ISSUE TITLE
ConsoleUI opens automatically on Mac 10.15 and later

### ISSUE THREAD

**Issue by ArtinGitHuber** [KSP-CKAN/CKAN#3472]
Hello, 
i have a macbook pro mid 2012,
i have previously used ckan and i have to say... I LOVE IT
there is an issue thats recently popped up,
the issue is that whenever i open ckan on my mac, it imidiately crashes,
 and opens up terminal (command equivalent for mac) and runs ckan on terminal, 
you have to use a keyboard, most mods that are useful or popular or i know exist on ckan are not in the mods list,
 some features are innacessible AND the biggest problem is,
 everytime i open up ckan it messes up my gamedata folder and disables most mods which work fine and are for 1.12
 (the version i have)
currently im redownloading ckan to get a picture to share it again

**Comment by ArtinGitHuber** [comment]
also i used the most recent ckan version

**Comment by DasSkelett** [comment]
On macOS 10.15 and later the GUI is no longer functional. That's why CKAN automatically starts to the console UI.

The console UI only shows compatible mods in the list. You probably want to extend the list of what CKAN considers as compatible a bit, many users are running with 1.8-.12 currently.
Instructions on how to do that and some more information is available in the [User Guide](https://github.com/KSP-CKAN/CKAN/wiki/User-guide#using-the-console-ui)

> everytime i open up ckan it messes up my gamedata folder and disables most mods which work fine and are for 1.12
(the version i have)

Can you clarify what you meant by that? CKAN doesn't change anything in GameData by itself, only if you tell it to install, upgrade or uninstall something.
Maybe you are confused by CKAN not detecting all the manually installed mods of yours. It is not possible to detect all of them, if you want all your installed mods to show up in CKAN, you should reinstall them through it. It's generally a good advise to uninstall all manually installed mods before starting to use CKAN anyway, to prevent any conflicts and situations like this.

**Comment by ArtinGitHuber** [comment]
oh no it doenst decet my manual mods AND it modifies my gamedata,
before ckan i had a few mods, i used them completely fine, then after i opened ckan, mods stopped working

**Comment by ArtinGitHuber** [comment]
can disabled the mods i manually installed and werent on its lists

**Comment by ArtinGitHuber** [comment]
also why isnt the gui funcional ?

**Comment by ArtinGitHuber** [comment]
isnt there a way to fix that ? or make a version or update

**Comment by DasSkelett** [comment]
> oh no it doenst decet my manual mods AND it modifies my gamedata,
before ckan i had a few mods, i used them completely fine, then after i opened ckan, mods stopped working
can disabled the mods i manually installed and werent on its lists

No I don't think that's what happened. As I said, CKAN doesn't touch your files unless you explicitly tell it to do so.
It's possible that one of the mods you installed through CKAN conflicts with other manually installed mods.

> also why isnt the gui funcional ?
isnt there a way to fix that ? or make a version or update

See the short explanation and links in https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-macOS:
- https://github.com/KSP-CKAN/CKAN/issues/2272
- https://github.com/KSP-CKAN/CKAN/pull/2911

No, there's not way for _us_ to fix it within CKAN, this is out of our control. We depend on the Mono framework for this.

**Comment by ArtinGitHuber** [comment]
is there a way to contact the devs and ask them to make a version or update thats compatible ?

**Comment by DasSkelett** [comment]
There is already an open feature request: https://github.com/mono/mono/issues/6701

However the Mono team expressed that there is no interest / there are no resources to make WinForms GUIs work on macOS again. It is also very unlikely that Apple will revert their removal of 32-bit application support.

**Comment by ArtinGitHuber** [comment]
thanks

**Comment by ArtinGitHuber** [comment]
just one last question

**Comment by ArtinGitHuber** [comment]
how do i change supported versions on ckan in the mac version

**Comment by HebaruSan** [comment]
> how do i change supported versions on ckan in the mac version

See the user guide:

- <https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions-1>

**Comment by ArtinGitHuber** [comment]
thanks]
