### ISSUE TITLE
Prompt user to delete non-empty folders after uninstall in the ConsoleUI

### ISSUE THREAD

**Issue by The0n1y5pace4ce** [KSP-CKAN/CKAN#3484]
Background
----------
* Operating System: macOS
* CKAN Version: Hubble
* KSP Version: 1.12.2

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Yes, other mods not included in the macOS version of CKAN

Problem
-------
**Describe the bug**
Dont know if this counts as a bug, but when un installing a mod installed via CKAN, the proper mod folders are kept, but the contents on them are removed except for the `@thumbs` folder inside the parts folder, this does not affect me physically, but can make it harder to manage my gamedata folder

**Steps to reproduce**
* Go to CKAN and uninstall a mod installed through CKAN
* Click on gamedata and then you will still see the folder

**Expected behavior**

The `@thumbs` folder in the parts is there, nothing in it, nothing around it

**Comment by DasSkelett** [comment]
CKAN does not remove files it didn't install by default, the `@thumbs` directories are created dynamically when the game is running.
Since #2962 the GUI asks whether to remove remaining files and folders.
This feature doesn't exist in the console UI yet, which I suspect you are using, as you mention "the macOS version of CKAN".

It might be time to add it as well, given how much we rely on the console UI now on macOS. I'm going to label this as feature request.

**Comment by HebaruSan** [comment]
The core idea of this enhancement is still valid, but #3890 added auto-deletion of game-created `@thumbs` folders.
