### ISSUE TITLE
[Feature] possibility to disable DLC in the CKAN

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/CKAN#3504]
DLCs could be manageable in the CKAN (if they are bought)

For example, on disabling to move folder from `KSP\GameData\SquadExpansion\` to `KSP\SquadExpansionDisabled\`
and to move it back on enabling.

**Comment by HebaruSan** [comment]
Why?

**Comment by yalov** [comment]
Why someone want to disable DLC? 

Mostly because someone could prefer to use mods providing the same functionality, and therefore to clear up setup by disabling the unnecessary DLC. Manually it could be done by moving the folder somewhere. 

Why it need to be on CKAN?
It is a little bit more convenient.  
And Restock+, KIS1, or some other could propose to disable DLC using the https://github.com/KSP-CKAN/CKAN/issues/2961

**Comment by HebaruSan** [comment]
Why would the user install the DLC in the first place if they did not want it?

**Comment by DasSkelett** [comment]
I don't think this is a feature for CKAN. CKAN doesn't and shouldn't touch stock game files.

Would renaming the directory actually disable the DLCs? If the loading works just like for mods (which I suspect it does), it will still load the DLC for the most part – except some parts of it might be broken due to mismatching paths.
The only safe way to fully remove a DLC would be completely removing it from GameData, but unless we save it at some backup location, there's no way CKAN could install them again.

**Comment by yalov** [comment]
user want the DLC today, doesn't want it tomorrow, and want it back after a week, just like any mod

@DasSkelett yes, move `KSP\GameData\SquadExpansion\DLC1` to `KSP\SquadExpansionDisabled\DLC1` outside the GameData

**Comment by HebaruSan** [comment]
Thanks for submitting the suggestion, but after considering it, I agree that this isn't something we should add to CKAN. The risk of corrupting game files is serious, the benefit is minimal and dubious, and the user already has a superior workaround of not-installing-the-DLC. Closing as won't be worked on.
