### ISSUE TITLE
Registry already enlisted with tx error during install (again)

### ISSUE THREAD

**Issue by JovietUnion** [KSP-CKAN/CKAN#3517]
Background
----------
* Operating System: Windows 10 Home
* CKAN Version: 1.30.4
* KSP Version: 1.8.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Had to delete some mods due to bdarmory making my files unable to load any launch pads.

Problem
-------
**Describe the bug**
When I download any file, it produces this error:

```
CKAN.TransactionalKraken: Registry already enlisted with tx 164d9040-8979-4c98-8682-1b3168c55039:80, can't enlist with tx 164d9040-8979-4c98-8682-1b3168c55039:86
   at CKAN.Registry.EnlistWithTransaction()
   at CKAN.Registry.RegisterModule(CkanModule mod, IEnumerable`1 absolute_files, GameInstance ksp, Boolean autoInstalled)
   at CKAN.ModuleInstaller.Install(CkanModule module, Boolean autoInstalled, Registry registry, HashSet`1& possibleConfigOnlyDirs, String filename)
   at CKAN.ModuleInstaller.InstallList(ICollection`1 modules, RelationshipResolverOptions options, RegistryManager registry_manager, HashSet`1& possibleConfigOnlyDirs, IDownloader downloader, Boolean ConfirmPrompt)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Steps to reproduce**
* Go to... ckan
* Click on... any mods. Apply Changes.
* Wait...
* See error

**Expected behavior**
Mods should install fine.

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/62820134/149818495-4fdc6138-f1dd-4d8d-a15f-171667d8f4bb.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
There is none in the error box.
```

**Comment by HebaruSan** [comment]
Hi @JovietUnion, thanks for reporting this. We saw this once before in #3502, but we weren't able to investigate because the author of the issue wasn't responsive.

We don't have enough information yet to figure out what's wrong, so I have prepared a debug build of CKAN and a log4net.xml file with some settings to make it generate a log file for us. Please download it here:

- [ckan-tx-debugging.zip](https://github.com/KSP-CKAN/CKAN/files/7824891/ckan-tx-debugging.zip)

1. Extract both files in the ZIP to a folder on your disk
2. Run the copy of ckan.exe in that folder
3. When CKAN appears, make the error happen
4. Close CKAN
5. In the folder from step 1 find a file called CKAN.log
6. Upload this file to a sharing site like Google Docs and share the link here
   (Or if you put it into your own new ZIP file, you can upload it directly to GitHub by clicking on the bottom of the text box where it says, "Attach files...")

This will help us to figure out the sequence of events that lead up to the error. It may allow us to determine the problem, or we may need to gather more information.

**Comment by JovietUnion** [comment]
Ok. Glad I'm able to help with these issues. No program is ever truly
perfect, and I know that by experience.

**Comment by JovietUnion** [comment]
windows cannot access the specified path or item.

**Comment by HebaruSan** [comment]
Huh? When is it saying that? What are you doing when it happens?

**Comment by JovietUnion** [comment]
I tried running the .exe file after extracting it to a folder in 3d objects.

**Comment by HebaruSan** [comment]
Why in 3d objects? Is that a special folder? You should just put this someplace normal like your desktop or downloads. That error message means there's probably something wrong with the permissions where you unzipped it, here's some background from Microsoft:

https://support.microsoft.com/en-us/topic/-windows-cannot-access-the-specified-device-path-or-file-error-when-you-try-to-install-update-or-start-a-program-or-file-46361133-47ed-6967-c13e-e75d3cc29657

**Comment by JovietUnion** [comment]
Placed in desktop and it still doesn't work. Same error

**Comment by HebaruSan** [comment]
Try the troubleshooting steps at the link I posted earlier, I guess. Something on your computer is stopping you from running the file, and you'll have to figure out what it is. All I can do is guess.
