### ISSUE TITLE
[Policy] De-indexing policy still contradictory

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/CKAN#3518]
Problem
-------
The de-indexing policy was amended a number of years ago, controversially. The outcome of this amendment is that the policy contradicts itself. 

The policy currently contains this text:

>   When an author gives us explicit and irrevocable permission via a legal document to redistribute their work, we cannot in good faith de-index the mod and still act in the interests of our users. Whenever possible, mods with permissive licenses will be preserved by the CKAN, especially when alternate downloads to such mods exist, including those cached by the CKAN's own automated systems.

>   In some cases it's not possible to install mods via the CKAN and maintain the goodwill of the author(s). The CKAN will not install any mod when the primary maintainer (or a significant group of maintainers when no primary is identifiable) requests the mod be removed from the CKAN.

These two paragraphs directly contradict each other. 

For those who came in late: This was last addressed in #2147, which was closed without merging. The issue was first raised in #1793. 

From the PR:

>   Delisting permissively-licensed mods is a workaround until we can implement a system to allow listing with manual installation.

It seems clear this "temporary workaround" is in fact the official policy by default. 

Suggestions
-----------
I submitted a PR already, which was closed (#2147). This could be adopted as it stands. 

Alternatives exist. A discussion by current contributors about CKAN's values and policies could generate a more up to date and inclusive version which clarifies the policy as it stands. 

Musings
----------
It seems clear that one must be more important - either the requirement to act in the interests of CKAN users, or the requirement to maintain the goodwill of the authors. At present, we prioritise the latter, and this seems unlikely to change anytime soon. Therefore it seems likely that any change to the document must come to the former paragraph - at its simplest, by deleting the first line. I suggest that simplicity of change is not a desirable outcome here.

**Comment by HebaruSan** [comment]
@DasSkelett, as current ship's captain or whatever the role was called, I think this decision would be up to you. I agree the current text is incoherent, and I (still) think a full rewrite is in order.

It's in users' interest to keep mods listed, _but the CKAN team ought to earn that by working well with mod authors_, as judged by the mod authors themselves. So the interests of users and authors align more than might initially be suspected. I've always believed that the healthiest approach is to build relationships with mod authors at time of indexing and get them to opt-in, regardless of the details of the policy, because then if something does go wrong, we're all going to be starting off on friendlier footing as we work toward a resolution that satisfies everybody, rather than one party feeling victimized and put-upon.

If there are problems with how mods are being installed (as far as I know, there aren't anymore), then the best solution is to fix that problem rather than getting sidetracked into a debate over the ins and outs of software licensing again for fifty pages and/or fighting over de-listing (which also has not actually been a live issue, with I think two authors asking to be de-listed in about a 4 year span).

**Comment by Blu3wolf** [comment]
We largely agree. We agree that the CKAN team ought to work well with mod authors, and that building relationships is a healthy approach. We also agree that a debate over the ins and outs of software licencing would be a sidetrack, and I suggest a pointless one: I suspect nothing has changed in the last 6 years which would change anyone's views on the matter.

**Comment by DasSkelett** [comment]
I'm also in favor of a full rewrite of this document.

To summarize our current de-facto policy:
- We ask mod authors for their agreement before putting their mods on CKAN. We do this for every mod of the author, because while one mod might be ready for CKAN, the other might not be.
- We reserve the right to decide against indexing a mod, even if an author wants us to.
  This could be (no-exclusive) due to 
  - technical reasons, or because
  - it violates somebody's copyright as determined to the best of our abilities (we aren't lawyers), or
  - it conflicts with our code of conduct, or 
  - we don't think the mod is a good fit for CKAN generally or 
  - because it could be save-breaking in an unexpected way ("joke mods").
- When a mod author asks us to de-index a mod for whatever reason, we do so.
	- However we do not remove the mirrored uploads from archive.org, because those are not only meant for CKAN, and they still have their right to exist
	- We also don't take active measures to prevent users from installing the mod through CKAN. I.e., they can still recover the old metadata from the git history or write it from scratch themselves, and add it as a custom repository to CKAN.

Points one and two probably don't fit in a document specifically for de-indexing, but we could rename the file and make it a more general "indexing policy" document.

This basically only leaves the third point. A bit short for a full document, but that's how it is.
If we want to keep a "principle" foreword, I'd say it should be
> **The CKAN acts in the interests of the modding community.**

We are there for mod authors _and_ users. Ideally we make the life easier for both groups. As @HebaruSan already mentioned, quite often de-indexing a mod at the request of an author is in the interest of users too, often already in the short run (broken mod, retired author who can't/won't give support anymore), but especially in the long run.

**Comment by Blu3wolf** [comment]
I was not expecting to have a wellspring of support for my position on the subject. As you may have surmised already, I firmly disagree with this paternalistic stance. I still think it would benefit CKAN, and its users, to clarify the policy document, even if the clarifications are deeply unpleasant to me. 

In any event, I've already made one PR on this topic. I dont think Ive the ability to draft a full rewrite based on the above summary of current policy. I do regret that this is an issue rather than a PR :  FOSS projects blossom when users submit PRs rather than issues.

**Comment by HebaruSan** [comment]
I'm not sure whether this was your intention, but that's coming off as an invitation to a debate over whether we are paternalistic (or whether what we are, whatever it should be called, is good or bad). No thanks.

**Comment by HebaruSan** [comment]
> us as [...] an organisation

Have to admit I'm a bit confused here, are you a member of an organization that's connected to this policy? Obviously anyone is welcome to point out problems or provide feedback, member or not, but you seem to see yourself as integrally involved in drawing up rules for what some other people are doing.

**Comment by Blu3wolf** [comment]
Indeed. Well then Ill leave you to it, as you seem to prefer to avoid my involvement.

**Comment by HebaruSan** [comment]
You made a valid point that the document needs to be revised, and we thank you for that.

But when it comes to what the final policy should be, wouldn't you expect that would be the domain of people with some relevant experience, who would also be the ones following and enforcing the policy day to day? Wouldn't that just be natural?
