### ISSUE TITLE
GUI offers to "upgrade" autodetected DLLs

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#352]
See [this comment](http://forum.kerbalspaceprogram.com/threads/97434-The-Comprehensive-Kerbal-Archive-Network-Call-for-mod-participation?p=1540255&viewfull=1#post1540255).

If something has been installed outside of the CKAN, then we promise to _never_ touch it. Consequently, we certainly can't upgrade these mods.

Autodetected DLLs should probably be greyed-out, or otherwise indicated that they can't be interacted with via the client.

**Comment by Fluffkin** [comment]
Sorry to necro this one but! (I'm going to anyway)
A "force CKAN update" option would be handy:
I've got "ModuleManager" autodetected and would like to install the CKAN provided link.
The relationships tab doesn't tell me which other mods I use depend on it.
If I delete the ModuleManager DLL, CKAN freaks out because other mods depend on it, so I can't get CKAN to install it that way because it stays "autodetected" even though it's not there.
If I put it back, it returns to happily autodetecting it, but won't let me install the CKAN linked version.
So yeah ..
A force CKAN install over a selected, autodetected mod option might be nice, with a big "Are you sure you want to overwrite files? This is often a bad idea" popup or something.
