### ISSUE TITLE
Unhandled Exception: Not Enough Space on Disk

### ISSUE THREAD

**Issue by apzeedyk** [KSP-CKAN/CKAN#3581]
Unhandled exception when trying to download to a full hard drive causes CKAN to crash. Should check for enough space before downloading and notify the user if there is not enough space on the disk from which CKAN was launched (NOT the disk that KSP is installed on.)

As is, the download crawls and stalls as it reaches the limit of free space, then the crash report looks more dev-oriented than user oriented so it's not immediately obvious what is the cause of the issues.

**Comment by HebaruSan** [comment]
Last time we looked into this, checking disk space in .NET wasn't possible due to the lack of any mapping from the [`DirectoryInfo`](https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo?view=netframework-4.7.2) that we are given by the cache settings to the [`DriveInfo`](https://docs.microsoft.com/en-us/dotnet/api/system.io.driveinfo?view=netframework-4.7.2) that would tell us the `AvailableFreeSpace`. But we could try to catch the exception and clean up rather than letting it fall to the unhandled exception handler.

@apzeedyk, do you happen to have a copy-paste of the text of the exception on hand? I can't reproduce this at the moment for investigation because my disk isn't full.

**Comment by apzeedyk** [comment]
Sorry, no I actually moved just last week and havent even had a chance to
set up my pc yet and it's been too long for me to remember even vaguely
what the error message or anything was like.

(For the record, i appreciate everything the devs do for the KSP community
and i only brought this up to try to help improve the experience for
everyone, not because i was butthurt about 10 minutes of confusion. Thank
you all for everything you do.)

**Comment by HebaruSan** [comment]
That's cool, good luck with your new digs, and if you do have a chance to get your PC set up and try this out, please do share the output if you can.

(Now I'm wondering if we could search the known drives for one where [`DriveInfo.RootDirectory`](https://docs.microsoft.com/en-us/dotnet/api/system.io.driveinfo.rootdirectory?view=netframework-4.7.2) matches the [`DirectoryInfo.Root`](https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.root?view=netframework-4.7.2) property of our cache folder. The big wildcard would be Mono and whether it actually provides the needed info for a Linux/Mac filesystem.)

**Comment by HebaruSan** [comment]
What **does** seem to work is looking for the `DriveInfo` with the longest `RootDirectory.FullName` that's a prefix-substring of the cache's path; I _think_ this is cross-platform (on Windows, `DriveInfo.RootDirectory.FullName` should always be `C:\`, `D:\` etc.):

```csharp
private static DriveInfo GetDirDrive(DirectoryInfo dir)
    => DriveInfo.GetDrives()
                .Where(dr => dir.FullName.StartsWith(dr.RootDirectory.FullName))
                .OrderByDescending(dr => dr.RootDirectory.FullName.Length)
                .FirstOrDefault();
```

```
$ _build/ckan.exe cache list
/media/DataTrove/Games/CKAN_downloads2
4829 files, 85.5 GiB, 2,176.7 GiB free

$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       217G  197G  8.9G  96% /
/dev/sdc1       5.5T  3.1T  2.2T  59% /media/DataTrove
```

**Comment by HebaruSan** [comment]
Finally found some previous disk-full issues: #1236, #1422

One of them has a small amount of useful information:

![image](https://user-images.githubusercontent.com/1559108/183672118-68f8869c-8517-4b11-8416-c018d4792c0b.png)

So the exception to catch might be [`System.IO.IOException`](https://docs.microsoft.com/en-us/dotnet/api/system.io.ioexception?view=netframework-4.7.2). Unfortunately that exception would be used for many other disk-related issues, and there don't seem to be any properties that can tell us whether it's caused by a full disk. :facepalm:

We also need to identify specifically when it's happening. There are at least three separate possibilities:

- Trying to write a download to the temp folder
- Trying to copy a downloaded file from the temp folder to the CKAN downloads cache
- Trying to extract files from a ZIP in the cache into GameData

**Comment by HebaruSan** [comment]
Have a prototype going, feedback welcome:

![image](https://user-images.githubusercontent.com/1559108/183706793-2c2037c7-be2e-4e2d-876e-c9363fd6c51a.png)

**Comment by HebaruSan** [comment]
Each of those three enumerated cases will have its own custom message:

![image](https://user-images.githubusercontent.com/1559108/183710769-f3db4099-fb45-4cbf-9f7c-b457428c1eb9.png)

![image](https://user-images.githubusercontent.com/1559108/183711651-db17180a-81c7-4249-93f5-3dffb1ba77eb.png)
