### ISSUE TITLE
[Bug] Cant download "Karbonite" from RoverDude

### ISSUE THREAD

**Issue by Ferigad** [KSP-CKAN/CKAN#3601]
Background
----------
* Operating System: 
* CKAN Version: 
* KSP Version: 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**
Karbonite cant be downloaded, the URL to the Mod from CKAN shows: "Not found"
https://github.com/BobPalmer/Karbonite/releases/download/1.2.0.0/Karbonite_1.2.0.0.zip

CKAN will just try to download it and never stop (i waited 10 Minutes without anything happend, except the download try running)

**Steps to reproduce**
* Try to download Karbonite for KSP version 1.7.2. or 1.8

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Thanks for the report, it looks like that release was removed or changed after we indexed it...

**Comment by HebaruSan** [comment]
Metadata: https://github.com/BobPalmer/Karbonite/releases/download/1.2.0.0/Karbonite_1.2.0.0.zip

Release: https://github.com/UmbraSpaceIndustries/Karbonite/releases/download/1.2.0.0/Karbonite_1.2.0.0.zip

Ahh, it's because the mod was moved from the `BobPalmer` account to `UmbraSpaceIndustries`. I know we cleaned up several of those earlier, but I guess there are a few more to do.
