### ISSUE TITLE
[Bug] Apt repository doesn't support architecture "i386"

### ISSUE THREAD

**Issue by DJLevel3** [KSP-CKAN/CKAN#3602]
Background
----------
* Operating System: Ubuntu 22.04
* CKAN Version: 1.30.4
* KSP Version: 1.12

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
When the apt repository is added to the system package list, updating packages succeeds but produces the warning `N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://ksp-ckan.s3-us-west-2.amazonaws.com/deb stable InRelease' doesn't support architecture 'i386'`

**Steps to reproduce**
* Add the apt repository
* Update packages (sudo apt update)
* Error appears at end of update

**Expected behavior**
No error appears

**Comment by HebaruSan** [comment]
Yeah, we know about this, it came up when we were first creating the APT repo. There's a reason for it, but I'll have to dig into the history to find it...

**Comment by HebaruSan** [comment]
OK, the first thing to note here is that [the `N:` prefix stands for "NOTICE"](https://askubuntu.com/questions/1081507/what-do-the-letters-stand-for-in-apt-errors), a lower alert level than an error or even a warning. It's one level higher than "DEBUG", which in modern `log4net` would correspond to "INFO", so it's basically letting you know about something rather than reporting a problem that's going to affect you.

Next, it's important to note that our `.deb` file *isn't* for i386. It's platform-neutral, because that's how .NET and Mono work. APT is telling you that there isn't an i386 build of our package, which is correct and intentional. Initially we set the architecture to `all` to try to reflect that accurately, but then APT printed that `N:` message for both i386 _and_ amd64 (and I think we finally found some documentation explaining that that was not the intended usage of the `all` architecture), so eventually we decided to [change the arch to amd64](https://github.com/KSP-CKAN/CKAN/commit/a27f4adf6553c99d9c710d539829e181c69e7c90) so at least we could suppress the message for the architecture that 98% of people are using.

If you really want to suppress the message, you can add `[arch=amd64]` to the `sources.list` file containing our repo. We left this out of the instructions to keep them simpler:

```
deb [arch=amd64] https://ksp-ckan.s3-us-west-2.amazonaws.com/deb stable main
```

As far as we could determine when we were setting it up, APT doesn't provide a better way of doing this on our end. Please let us know if you know of one, but otherwise, we're sorry for the annoyance.
