### ISSUE TITLE
Error: could not find a distribution template for Debian/Bullseye

### ISSUE THREAD

**Issue by tskozel** [KSP-CKAN/CKAN#3607]
Background
----------
* Operating System: Debian 11 - Bullseye
* CKAN Version: **Not needed,** but 1.31.0
* KSP Version: **Also not needed**, but 1.12.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No.

Problem
-------
**Describe the bug**
When the apt repository for CKAN is added, there is a Python error: 
```
File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Debian/Bullseye
```
The repository probably is not set up to handle Debian 11.

**Steps to reproduce**
* Go to the [apt repo guide](https://github.com/KSP-CKAN/CKAN/blob/master/doc/apt-repo.md)
* Follow the instructions for stable
* See error

**Expected behavior**
Repository is added

**Screenshots (if applicable):**
![Error](https://i.imgur.com/XNyBrOU.png)

**CKAN error code (if applicable):**
~~PLACE CODE HERE !~~ NONE

**Comment by HebaruSan** [comment]
> The repository probably is not set up to handle Debian 11.

As far as I know, that isn't how APT works; there isn't special setup for different releases of different OSes (but if you've found a source stating otherwise, please do share it so we all may learn). Especially notably, the error happens before any actual data is retrieved from our repo (`apt-add-repository` just makes some edits to your system's files to make subsequent commands download from our repo). All the web searches that I've done for this error message indicate that a local configuration problem is more likely:

- https://askubuntu.com/questions/1277931/add-apt-repository-ppa-always-throws-an-error
- https://github.com/elementary/os-patches/issues/136
- https://askubuntu.com/questions/277910/why-did-i-have-to-edit-etc-lsb-release-to-get-apt-get-to-work
- https://askubuntu.com/questions/1231856/aptsources-distro-nodistrotemplateexception-error-could-not-find-a-distributio

Specifically, the consensus seems to be that there's some problem with your `/etc/lsb-release` file. Please take this issue up with whatever party is responsible for supporting your OS.

**Comment by tskozel** [comment]
My lsb release was messed up after a kali metapackage changed it to kali, so i had to change it back manually and messed up. I fixed it by copying the /etc/os-release file from server running debian.
