### ISSUE TITLE
[Bug] Trying to reinstall a mod which has a dependency doesn't work due to the dependency

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#3725]
Background
----------
* Operating System:  Windows 10, latest build
* CKAN Version:  1.31.2
* KSP Version: 1.12.4

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
Clean game, installed X-Science only.  Dependencies are ClickThroughBlocker, SpaceTuxLibrary and ToolbarController
No installation filters 

1. Select one of the mods
2. Right-click and select "Reinstall"
3. Get the next page which shows Recommendations (on a reinstall, why?)
4. Don't change anything
5. Click Continue
6. Get the message the it already contains module (see attached image)

Doing a Retry then appears to work

However, after some testing, it appears that the mod did NOT get reinstalled
This was tested by removing the dll and seeing if it was reinstalled while investigating an issue with the mod.  This raises the issue from an annoyance to a significant problem

**Expected behavior**

Do the reinstall without this error page

**Screenshots (if applicable)**

![reinstall](https://user-images.githubusercontent.com/1630166/203775951-34cb4097-cf64-4c39-8ebd-48f696c928ce.png)

**CKAN error code (if applicable):**

Message at bottom of screen:  :Error during installation!"
```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
The message is from `RelationshipResolver.Add`, raised when one of the mods in the changeset is already in the resolver:

https://github.com/KSP-CKAN/CKAN/blob/3f9b2f01d0857ba39d445c04290033f695c3ae7d/Core/Relationships/RelationshipResolver.cs#L581-L594

Notably, the mod in the message isn't the one chosen to reinstall, it's one of the dependencies. Presumably there's a problem with how the changeset is prepared for reinstalls.

**Comment by HebaruSan** [comment]
That second code block creates a changeset containing:

- Remove the selected mod
- Install the selected mod 
- Install all mods depending on it (since these are auto-removed by removing the selected mod)
- Install any of the selected mod's auto-installed dependencies that woudl be auto-removed

So far I'm having luck with building a changeset that explicitly removes _all_ of the mods that are in the re-install list, rather than depending on the `ModuleInstaller` to remove them.

I think I also found a performance problem; since `FindReverseDependencies` returns `IEnumerable<string>` and is lazily evaluated, `revdep` will be re-evaluated from scratch for each `!revdep.Contains(im.identifier)` call. It should be stored into a hashset and re-used.
