### ISSUE TITLE
Chatterer.dll is registered to Chatterer but has not been removed

### ISSUE THREAD

**Issue by Tcarter1230** [KSP-CKAN/CKAN#3856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

1.32.0

### Game Version

1.12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

i did load up a backup file for KSP twice

### Describe the bug

the Chatterer mod for KSP is not uninstalling. when i try to uninstall the file it just says, "file is in use" KSP isn't open and Ckan isn't open

### Steps to reproduce

1: Go to Ckan and download the Chatterer mod for KSP
2: Install the mod
3: Open KSP and close it after some time
4: go to uninstall the mod.
5: see the error

### Relevant log output

```shell
c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/Chatterer/Plugins/Chatterer.dll is registered to Chatterer but has not been removed!
```

**Comment by HebaruSan** [comment]
> KSP isn't open

If you're saying this because you exited the game, try checking Task Manager. It's possible for a process to continue running after you close the window, especially if there's some sort of problem. This error message means some process is holding a lock on `Chatterer.dll`, and KSP is the only process that would do that.
