### ISSUE TITLE
[Feature]: When uninstalling a mod, generated @thumbs directories should be auto-removed

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#3886]
### Problem

I just handled support for someone who had tried to uninstall USI LifeSupport using CKAN but apparently didn't click "Yes" on the window that asks if extra folders should be removed.  This then caused other mods to think USI LS was still installed and caused fatal errors on startup.

I can understand the need for this window, but 99% of the time the answer should be Yes and it's a stumbling block for people that aren't familiar with what might have happened.  It's also an annoyance when installing/uninstalling mods frequently.

### Suggestion

Often, these extra folders are from generated `@thumbs` folders inside Parts directories.  It would be awesome if CKAN could just automatically remove those folders specifically, and then if there's no extra folders left to remove that extra window doesn't even need to be shown.  The other situation where this happens a lot is when mods write out a config file or user preferences.  Since there's no formal pattern for that, I'm not sure if CKAN can do anything about those.  And that's a case where someone might want to grab their user preferences before uninstalling too.

### Alternatives

Just remove the extra folders 100% of the time like CKAN used to do.  Or make an option for that (and ideally leave it enabled by default).

**Comment by HebaruSan** [comment]
> Just remove the extra folders 100% of the time like CKAN used to do

Just to clarify, CKAN never did this. It went from always leaving the folders regardless, to asking the user whether it's OK to delete them.

**Comment by HebaruSan** [comment]
Do you think the explanatory text could be improved? The checkboxes are checked by default because deleting is the most expected action, but maybe the current text doesn't get that point across as well as it could. I notice that the consequence about ModuleManager breaking everything is mentioned last, so maybe users get bored and stop reading before they get to that part? We could look into adding a blacklist of dirs that are treated as always-delete, but in the general case it's just not safe for CKAN to go auto-deleting files that it doesn't know the purpose of.

https://github.com/KSP-CKAN/CKAN/blob/858d71fc389910fb3ce357d70fa2d4ea0de82218/GUI/Controls/DeleteDirectories.resx#L120-L121

**Comment by HebaruSan** [comment]
@JonnyOThan, are there any other known folders like this that are auto-generated by the game at run time and could be deleted unconditionally? I have a dev branch that might be able to do this, and I'd like to make sure all the bases are covered.

**Comment by HebaruSan** [comment]
This is essentially a duplicate of #3484, but that was transformed into a ConsoleUI enhancement request (which still makes sense to add).
