### ISSUE TITLE
Auto-removal of MagiCore at upgrade of RP-1 caused RP-1 Express to be removed

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/CKAN#3911]
Writing this down as an issue so it doesn't get lost on a mod's discord.

[Starting here on the RO discord](https://discord.com/channels/319857228905447436/512556137380315139/1153203205157687346) two users encountered an issue with the latest metadata update to RP-1. Here is the setup:

* They installed RP-1 via the express install, which deps a large number of mods, including RP-1 itself
* We released a new version of RP-1 today
* Concurrent with that, I merged [HebaruSan's PR here](https://github.com/KSP-RO/RP-1/pull/2233) and then removed the dependency on Magicore [here](https://github.com/KSP-RO/RP-1/commit/b9f085575debb6be46dfeed3f722f3110ce0d046)
* Netkan bot picked up the new release using the new netkan
* A couple hours later, I also merged [Qazerowl's PR here](https://github.com/KSP-RO/RP-1/pull/2205)
* A little later [this PR](https://github.com/KSP-CKAN/CKAN-meta/pull/3206) was merged to CKAN-meta, directly touching the .ckans of the RP-0 mod (the Express Install has an any_of dep on RP-1 or RP-0). This resulted in the there being no choice and RP-1 being auto-selected when resolving the any_of on new installs.
* A couple hours after that, the discussion began in the support channel of the discord.

The symptoms:
* The users were given the option to upgrade RO, RSS, and RP-1.
* On doing so, they were prompted to uninstall some, but not all, of the mods the Express Install depends on, as part of (it appears) the express install itself uninstalling.

Manually reselecting the express install in CKAN and reapplying brought it and its dependencies back successfully. In the past, when the _express install's_ metadata changed, users were prompted to upgrade it and thus to uninstall _but then CKAN reinstalled_ its dependencies; this seems to be a different situation.

I diffed the previous RP-1 .ckan file with the initial RP-1 v2.12 .ckan file, and the only changes were (a) the addition of the recommend-suppression on the dependencies, and the removal of Magicore as a dependency. I also diffed the 2.12 ckans from before and after netkan bot inflated the result of the second PR to change the netkan, and it showed only the expected reorganization of the recommends and suggests (which should not have been relevant at all to the Express Install on CKAN 1.33.2). There have been no changes to the express install or the graphics sub-install .ckans in the last 3 weeks, so this seems entirely due to the RP-1 change.

As a band-aid I've reverted the netkan changes to RP-1, in the hope that will solve the problem for other users and they will not also end up with broken installs. But I remain mystified how changing the dependencies of a dependency causes a parent mod (the only manually-selected, rather than auto-installed, mod, to boot!) to be uninstalled.

**Comment by HebaruSan** [comment]
## What's happening

- Upgrading RP-1 triggers auto-removal of MagiCore, as it should
- GUI always calls `ModuleInstaller.UninstallList` before `ModuleInstaller.InstallList` before `ModuleInstaller.Upgrade`:
  https://github.com/KSP-CKAN/CKAN/blob/341adf88886d6d86626bca0073421cf576af5081/GUI/Main/MainInstall.cs#L169-L184
  ... so the first change that happens is removal of MagiCore
- The CKAN core code performing that removal doesn't know anything about the pending upgrade, it just knows it's been asked to remove MagiCore and that the currently installed version of RP-1 depends on MagiCore
- When that code removes MagiCore, it also removes all mods that depend on it, including the currently installed (old) version of RP-1. This is mildly surprising and not ideal, but not necessarily a serious problem yet.
- However, that dependency search is **transitive**, so everything depending on RP-1 is also  removed, including RP-1 Express! **This is when things definitely are going wrong**.
- The removal of RP-1 Express also triggers the automatic removal of any mods marked as auto-installed that only RP-1 Express depended on. This is desirable in a narrow sense, but in the context of removing a mod that we don't really want to remove, it just makes a bigger mess.
- When the Remove step finishes, essentially everything is uninstalled
- Since we're not installing anything, the InstallList step does nothing
- Finally the Upgrade step happens, which causes all the "Update" mods in the changeset to be reinstalled:
  ![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/04a875a5-6944-4cd2-b1f9-b400fde9698e)
  ... so RP-1, RealismOverhaul, RealFuels, and KSPCommunityFixes.
- But RP-1 Express was never in the changeset, so it doesn't get reinstalled!

## Workaround

I believe that if you uncheck the auto-installed checkbox for MagiCore before upgrading, the upgrade would work fine and would not uninstall all that stuff. Then you can re-check that checkbox again afterwards, and MagiCore would be queued for auto-removal safely.

I realize that's not something that can be communicated effectively to a large user base, and that the MagiCore dependency has been restored for now anyway; I'm only including it here to further illustrate the issue and provide another possible option for expert users dealing with this.

## Ideas for actual solutions

I'm thinking the auto-removal of MagiCore should be happening in the Upgrade step instead of the Remove step. We could do this by making `ModuleInstaller.Upgrade` check for auto-removable mods like `ModuleInstaller.UninstallList` already does, and then by filtering auto-removals out of the changeset GUI passes to `ModuleInstaller.UninstallList`.

**Comment by NathanKell** [comment]
Yep, that makes perfect sense in retrospect--the metadata upgrade triggers the uninstall of the auto, which triggers the uninstall of existing dependencies *before* the upgrade. I was thinking of it as the same single coherent step as installing, but of course it's not. I agree that for now I definitely need to leave the bandaid in place (I have....limited faith in any user-signaling method I could devise :D ).

For what it's worth I agree that the removal of auto-installs via metadata changes should occur in upgrade now that the processing of metadata changes is handled as an upgrade, but you actually know the code and I don't. :) And I don't know how involved that change would be, or how risky.

Thanks for looking into this!
