### ISSUE TITLE
[Bug]: BepInEx misses quirk for Proton/Wine/Linux (please give at least a warning)

### ISSUE THREAD

**Issue by kolAflash** [KSP-CKAN/CKAN#3916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Linux

### CKAN Version

v1.33.2

### Game Version

0.1.4.0

### Describe the bug

Many mods do not start when running the game via Proton / Wine on Linux (or probably on macOS too).

Many mods use [SpaceWarp](https://github.com/SpaceWarpDev/SpaceWarp) require BepInEx. But BepInEx needs a quirk running in Proton on Linux.

The quirk is pretty straightforward. But when installing via CKAN there's nothing giving a hint to configure that quirk. So a user might just wonder, why mods do not work.  
https://docs.bepinex.dev/articles/advanced/proton_wine.html

An easy solution would be if CKAN shows a message when running on Linux, advising the user to read that BepInEx page.

Ideally CKAN would apply that quirk automatically. But I guess that would be pretty complicated.

### Steps to reproduce

install a mod on Linux using Proton

**Comment by HebaruSan** [comment]
Hi, thanks for the report. KSP2 support is currently Windows-only, because the game is. We'll wade through Linux-related issues once the game runs there natively.

I think you can get support for BepInEx/SpaceWarp here:

https://forum.kerbalspaceprogram.com/topic/218490-space-warp-v142-for-ksp2-014/

**Comment by kolAflash** [comment]
KSP2 runs pretty well on Linux using Proton.  
https://www.protondb.com/app/954850
On the other hand it doesn't look like the developers are interested in native Linux support.  
_(really disappointing after the great Linux support by KSP1)_  

SpaceWarp and BepInEx already document everything needed to make them run in Proton.  
**So I'm just asking CKAN to show a small message, that users should read the SpaceWarp documentation when installing it.**  
No need to do any complicated tasks for CKAN.

That would be very kind! :-)

**Comment by HebaruSan** [comment]
I'm sorry to disappoint you. Please see my previous message; we're not trying to optimize the experience of running someone else's Windows application with a third party modding add-on _through a compatibility layer_. That's well into "at your own risk" territory, and anyone attempting it should be aware of that.

As an example of the reasons to leave this as-is, consider the impact on Windows users. There are a lot of them, and they'll be confused if they suddenly start getting a warning telling them they need a "quirk" or somesuch. They'll show up here to ask about it, repeatedly. Will **you** stick around long enough to explain, promptly and patiently, to each and every one of them what is going on? If not, consider how others might react to the idea of taking on that same support burden. (And before you respond that the message would only appear on Linux, remember that you're talking about running through a compatibility layer! We would not be able to rely on the platform checks, since they would tell us we were running in Windows if users chose to run CKAN in the same emulated environment as the game.)

As a second example, consider what will happen if/when the game is released natively for Linux. We would have to go back into the code and remove the warning, since it would no longer be relevant. That's a small change in itself, but it still creates a messy situation where we have a "this is needed until X happens" in the code rather than "this does the right thing, period". A similar point applies to when the official modding support is released and BepInEx goes away; again, we'd have to go back and clean this up to reflect the new state of affairs.

Third, it's so extremely specific and not even related to CKAN functionality. One specific (unsupported) platform (running a compatibility layer), one specific game (we would have to make sure this message never appeared for KSP1), one specific mod.

The folks distributing BepInEx have documented this, so it's out there to be found by users who can't wait for a native release. I think that's the most appropriate and least bad solution.
