### ISSUE TITLE
[Bug]: CKAN freezes while downloading "master.tar.gz"

### ISSUE THREAD

**Issue by DobrbobrYT** [KSP-CKAN/CKAN#3923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

v1.33.2

### Game Version

v1.22.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Clean install

### Describe the bug

The CKAN window is frosen, no inputs are working (other than "close" button) while it tries to install "master.tar.gz"

### Steps to reproduce

* Open CKAN
* Press yes to pop-out about checking for updates
* Lag

### Relevant log output

![image](https://github.com/KSP-CKAN/CKAN/assets/84640041/69bd8649-98a9-4e36-8481-8a8d3bd7756a)

**Comment by HebaruSan** [comment]
Hi @DobrbobrYT, sorry you're having problems. Based on previous reports, there's a good chance this is caused by crypto mining malware, check your hosts file (see #3802 and #3814).

If that's not it, the current dev build may give more information about why it can't connect, since it contains a fix for #3901:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe
