### ISSUE TITLE
"Max Game Version" column has some strange behavior

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#3973]
When I first launch CKAN on a KSP 1.12.3 instance with *no* additional game versions marked as compatible, BDB says that its max game version is 1.12.5:

![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/4524b870-18cc-4ffe-bde8-c30ef08957e8)

Then if I open the compatible game versions window, and hit accept *without making any changes*, BDB now says max game version is 1.8.0:

![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/9a18938f-d4b3-4e8f-974f-5a423e3f50aa)

If I check 1.12 and 1.11 as compatible, then BDB still says max version 1.8.0 but will let me install it:

![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/dee910a0-f67f-4c74-9775-8a638e923b32)

Note that BDB depends on SimpleAdjustableFairings which has a max version of 1.11.2.

Uhhh...further, it depends on DMModuleScienceAnimateGeneric which has a max version of 1.8 but is installable with only 1.12 and 1.11 checked?

![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/34d1e7d6-d260-4c4c-ad44-8b52d2ae7e07)

DMagic netkan: https://github.com/KSP-CKAN/NetKAN/blob/86c8ec832126fc6fa8583eb4a94f029fc3ea9783/NetKAN/DMagicScienceAnimate.netkan

**Comment by HebaruSan** [comment]
Yeah, there are some quirks here. The Versions tab can relieve some of the confusion...

- DMModuleScienceAnimateGeneric's _minimum_ game version is being put into the column:
  ![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/cc18efda-702a-4308-b591-2bc80d1d3141)
  I thought that was supposed to be 1.12.5 in the current release, so that'll need investigating.
- For BDB, 1.8.0 is the compatibility of the last version that used `ksp_version` before switching over to `ksp_version_min` and `ksp_version_max`, so apparently those are being treated more differently than they should be. Another thing to look into.
  ![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/bb68206a-395b-4483-a5fc-b44dcec4ffbf)

**Comment by HebaruSan** [comment]
> Then if I open the compatible game versions window, and hit accept _without making any changes_

This part is **REALLY** weird! `KerbalSpacePorgram.KnownVersions` is _reversing the order of all its elements_, even though it's a read-only `List` and only generated the first time we use it! The mod list before  reflects the correct ascending ordering, but then after you accept the compatibility popup, it is somehow flipped to descending. The majority of the weirdness observed here looks related to that.
