### ISSUE TITLE
Certificate errors on Debian (Ssl error:0900006e:PEM routines:OPENSSL_internal:NO_START_LINE)

### ISSUE THREAD

**Issue by bladela** [KSP-CKAN/CKAN#3981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Debian Linux

### CKAN Version

1.34.2

### Games

KSP 1

### Game Version

1.12.5.3190

### Describe the bug

Linux debian 6.5.0-5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1 (2023-11-29) x86_64 GNU/Linux

ckan is unable to sync the repository and fails with the error as in the object

i've already tried the wiki https://github-wiki-see.page/m/KSP-CKAN/CKAN/wiki/SSL-certificate-errors, with no results

### Steps to reproduce

open ckan

wait for the sync that immediately fails

### Relevant log output

2403 [Thread Pool Worker] WARN CKAN.Games.KerbalSpaceProgram.GameVersionProviders.KspBuildMap (null) - Could not retrieve latest build map from: https://raw.githubusercontent.com/KSP-CKAN/CKAN-meta/master/builds.json
2407 [Thread Pool Worker] WARN CKAN.Games.KerbalSpaceProgram.GameVersionProviders.KspBuildMap (null) - Could not refresh the build map from remote server

$ mono --version
Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-3.5 Wed Sep  6 18:25:01 UTC 2023)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

**Comment by HebaruSan** [comment]
Hi @bladela, thanks for the report. You've already seen this link on the forum, but in case any other Debian users land here, this wiki collects everything we know about cert errors on Linux:

- https://github.com/KSP-CKAN/CKAN/wiki/SSL-certificate-errors

I don't have a Debian system for testing, so I won't be able to investigate this for you. (But I do have an Ubuntu partition, Ubuntu VM, WSL, local Ubuntu Docker containers, and Ubuntu Docker containers on GitHub and AWS, all of which have been running CKAN without problems for a long time, so I'm satisfied that this problem isn't due to something CKAN is doing.) If any Debian users figure out this problem, please reply and consider updating the wiki with your discoveries. Thanks!
