### ISSUE TITLE
[Bug]: Failed downloads popup doesn't appear when downloads time out

### ISSUE THREAD

**Issue by CrypticPotatoo** [KSP-CKAN/CKAN#3983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

1.34.2

### Games

KSP 2

### Game Version

0.2.0

### Describe the bug

after selecting the mods I want downloaded, click apply and install. they begin to download some of them and then seem to stop at random points and not continue to download. I have restarted the process and left it for a few hours to no avail.

in the attached picture, it has been stuck on that for a few hours

![image_2023-12-31_062712594](https://github.com/KSP-CKAN/CKAN/assets/155258814/196c847d-e2d7-4ff1-bb33-0216e82a858c)

I have tried downloading straight from space dock with no issues at all. also tried reinstalling CKAN with no luck either.

would appreciate any pointers, cheers

### Steps to reproduce

Select Mods
Click Apply
Click Apply again
Watch downloads
Then downloading stops

**Comment by HebaruSan** [comment]
Thanks for the report. It looks like some downloads are failing (otherwise the next one wouldn't start, since we only download one file per host at a time). The log shows the final download starting and completing, but that's not happening.
The error messages are supposed to be reported in a popup after the last download succeeds or fails, and 


> I have tried downloading straight from space dock with no issues at all.

If you still have those ZIP files, you can import them into CKAN:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/f832016f-5067-4529-81cf-daa690c547c3)

Checking the bot's logging on Discord, SpaceDock seems to have had some intermittent connection timeouts recently (starting today around noon UTC and continuing for about 7 hours), which likely played a role in this. You might have better luck if you retry now.

This makes me think we should move forward with adding alternate GitHub downloads where available...

**Comment by CrypticPotatoo** [comment]
awesome as, cheers for the help and I did end up installing via import, ill try it again later on when I get some mods for KSP1 and can advise on how that goes

**Comment by CrypticPotatoo** [comment]
hey, it appears to be working now without any issues

**Comment by HebaruSan** [comment]
That's great to hear! 🎉 
Let's keep this open until we figure out why the error messages weren't appearing.

**Comment by HebaruSan** [comment]
Looking into something that at first appeared unrelated, I found a possible explanation:

1. The SpaceDock download times out
2. CKAN falls back to the implicit archive.org fallback URL for redistributable mods
3. The archive.org download _succeeds_
4. However, the code to map back from a URL to a module doesn't account for the archive.org fallback, which lives in `CkanModule.InternetArchiveDownload` instead of `CkanModule.download`:
  https://github.com/KSP-CKAN/CKAN/blob/cbfad766252d14429e8ff39d9ae82e44203580bc/Core/Net/NetAsyncModulesDownloader.cs#L141-L142
5. "No module found for completed URL" is printed to the warnings log and the download doesn't get moved into the cache

The problem so far is that in my testing, rather than freezing forever, this caused it to plow forward into trying to install modules, which failed because the files weren't in the cache to be unzipped. I don't yet know whether or how it might instead fail to complete the download phase...
