### ISSUE TITLE
[Feature]: Show a warning when CKAN detects CKAN files for an identifier selected or being downloaded as a dependency that have a newer spec than the CKAN version

### ISSUE THREAD

**Issue by cheese3660** [KSP-CKAN/CKAN#3994]
### Problem

I have been getting multiple reports of the latest version of my mod not being on CKAN, where the issue is that the user as an outdated version of CKAN, and CKAN does not notify them of this.
Example Report:
https://github.com/SpaceWarpDev/SpaceWarp/issues/281

### Suggestion

To prevent such reports, CKAN should when it detects that an identifier that is selected or is being selected as a dependency has a CKAN file of a newer spec than CKAN itself, and notify the user in some way that they should update CKAN to get the latest versions of said identifier/mod.

**Comment by HebaruSan** [comment]
When this happens, `UnsupportedKraken` is thrown by `CkanModule.FromJson` and handled here for freshly downloaded metadata:

https://github.com/KSP-CKAN/CKAN/blob/eaefca5df6c94ea2e04a4e390d74767acefb588b/Core/Repositories/RepositoryData.cs#L341-L352

There's also a JSON converter for when we load cached data from disk after saving it with a newer client:

- https://github.com/KSP-CKAN/CKAN/blob/eaefca5df6c94ea2e04a4e390d74767acefb588b/Core/Repositories/AvailableModule.cs#L67-L70
- https://github.com/KSP-CKAN/CKAN/blob/eaefca5df6c94ea2e04a4e390d74767acefb588b/Core/Converters/JsonLeakySortedDictionaryConverter.cs#L17-L36

In both cases unsupported modules are noted in the log and then skipped because the older client can't handle them. To alert the user, we would have to propagate a message out to GUI in some way, and it's not obvious to me how we could do that.

**Comment by HebaruSan** [comment]
Thinking about the code level interface for this, it might make sense to extend the `enum` that the repo update process returns:

https://github.com/KSP-CKAN/CKAN/blob/eaefca5df6c94ea2e04a4e390d74767acefb588b/Core/Repositories/RepositoryDataManager.cs#L112-L121

`RepositoryDataMaanger` could return a new `OutdatedClient` option if any unsupported modules are found, and GUI could use that as a signal to prompt the user to update their client, maybe with a yes/no dialog.
