### ISSUE TITLE
[Bug]: Only folders are showing when tryin to create a new instance.

### ISSUE THREAD

**Issue by gater308** [KSP-CKAN/CKAN#4029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

linux mint cinnamon

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

cloned folder and neither instance will display anything except for folders.

### Describe the bug

 there is no way to click on the build.txt file because it does not display. onlt folders display.
![Screenshot from 2024-02-14 12-02-28](https://github.com/KSP-CKAN/CKAN/assets/49091113/3bcd84d3-9c7e-4816-a5f7-5aecad4eb53c)

### Steps to reproduce

open ckan
click on new instance
navigate to game folder
nothing but folders are visible
check view hidden files 
still nothing but folders

**Comment by HebaruSan** [comment]
Copying forward my reply on #3823...

Hi @gater308, this functionality has changed since this discussion took place. CKAN no longer looks for `buildID.txt`.

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/1e83e6d0-72c7-4a97-8a2a-879d1f10a12c)

On Linux it would be `KSP.x86_64`. Does that file exist in that folder?

**Comment by HebaruSan** [comment]
User was trying to add Windows instance on Linux, so the game executable was missing.
