### ISSUE TITLE
Autoupdater should use a consistent filename for the exe so that it can be excluded from windows virus scanning

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#4040]
The autoupdater is often defeated by the overzealous windows virus scanner:
![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/3e63bbc0-ff95-437f-8c51-3c4e45d52495)

It's possible to set up exclusions to the windows defender based on filenames, but since the autoupdater seems to be downloading the exe to a random guid filename this isn't applicable.  If the autoupdater used a consistent name then it could be added to the exclusion list and this would work better.

**Comment by HebaruSan** [comment]
This is set here:

https://github.com/KSP-CKAN/CKAN/blob/d1387c33b399db2829dd2d757d7fb9011355f8b7/Core/AutoUpdate/CkanUpdate.cs#L21-L22

**Comment by HebaruSan** [comment]
FYI, I just tried setting up such an exclusion, and I'm not sure it actually works the way hoped for here:

1. Start → Settings
2. Update &amp; Security
3. Windows Security
4. Virus &amp; threat protection
5. Virus &amp; thread protection settings → Manage settings
6. Add an exclusion
7. Since no download is in progress, I entered: `%TEMP%\ckan.exe` for testing

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/4626ba9c-d70d-47fe-ac86-e70e6dec0bc9)

It looks like it only works for specific files that actually exist, not just a list of paths, which means you would have to navigate through these steps while CKAN was in the middle of downloading an auto-update, since as soon as it's done it will be moved to replace the running ckan.exe (if it isn't deleted by Defender). At my current typical network speeds this would give me about 0.2 seconds to react. I haven't tested that, but if such a file _changes_, I suspect it would no longer be considered the same file, and the exclusion would no longer apply.

**Comment by JonnyOThan** [comment]
Can't you just enter `ckan.exe` as the exclusion?

**Comment by HebaruSan** [comment]
> Can't you just enter `ckan.exe` as the exclusion?

Not successfully. "Add an exclusion" drops down this dropdown:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/efed2bda-94c8-4802-96d0-9af79838cc96)

Clicking "File" brings up a File Open popup, **not** an "enter a string" popup.

It says this:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/03386165-d837-4371-be6d-15f43651e58c)

> Ah, yeah, try doing "process" and entering ckan.exe:

But that would only work for a process, right? The message shown in the OP here is just for a _file_ that has not even been run yet, so it's not a process.

**Comment by JonnyOThan** [comment]
Ah right...hmm... docs are here: https://support.microsoft.com/en-us/topic/how-to-add-a-file-type-or-process-exclusion-to-windows-security-e524cbc2-3975-63c2-f9d1-7c2eb5331e53

The new exe is created by the old ckan.exe process right?

**Comment by HebaruSan** [comment]
1. Old exe downloads new ckan.exe and the updater exe to temp folder
2. Old exe runs the updater and passes it the path to the old and new ckan.exe
3. Old exe closes
4. Updater replaces ckan.exe with the new file
5. Updater runs the new ckan.exe and closes

I am guessing that the Defender message in the OP happens in step 1. Please add more details if there's reason to doubt that.

**Comment by JonnyOThan** [comment]
Is there a good way to test this process? I don't have older exes to run

**Comment by JonnyOThan** [comment]
oh heh there was a new dev build just put out.  So I already had ckan.exe added as a process exclusion, and I added AutoUpdate.exe this time, and it seems to have worked!

**Comment by HebaruSan** [comment]
Adding AutoUpdate.exe wouldn't do anything, since the file is never renamed to that. It's executed at its temp file location.

**Comment by HebaruSan** [comment]
I think this is what I eventually turned off to work around Defender's very high false positive rate:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/7a4028e6-d08c-4f2e-9990-06feb543f270)

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/7e1b596b-ff53-4fc1-82a2-8c20e2bef85b)

**Comment by JonnyOThan** [comment]
ok, so maybe the issue should be "ckan.exe should download the autoupdate.exe to a consistent filename."  e.g. temp\<guid>\ckan-autoupdate.exe.  Then you can add ckan-autoupdate.exe and ckan.exe as process exclusions and it should work?  maybe?

**Comment by JonnyOThan** [comment]
According to the docs, the file created by ckan.exe should be excluded from scanning.

**Comment by HebaruSan** [comment]
I'm thinking the best we can do here is to auto-launch a URL for a new wiki when the user clicks "Use dev builds" that explains Defender's false positives, how to turn off "reputation-based protection 🤮", and the attendant risks, then explains how to turn dev builds off again in the settings if the user isn't comfortable with that.
