### ISSUE TITLE
[Feature]: Allow using Proton instance for significantly improved speed over Linux native

### ISSUE THREAD

**Issue by Lyra-Vhess** [KSP-CKAN/CKAN#4041]
### Problem

In #4038 it was brought up that on Linux, CKAN won't find instances under Proton, but the issue was closed because there's a native version, however, the GE-Proton version runs _significantly_ faster than the native version, by up to 1.5x*, and I would vastly prefer to use it for heavy graphical modding. 

### Suggestion

Would detecting/using Proton instances be considered in light of this?

### Additional context

*When heavily modded, on one of my space stations I saw about 67-71 fps with GE-Proton 8-32 vs ~53 FPS with Linux Native. Mods included EVE Redux, Scatterer, SVE, Parallax, Planetshine, and TUFX

**Comment by permaloom** [comment]
This wouldn't just be for useful for speed, but for compatibility. Most graphical mods are developed for DirectX and may cause graphical bugs and/or degraded performance when using OpenGL. For example, the Parallax mod's surface object shadows are poorly rendered due to the way OpenGL renders shadows on top of geometry (according to the mod's config file).

**Comment by HebaruSan** [comment]
Yeah, I think we'll do this. It should be pretty easy. I just didn't know that some Linux users would choose the non-Linux build, but it makes sense for that to be an option since it does work.
