### ISSUE TITLE
[Feature]: Icons!

### ISSUE THREAD

**Issue by irasponsible** [KSP-CKAN/CKAN#4073]
G'day,

I made up some new icons for the CKAN Client, Console, and Command prompt. Is it worth baking these into .ico files at the right sizes for CKAN and making a pull request?

### Suggestion

| CLIENT | CONSOLE | CMD |
|--------|--------|--------|
| ![kerbal-space-program-ckan](https://github.com/KSP-CKAN/CKAN/assets/138816927/cfa45df1-cf53-4d4a-9afd-7af19d55407b) | ![kerbal-space-program-ckan-console](https://github.com/KSP-CKAN/CKAN/assets/138816927/b1ed7702-4d5b-4a62-884f-fcb594387f1d) | ![kerbal-space-program-ckan-cmdprompt](https://github.com/KSP-CKAN/CKAN/assets/138816927/ad49e194-a9f1-41e7-bda1-4ffbb3eb86e6) |

### Additional context

I used [these](https://www.reddit.com/r/KerbalSpaceProgram/comments/qzx51m/created_highres_renders_of_logo_on_ksp_website/) SVGs of the KSP logo on the [Official KSP website](https://www.kerbalspaceprogram.com/). If we had permission from SQUAD for the current iteration, they'd probably be alright with use of the updated logo? I'm happy to put in the legwork to contact Intercept/PD about it.

These icons are based on the [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) open-source icon theme. This is 64px, I've also done the other size `svg`s.

I also did some others up, which I plan to submit to Papirus at some point. Might even do up a full rainbow for people with too many KSP installs!

| KSP 1 | KSP 2 | KSP RSS |
|--------|--------|--------|
![ksp@64x64](https://github.com/KSP-CKAN/CKAN/assets/138816927/d20c6e70-2f18-4e5a-8271-f84fdefdeb68) |![kspdark@64x64](https://github.com/KSP-CKAN/CKAN/assets/138816927/d0bc0820-5281-441a-b36b-01b734d295da) |![ksprss@64x64](https://github.com/KSP-CKAN/CKAN/assets/138816927/28131be9-72ff-463b-885d-3ebb4bfaf759)

**Comment by HebaruSan** [comment]
Hi, really neat work!

I have a couple of points of feedback to bring up:

- The current/old icon says "CKAN", and these don't. I think that'd be an important way to differentiate it from the KSP1 and/or KSP2 icons. If these were on my taskbar, I don't think I'd be able to tell what to click to launch CKAN vs the games.
- I'm skeptical about your hope that years-ago permission to use a particular icon applies to future icons. I'm also a bit nervous about asking, since the franchise has changed hands since then and we don't know whether the new owners would have the same attitude or even remember their predecessors' decisions. I wouldn't want an email forwarded to their (new) legal team to trigger a cease and desist letter and have to stop using even the old icon that we have now.
  - Then again, maybe a completely new, completely original icon would be best, since we've begun branching out into supporting multiple games. A KSP-related icon would seem out of place if we eventually add support for games outside that franchise.
- How exactly are you imagining the CmdLine and ConsoleUI ones would be used? All three UIs live inside the same .exe file, which can only have one icon. We could probably set them up to show up in the system menus in Ubuntu/Fedora, since those are separate `.desktop` files that can reference whatever standalone icon files they want, but other than that I would not know where to put them.

**Comment by HebaruSan** [comment]
Looking at that link for Papirus, could we make it possible for icon libraries like that to set their own icons for CKAN? I haven't looked at the spec for this recently, but I would guess that could be done by changing the `Icon` property in the `.desktop` file from a path to a generic symbol?

```desktop
Icon=/usr/share/icons/ckan.ico
```

&rArr;

```desktop
Icon=ckan
```

If that worked, then we might be able to offload some of the "risk" of a derivative icon to such projects. I.e., if _Papirus_ gets a C&amp;D letter, that wouldn't affect us.

**Comment by irasponsible** [comment]
> The current/old icon says "CKAN", and these don't. I think that'd be an important way to differentiate it from the KSP1 and/or KSP2 icons. If these were on my taskbar, I don't think I'd be able to tell what to click to launch CKAN vs the games.

I'll admit, this started out as me wanting a couple of different icons for different KSP1 instances. CKAN's default icon didn't show up very well at 24x24px so I was using a generic one.
In my head the white/red vs red/white was enough of a distinction, but I was the one who made them, so of course I thought so!

I'll try and come up with something more CKAN specific, maybe just the "rocket plume lens flare" *shape* and "CKAN", which would pay some homage to the original but still be generic for if CKAN expands. Also neatly nips licencing questions in the bud.

> How exactly are you imagining the CmdLine and ConsoleUI ones would be used? All three UIs live inside the same .exe file, which can only have one icon. We could probably set them up to show up in the system menus in Ubuntu/Fedora, since those are separate `.desktop` files that can reference whatever standalone icon files they want, but other than that I would not know where to put them.

I'm using Debian 12 with KDE, where they already show up as three separate options - I assumed that was how it showed up on Windows! I think since CKAN comes with three `.desktop`s, it'll show three menu entries. It was the same on Linux Mint.

> Looking at that link for Papirus, could we make it possible for icon libraries like that to set their own icons for CKAN?

I'm happy to do the digging to see how to set it up properly! It's also possible for a user to just set them manually (KDE and Mint have menu editors, or can just edit the `.desktop` in a text editor.)

**Comment by irasponsible** [comment]
Here's what I could come up with.

| Client | Client (alt) | Console | Command |
|--------|--------|--------|--------|
|![new-ckan-red@64x64](https://github.com/KSP-CKAN/CKAN/assets/138816927/180ce3ba-a11a-43d3-b23e-306ac4b92041)|![new-ckan-white@64x64](https://github.com/KSP-CKAN/CKAN/assets/138816927/0d519c14-d781-4700-b1b6-6b98620a378b)|![new-ckan-console@64x64](https://github.com/KSP-CKAN/CKAN/assets/138816927/113ba32f-17ea-4661-b9f5-846aa854919e)|![new-ckan-cmdprompt@64x64](https://github.com/KSP-CKAN/CKAN/assets/138816927/43d01cb1-75be-4761-bd07-b09921ae58c9)| 

|Wide | Wide (alt)|
|-|-|
|![new-ckan-red-wide@128x64](https://github.com/KSP-CKAN/CKAN/assets/138816927/dd04baf6-430c-40fa-bbfe-80d5466d29b6)|![new-ckan-white-wide@128x64](https://github.com/KSP-CKAN/CKAN/assets/138816927/3838c6ee-432b-4420-b725-1ae34e920f84)|

Tried to keep the current 'motif' as much as I could. Font is "[Nasalization](https://typodermicfonts.com/nasalization/)" by Typodermic, which has a [licence](https://typodermicfonts.com/license/) that allows this use.
