### ISSUE TITLE
[Bug]: max game version column can show an incorrect value when a mod uses major.minor ksp_max_version

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#4141]
I suspect this was caused by the fix for this bug:  https://github.com/KSP-CKAN/CKAN/issues/3973

As reported here: https://discord.com/channels/601452466017665040/601456752906469388/1269997308687417346

StockWaterfallEffect's netkan contains this:

```
ksp_version_min: '1.11'
ksp_version_max: '1.12'
```

According to the CKAN spec, this should allow any 1.11.x or 1.12.x version.  But for some reason the Max Game Version column shows 1.12.2:

![image](https://github.com/user-attachments/assets/a62df0d1-35d3-497a-a084-756374fd7be2)

My hunch is that this bug occurs when OLDER versions of the mod had an explicit patch version in their max_ksp_version metadata (1.12.2 in this case).  If the max game version column is doing a naive lexicographical sort (or even a version-based sort) on the ksp_max_version field for each version of the mod, then it will come up with 1.12.2 as the maximum value, even though 1.12 is actually a higher compatibility value.  Version specifiers that don't have a patch version need to be handled differently.

**Comment by HebaruSan** [comment]
Thanks. I think `.Max()` isn't working the way I expected with `GameVersion`s:

https://github.com/KSP-CKAN/CKAN/blob/a37eca5e59ae44218518d8ef37860176819b3941/Core/Registry/Registry.cs#L668-L675

... because `GameVersion.CompareTo` lacks special handling for `Undefined` values, which end up being treated as less than everything else:

https://github.com/KSP-CKAN/CKAN/blob/a37eca5e59ae44218518d8ef37860176819b3941/Core/Versioning/GameVersion.cs#L737-L770

https://github.com/KSP-CKAN/CKAN/blob/a37eca5e59ae44218518d8ef37860176819b3941/Core/Versioning/GameVersion.cs#L23

**Comment by HebaruSan** [comment]
Hmm, no, that doesn't make sense; the whole point of that logic was to replace wildcard versions like `1.12` with the equivalent real versions like `1.12.5`, so `.Max()` should already be working fine. Must be something else...

**Comment by JonnyOThan** [comment]
I think you need a custom comparison function.  For purposes of ksp_max_version, a missing patch value should be compared via < (next minor version).  I think ksp_min_version can stay as it is?

**Comment by HebaruSan** [comment]
Nah, see previous comment.

**Comment by JonnyOThan** [comment]
Er, right?  You can’t use GameVersion.CompareTo, you need to pass in a different comparison function that is aware of this

**Comment by HebaruSan** [comment]
No, but not worth taking time away from debugging to explain it.
