### ISSUE TITLE
ZIP file for Waterfall corrupted after being validated and added to cache

### ISSUE THREAD

**Issue by avro-1** [KSP-CKAN/CKAN#4226]
### Is there an existing issue for this?

- [X] I have checked the existing issues for an existing issue. I even actually looked at the ones that are pinned to the top!

### Operating System

windows 10

### CKAN Version

V1.35 (the latest my install found)

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

no, i did not make any manual changes, i do all modding via CKAN

### Describe the bug

all mods fail to install, i attempted everything from removing all CKAN files from my KSP install to even just restarting it, no dice, nothing worked

### Steps to reproduce

i am unsure, my OS locked up after attempting to run KSP and then i had to restart via the power button on my case, now neither CKAN or KSP are working right, with KSP hanging on "loading part upgrades"

### Relevant log output

this is what CKAN said when i attempted a mod installed, note that my wifi is working fine so cannot cause the issue:

```
About to install:

 * Module Manager 4.2.3 (cached)
 * Waterfall Core 0.10.1 (cached)
Installing ModuleManager 4.2.3...
Successfully installed ModuleManager 4.2.3
Cannot find central directory
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose
```

**Comment by avro-1** [comment]
good news, managed to pin it to the client i was using, installed a new one and the issue went away like children in the cold, issue resolved

**Comment by avro-1** [comment]
i was wrong, worked for four mods, this is a roller coaster but i'll keep this open until i managed to install my mods

**Comment by HebaruSan** [comment]
Hi @avro-1, "Cannot find central directory" means something is wrong with one of the ZIP files you were trying to install. Since you listed Waterfall and ModuleManager as being installed together, and ModuleManager was successful, by process of elimination that would indicate the problem is with Waterfall. Since Waterfall is listed as "(cached)", and CKAN validates ZIP files before adding them to the cache, this suggests that the file was corrupted after that.

You can right click that mod and choose "Purge from cache" to delete the presumably corrupted ZIP and force it to be re-downloaded:

![image](https://github.com/user-attachments/assets/96afbfb3-d663-4e2f-b28a-573ef3822e48)

**Comment by avro-1** [comment]
hi, im gonna give that a shot now, thanks for the help mate

**Comment by avro-1** [comment]
![image](https://github.com/user-attachments/assets/05526d52-5669-4700-b05e-8ae357afbb31)
hi, reporting back here, the fix either didn't work because im dumb, or because of other mods that need to be purged, gonna fully purge then reinstall my mods, wish me luck

**Comment by avro-1** [comment]
annoying update, still downloading, good update, still downloading

**Comment by avro-1** [comment]
welp, couldn't finish downloading because i killed the drive, currently trying to fix it, but thanks for the help anyway
