### ISSUE TITLE
Add support for localization

### ISSUE THREAD

**Issue by CodingWoes** [KSP-CKAN/CKAN#433]
Continuing the discussion from IRC. Let's come up with a standard approach to add localization support to CKAN.

First step would be to come up with a framework which we could then refactor into existing functionality. Then, for additional features, we could settle with providing en_US localizations until we have time/resources to add in languages.

**Comment by plague006** [comment]
This would be "neat" but I think if anyone had any impetus to do it, this issue would have at least had 1 comment in 15 months. I think if/when anyone tackles this, it won't be because it's in the enhancement queue: it'll be because they care enough.

As an aside, CKAN is a tool for a game that, itself, doesn't have multi-language support built in.

**Comment by ayan4m1** [comment]
I support closing this unless it comes with a PR. The time and effort overhead involved in even getting the English translations working would be monumental, we do not have any translators, etc etc.

**Comment by politas** [comment]
I'm in agreement
