### ISSUE TITLE
Add usage stats

### ISSUE THREAD

**Issue by tips48** [KSP-CKAN/CKAN#481]
Now that we have ksp-ckan.org, it would be great if we could add some sort of usage stats.  
For example: 
How many people use CKAN?
What mods are most popular?

This would have to have a clear option to opt-out, such as a dialog that pops up the first time you open the GUI.

**Comment by pjf** [comment]
Yay! Six month old tickets! :)

We have abut 14,000 users. You can tell by looking at [the github release API](https://api.github.com/repos/KSP-CKAN/CKAN/releases).

I'm really happy with us never calling home or otherwise trying to track downloads of individual mods. Since we always try the primary download link first, mod authors are getting their stats through their hosting providers, whatever they may be.

Closing this out, but as always feel free to re-open if you think I'm doing this in error.

**Comment by jtac** [comment]
Being able to sort by popularity and type would be a nice median way for new users to locate mods they aren't familiar with but others have found to be useful, this wouldn't be as "controversial" as reporting pure stats would be. Perhaps even an opt-in review system where you could leave comments and review a mod, enabling sorting by reputation.
