### ISSUE TITLE
Spec extension proposal: "downloads"

### ISSUE THREAD

**Issue by AlexanderDzhoganov** [KSP-CKAN/CKAN#487]
I propose that we implement an extension called 'downloads'

```
"downloads" : {
            "description" : "A list of alternative URLs where a mod can be downloaded by tools",
            "type"        : "array",
             "items"       : { "type" : "string" },
             "format"      : "uri"
}
```

For now this will mostly allow mirorred ckan metadata to continue to function if the mirror goes down among other things.

**Comment by pjf** [comment]
#935, while not superseding this, may certainly remove much of the need. :)

**Comment by TeddyDD** [comment]
> That would be nice, but also a barrier to humans writing the metadata themselves.

This is simple to solve. We just need to add checksum calculation tool to netkan.exe (something like ```netkan.exe -checksum file.zip```
Also Linux users already have sha1sum etc.

**Comment by dbent** [comment]
May as well re-open this as it's getting particularly relevant.

**Comment by dbent** [comment]
My thoughts:

- I support making `download` a string or array of string. (A string would obviously be treated as an array of string with a single element)
- I support adding optional checksums and preferentially caching by the checksum. If there is no checksum, we'll cache by a hash of each download URL. This is not perfectly efficient since we could download duplicate copies of mods when we already have a local copy, **but** we should be striving to make checksums *non-optional*, so we can eventually rely only on that. I'll give additional thoughts in #62

**Comment by dbent** [comment]
Also, deprecate `$kref` so that a single mod can use multiple sources to automatically generate multiple download URLs.

Right now we have `x_netkan_jenkins` and will soon have `x_netkan_github`. The mere presence of these properties in a `.netkan` should indicate we want to use these sources.

For example:
```json
{
    "x_netkan_jenkins": {
        "url": "https://ksp.sarbian.com/jenkins/job/ModuleManager/"
    },
    "x_netkan_github": {
        "user": "sarbian",
        "repo": "ModuleManager"
    }
}
```

Would generate multiple download URLs, one from Jenkins and one from GitHub. This would be trivial to do with how NetKAN's transformers work.

**Comment by TeddyDD** [comment]
@dbent :+1:
