### ISSUE TITLE
Spec extension proposal: "last_updated"

### ISSUE THREAD

**Issue by AlexanderDzhoganov** [KSP-CKAN/CKAN#488]
I propose that we implement an extension called 'last_updated '
```
"x_last_updated" : {
            "description" : "A time-stamp representing the last time the 'download' url has been updated",
            "type"        : "string",
            "format"      : "date-time"
}
```
This could be used for various things like sorting by last update in the GUI.

**Comment by bstpierr** [comment]
This would be very useful. Especially when new versions are released, it makes it easier to find out if a mod only uses the min_version or is actually updated for the new version.

**Comment by pjf** [comment]
Since anything starting with `x_` is formally defined as something the spec (and hence the core) will never touch, there's no reason to go through any sort of formal process here! I'd be totally happy with this being added to the output of `netkan.exe`, but with the understanding that as an `x_` field nothing *should* depend upon it.

If this were part of the spec, then yes, a `last_updated` makes sense for automatically generated documents. Although the GUI and cmdline seem to be doing a pretty good job of showing "updated" mods at the moment just by comparing lists they had before and after repo updates.

**Comment by HebaruSan** [comment]
`release_date` was added in #3059.
