### ISSUE TITLE
Please cache downloads outside of the game directory

### ISSUE THREAD

**Issue by rafl** [KSP-CKAN/CKAN#584]
Currently almost all of CKAN's data, including downloaded mods, is stored within the `CKAN` directory within a KSP installation. As a consequence, mods previously downloaded and cached in one KSP installation's `CKAN` directory will be re-downloaded when trying to install the same mods into another KSP installation.

Especially with larger packages, such as the high resolution real solar system textures that weight in at something like 2GB, this gets annoying quickly, especially over slow downlinks.

Rather than caching downloads within KSP installations, please cache them in a more global location such as the user's home directory. On linux systems `$XDG_CACHE_DIR/ckan` would seem like a reasonable place.

**Comment by pjf** [comment]
re-opening after the re-merge

**Comment by 7ranceaddic7** [comment]
Would it be possible to get the cache directory to be user specified?  Currently I have a 128GB SSD partitioned for SxS Linux/Windows/Home.  I have multiple SATA drives, one which I have specified a directory for my Software Archive.

I don't need the speed of the SSD for CKAN operations and the .../CKAN/downloads/ directory chews up a sizeable portion of the Home partition that could otherwise be put to better use.

**Comment by plague006** [comment]
@7ranceaddic7 the workaround I use (windows box) is creating a symlink from the cache folder on my SSD to one on my HDD. Overall being able to choose a cache directory would be ideal, but all I can offer is a workaround. =)

**Comment by 7ranceaddic7** [comment]
@plague006 TY! TY! TY! Workaround or not is works perfectly.

**Comment by SilverlightPony** [comment]
If a good reason exists for one program to use _another_ program's installation directory as a data "warehouse"/cache, I've never encountered it.  For something like this (in Windows), IMHO the only reasonable place to store downloaded mods is in a subfolder of the same directory CKAN.exe is in—perhaps with further subfolders denoting KSP version compatibility.  e.g.:

Some_Folder_Somewhere\
- CKAN.exe
- CKAN data\
- - installed-default.ckan
- - registry.json
- - GUIConfig.xml
- - Plugins\
- - Downloads\
- - - 1.0.5\
- - - 1.1.2\
- - - 1.1.3\

Please, please, please get CKAN's cache out of the KSP installation directory.  It has no business being there.

**Comment by politas** [comment]
I think the version compatibility subfolders are a bad idea. If we want to use our stored hashed to recognise user-downloaded mods, we want to have a simple location for users to place them. Also, given the min/max provisions, you would quickly gain a plethora of confusing locations 

. 0.90-1.0.4
. 1.0.1-1.0.2
. 1.0.2
. 1.0.5-1.0.0
. 1.0.5-1.1
. 1.0.5-1.1.2

CKAN would need to ignore this folder structure and we would need to move files around every time metadata changes, which could make things very confusing. I think a single defined location is best.

**Comment by SilverlightPony** [comment]
Single location is fine, as long as it's not inside a KSP installation directory.

**Comment by politas** [comment]
Agreed. Tricky to work out a default in a cross-platform app, unfortunately. Especially when both CLI and GUI need to allow a way to check and change it. I would have thought something like C:/Users/username/(Program Data?)/CKAN/downloads for windows, and ~/.local/CKAN/downloads for *x

**Comment by SilverlightPony** [comment]
I prefer not to rely on system variables like %programdata% if I can help it.  Anything that is not user-specific (and cached mod ZIP files _aren't_ user-specific) should go in a subfolder of the program's own installation directory; the user should have means to choose whether user-specific info (in this case, stuff like KSP installation paths and current installed mods, among other bits of info) are stored in the program's installation directory as well, or in %appdata% (or %localappdata%; I'm still not sure what functional difference there is between the two).

**Comment by leftler** [comment]
@SilverlightPony normally installation directories are read only by non privileged users (administrators/super users), it is not a safe assumption that a installation path will be writeable.

The difference between %appdata% and %localappdata% is when you are in a domain files located in %appdata% will be copied to the domain controller on log off and copied to the computer when you log on, this lets files travel with you when you log off one machine then log on to another. files located in %localappdata% will always stay on the machine it was created on.

**Comment by politas** [comment]
I think the best thing initially, is to bypass the arguments about the ideal default location and implement a way for users to set the cache directory. Once that's in place, we can think about moving the default from where users currently expect to find it.

**Comment by linuxgurugamer** [comment]
I would suggest that when this is FINALLY implemented, that it default to the current behaviour.  Give the users the ability to do the following:

1.  At first time startup, select cache directory
2.  In settings give ability to select the directory.

I honestly don't understand why it's taking so long to do something so simple.  You already have dialogs to select game location, so pretty much everything you need is already implemented.

While I am not a contributer to this project  (yes), I might consider it to get this feature

**Comment by DinCahill** [comment]
Everyone loves a good [bikeshed](http://bikeshed.com/)!

**Comment by linuxgurugamer** [comment]
Ok, so, are you saying that I responded too fast (I did read the entire thread, and actually opened an issue yesterday on this), or that I should actually do something about it?
Not sure if you were being sarcastic or serious

**Comment by DinCahill** [comment]
Lol, it's a joke. We're busy discussing minutiae rather than doing anything. @politas has tried to end it, by getting us to build the bikeshed now, and then we can settle on what colour to paint it later.

**Comment by linuxgurugamer** [comment]
Ok, but still, has there been any action?  If not, then maybe tomorrow I'll take a look at setting up a local CKAN dev repo and seeing if I could do it myself

**Comment by linuxgurugamer** [comment]
So, this is what I'm planning on doing, seems to cover everything listed above:

1.  Add line to settings window showing path of cache directory
2.  Add 2 buttons to the right of the line to select cache directory, or use the default
3.  Add cache directory path to saved settings
4.  Update KSP.cs  (DownloadCacheDir) to use the selected path

Since I'm new to this code, please feel free to tell me what I missed :-)
But hopefully this will get it working, and specifics can be updated later if needed

**Comment by DinCahill** [comment]
If anyone's started working on this privately, please say so!

Your suggestion is in line with what @politas said, so if you want to work on it, @linuxgurugamer, go for it :smile:. Then we can review some actual code in a PR.

**Comment by politas** [comment]
Need to make sure the directory choice is saved in the registry with the set of KSP installs, rather than the CKAN appearance settings that are saved per KSP install (to be honest, I'm not sure why we do that!), but yes, that's about the gist of it. This was on my personal list of coding projects, but behind a couple of other things. Feel free to have a stab at it. Have a quick read of the Developer guidelines in the CKAN wiki; there's some useful stuff in there.

**Comment by politas** [comment]
#1788, #1847 and #960 are all related (or can be related to this) This particular change (Allowing users to select a cache directory) is probably the first step. Second step is to get CKAN to recognise files in the cache directory by their hashes rather than their filenames, at which stage we will no longer care about what we call the files, and we can think about file naming under #1637.

**Comment by techman83** [comment]
@politas as far as I know it already looks for just the hashes. I recall looking at it when working on the NetKAN code.

**Comment by politas** [comment]
It might test the cached files against the hash, but it doesn't find them that way. If you rename an item in the cache, it will re-download.
