### ISSUE TITLE
Installed but removed-from-CKAN mods are stuck in limbo

### ISSUE THREAD

**Issue by illusori** [KSP-CKAN/CKAN#746]
There seems to be an issue where if you install a mod via CKAN and then it is later removed from CKAN, you're no-longer able to uninstall it from the GUI (may just be a GUI issue, I don't know enough to say).

You can manually delete the files from your GameData directory, which is fine if that's all you need to do... but CKAN still believes you have it installed, and if other mods then have conflicts with the removed mod, you're stuck in a situation where you're unable to resolve the conflict.

An example of this would be the Active Texture Management mod, which has had its original entry in CKAN removed, but the replacement family of mods still flag themselves as conflicting with the original: you can't uninstall the original because it "doesn't exist", but you also can't install the replacements because you've got an entry somewhere saying there's a conflict. :D

Some manner of "Discontinued" filter for mods, that allows you to see "installed-but-not-on-ckan-any-more" mods and uninstall them would be a good general-case fix I imagine.

**Comment by hakan42** [comment]
Could you please try to run "ckan repair"? And before that, could you locate your registry.json (usually in your KSP folder, in "CKAN") so you can send it to us for testing if "repair" does not work?

**Comment by illusori** [comment]
"ckan repair" didn't fix the issue, and didn't appear to make any changes to registry.json either. I've pasted a pre-repair copy at https://gist.github.com/illusori/eca3ade23772354e9f9f. :)

**Comment by illusori** [comment]
Running `ckan remove "ActiveTextureManagement-Aggressive"` in the command-line uninstalled the module successfully and allowed install of the new modules, so I guess this is a GUI issue that it doesn't allow you to see mods that have been removed from CKAN, rather than any sort of underlying bug in CKAN itself.

**Comment by Dazpoet** [comment]
Relevant to this issue is probably https://github.com/KSP-CKAN/CKAN-GUI/issues/45

As someone who often try hacked together .ckan files for my own purposes I've noticed that the GUI seems to keep any unofficial mods added via commandline until the first refresh is ran from within the gui.

A reproduction cycle that worked for me locally is;
- Add a mod that's not in the repository
- Open GUI and see that the mod is there
- Run a refresh using the GUI button
- Try to locate the mod in the GUI list and see it's no longer there

The only way to remove the mod added is now via commandline.
