### ISSUE TITLE
can't get ckan to open. noob here, help greatly appreciated. OSX

### ISSUE THREAD

**Issue by liamjcassidy** [KSP-CKAN/CKAN#774]
I'm using yosemite and have downloaded the latest version of mono 3.12.0 and opening the ckan.exe just makes OS X say that it can't open windows applications. Any ideas where i'm going wrong? Thanks in advance.

**Comment by mlr84** [comment]
.exe is typically only compatible with Windows or Linux running Wine. Please follow instructions here: https://github.com/KSP-CKAN/CKAN-support/wiki/Installing-CKAN-on-OSX

I don't have my mac set up right now, but from the instructions you might need to launch the application via terminal (the run "mono ckan.exe). 
Maybe some one else can chime in  on that part.

**Comment by alampros** [comment]
Yeah, it's a little tricky on OS X. Follow the instructions that @mlr84 linked, then open up terminal.app (/Applications/Utilities/Terminal.app). Assuming you downloaded the latest `ckan.exe` and it's in your downloads directory, entering

```sh
mono ~/Downloads/ckan.exe
```
Should start the GUI.

I've found there sometimes mono hangs when trying to open the GUI windowing kit for no apparent reason (hopefully the new mono framework build will fix this). You might want to try running `mono ~/Downloads/ckan.exe help` to see if the non-gui CLI help text is printed.

If you want to get fancy, you can add an alias to your bash profile to make it easier.
```sh
# I keep my binaries in ~/local/bin
alias ckan = "mono ~/local/bin/ckan.exe"
# or you can keep it in the downloads dir
alias ckan = "mono ~/Downloads/ckan.exe"
```
That will let you just type `ckan [cmd]` instead of invoking mono with the explicitly referenced lib.

**Comment by liamjcassidy** [comment]
Hi guys thanks for the quick replies and helpful info. I had got to the stage to load the GUI before and it had indeed started the mono window, but it wasn't responding. I then tried the CLI help text and that worked a charm! I see this question asked by mac users on reddit so hopefully i'll now be able to help out anyone on mac who has the same difficulty with terminal as me. Thanks again!

**Comment by alampros** [comment]
KSP-CKAN/CKAN-GUI#52 might be of interest to you. I added a build script to create a standard OS X application bundle.

Would you mind downloading my [test build from dropbox](https://www.dropbox.com/s/84j6nwtmjkka3qy/CKAN.app.zip?dl=0) and letting me know if it works on your machine?
