### ISSUE TITLE
Torrent downloads

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN#783]
I was wondering how hard would it be to add torrent support within ckan.
The idea is to ease the bandwidth and infrastructure costs from community hosting like KerbalStuff.
It also provides an easy and painless solution to setting up multiple mirrors.
The download field could be extended to accept a magnet link.

I wonder how stupid this idea really is.

**Comment by erendrake** [comment]
I dont think its stupid. it would be kinda cool to give people the ability to quickly host a mirror

**Comment by Ippo343** [comment]
Update: it appears that Mono has an X11/MIT torrent libray we could use.
I will give it a more in-depth look as soon as I can :)

**Comment by TeddyDD** [comment]
That would be really awesome!

**Comment by pjf** [comment]
The idea is sane. However #935 is achievable at the moment, especially since we have infrastructure funding, so I'd suggest we head towards that first.

I'm working on getting  our tickets under control, so I'm closing this out with the expectation that #935 would solve most or all of our bandwidth and throttling issues. However please do feel free to re-open if you feel we should be keeping this around for the future. :)
