### ISSUE TITLE
Isn't a wiki supposed to be packed with info?

### ISSUE THREAD

**Issue by Shaggygoblin** [KSP-CKAN/CKAN#790]
A user...
fracking awesome feature! Just wish the wiki was more wiki and had a 'use guide' other than "install and hit refresh and add/remove mods with cheeck boxes."
CKAN, as it is is very unfriendly to users who know nothin' more than "click the .exe to run"
Maybe, a 'step 1, 2, 3...' tut on the wiki to making the metapackage mentioned in Issue #761(Closed)?

**Comment by pjf** [comment]
I might be missing something here, but... it's a *wiki*; the whole point is that *anyone* can edit it. Rather than saying "the wiki should contain X", you can instead fulfil that wish directly.

If it's not giving you edit permission, then that's something we need to fix, but otherwise yes, I agree with you entirely. Please make it so.

**Comment by Shaggygoblin** [comment]
I agree with you on all points.
I do need to point out that, my statement "A User..." was a literal description of me.
I would need to know how to do what I was going to add to the wiki...
and there is no readily available (read: 5 quick searches results = 0 relevant) info on the subject.

**Comment by AlexanderDzhoganov** [comment]
This is a loaded question (assumes wiki doesn't already contain enough info which may or may not be correct) and not really something to work towards, so closing it as irrelevant. Please don't spam the queue with questions like this, there are real issues to solve.
