### ISSUE TITLE
CKAN-Cmdline: Extended upgrade comand

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#809]
Currently the CKAN core allows for some really complex operations using the `ModuleInstaller.AddRemove()` call, which adds and/or removes a number of mods in a single transaction, but none of the CKAN clients utilise this directly.

I'd like to expose this to the user by expanding the `ckan.exe upgrade` syntax. In particular:

* A mod starting with a `-` will be added to the remove list.
* A mod starting with a `+` will be added to the install list.
* A mod without leading decoration will be added to both lists (which we already do).

This means a user could write `ckan.exe upgrade RealSolarSystem +RSS-Core` which would both upgrade RealSolarSystem, *and* install `RSS-Core` as a single transaction. It would be the same as writing `ckan.exe upgrade -RealSolarSystem +RealSolarSystem +RSS-Core`.

Note that this would also support the existing version specification syntax, so one could write `ckan.exe upgrade RealSolarSystem=v1.337 +RSS-Core=v9.001` which would upgrade/downgrade RealSolarSystem to v1.337, and install v9.001 of RSS-Core.

Also note that the spec disallows plus characters in identifiers, and states that identifiers *must* start with a letter, so we'll never see mods starting with plus or minus characters.

No changes to the core should be needed for this. The code is already there and being used (most operations call `AddRemove()` to do the final work).

Tagging @Dazpoet in particular here for opinions.

**Comment by Dazpoet** [comment]
This sounds very helpful for advanced users and I like it, esspecially since it is easy to add and give more ways to help users affected by mods changing dependencies.

Would it be possible down the road to somehow force certain upgrade commands to be ran upon upgrade of a mod? Currently we see a flourishing amount of contractpacks and some of them need additional dependencies as they grow. Maybe something like an upgrade stanza defining how a certain mod should be upgraded to the new version? I have no Idea how that stanza would look to make sense and work at this time but I do think it could be useful. The currently most obvoius application for us is the RSS split but mods like ODFC, SETI and NehemiaCommon have all had this problem earlier and more are sure to follow.

**Comment by pjf** [comment]
Closing this for now. Our `upgrade` command is pretty smart, and we can always re-visit this if we find it's not smart enough.
