### ISSUE TITLE
GUI improvements proposal

### ISSUE THREAD

**Issue by JustinKerbice** [KSP-CKAN/CKAN#813]
I think the dependencies & co could be improved for the best, instead of having a dropdown list for each (as there is not so much, if there is any, mod with a seriously big list of depends/recommends/suggests at all), a tree view will be a lot more better with something like:

depends
+-modA
+-modB
suggest
+-modC

+ two button: collapse/expand all

And, another one big addition would be a selected picture (+ maybe a link to an album + a small HTML parser/embedded browser, but that's another story) of the mod when selected. This pic should be of a given fixed size and encoded in Base64, for example, inside the meta data.
Mostly because text is not always enough to have an idea of a mod and a picture is always welcome.

**Comment by Dazpoet** [comment]
Can't say I have much to say about tree vs drop down since I always check all those things in the metadata rather than in the client.

I really like the picture idea and found that it has even been proposed before [here](https://github.com/KSP-CKAN/CKAN/issues/725). I agree that sometimes a picture would probably be a good compliment to the abstract.

**Comment by plague006** [comment]
A `needs discussion` or `needs approval` kind of tag would be helpful for issues like this. I'm of the opinion that this change wouldn't necessarily be an improvement. End users don't actually gain much from knowing the relationships other than conflicts (to know what the opportunity cost is of installing a given mod). We *should* be more clear about why we're installing things, which can be covered by #1268.

**Comment by mgsdk** [comment]
I believe we did have a `discussion needed` tag for the split repos, and it is still there for the meta repo. I've taken the liberty of porting the label to this repo now as well.

**Comment by mgsdk** [comment]
As for the primary issue at hand, I do not use the feature myself. I still often visit the forum pages of the mods in order to look for recommendations/compability, but a tree view would make it easier to see the relationships at a glance.

As for the second part with the images for each mod, I think the primary issue would be to get a proper image. For the KS mods we could probably scrape the image from there, but I wonder how representative it would be in general, especially when converted to a thumbnail size. I would recommend using the forum link, or adding a new link to an album, instead.

**Comment by plague006** [comment]
As there seems to be no direct support, I'm closing this. But if someone cares enough to open a PR there also seems to be no direct opposition.
