### ISSUE TITLE
Jenkins incorrectly does not catch additional brackets in spec_version

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN#817]
Case in point is https://github.com/KSP-CKAN/NetKAN/pull/951/files where Jenkins approved the files even though they have `"spec_version" : "(v1.4)"`.

The above slipped through Jenkins but not through the netkan-bot generating the .ckan files. Result of this is a commit approved by Jenkins which upon merge does not generate the proper .ckan files into CKAN-meta.

**Comment by plague006** [comment]
I tried testing this.. and failed.
I'm not sure if jenkins didn't create the folder structure because of a bug with jenkins, or if it detected an incorrect spec_ver. If it was spec_ver, it should probably give that as feedback.

Pinging @techman83 and @mgsdk because you guys can best assess this from Jenkins' side.

Pinging @dbent in case you want to do something with this on the netkan side.

Ran 2 tests:
https://github.com/KSP-CKAN/NetKAN/pull/1958 and https://github.com/KSP-CKAN/NetKAN/pull/1959

**Comment by techman83** [comment]
@plague006 I see the issue  KSP-CKAN/NetKAN#1959

```
Extracted null as KSP version.
```

null isn't a valid name for a ksp installation. I've duplicated it in my pr overhaul of the build script and I'll fix that.

**Comment by techman83** [comment]
It doesn't pass the schema validation, so the NetKAN-bot will never commit the resulting CKAN file. Funnily enough ckan will happily install it.

We don't have a subset schema to validate NetKANs and part of the testing is NetKAN inflating the data. I've just added a test to metadata.t

**Comment by techman83** [comment]
Once KSP-CKAN/NetKAN#1948 is merged, this will be closed.
