### ISSUE TITLE
Use If-Modified-Since when fetching metadata

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#854]
Currently I am refreshing on every start which takes quite a while on my connection.
A fast mechanism to check if the mod-list changed since last refresh would be great - if the check is fast enough it could be done automatically at startup.
Ideas: HEAD of http-response, extra version file, last git-fingerprint(?)

**Comment by pjf** [comment]
#945 is in progress, which should make things *much* faster. Likewise the latest release has a bunch of optimizations to make processing the metadata much faster when we have it.

I'll pop this over to our nice-to-have, because caching our update times and sending an if-modified-since header should be achievable, and should work sensibly regardless of whose metadata we're using. Many thanks!

**Comment by HebaruSan** [comment]
If-Modified-Since doesn't work on GitHub (isaacs/github#692), but ETag might. It's sent when requesting master.tar.gz. If-None-Match doesn't seem to work either, but we could do our own HEAD requests and compare the ETag values ourselves.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

Of course this assumes that ETag actually updates correctly when the repo is changed, which I can't test till some changes are made...
