### ISSUE TITLE
Download .tgz rather than .zip of metadata

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#945]
When the CKAN was first designed, I had the impression that .zip files would be great, because there's so much repetition between .ckan documents.

However the .zip format compresses each document, but doesn't share compression info between them. Consequently, the ckan metadata download is now 1.6MB in size.

The [.tar.gz](https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz) of the same data is just 253k, a significant saving.

As far as I know we already have code to do this from @mgsdk, so we *should* just be a case off flipping to a new default repo, yes? (I was away when the code was written, so please enlighten me if we have any blockers here...)

**Comment by mgsdk** [comment]
When I do metadata tests from my own repo I always use the tar.gz since it is smaller. So it should just be "flipping the switch". However, there is some room for improvement in the code, and as late as today I noticed we don't have the same amount of tests for the two formats.

The test part is at least partially fixed by https://github.com/KSP-CKAN/CKAN-core/pull/130. To be on the safe side I would make the switch in a pre-release.

**Comment by pjf** [comment]
@mgsdk : Awesome! Thank you! :)

I'll take a look over the tgz code before making a release where we flip the default repo, but this should provide a nice speed up to our users. :)

**Comment by TeddyDD** [comment]
I suppose this should be closed now (since Veil Nebula release)

**Comment by pjf** [comment]
Oh yay! Yes, closing with great joy! :)
