### ISSUE TITLE
ENHANCEMENT: Mod Selection by line

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-CKAN/CKAN#964]
It would be convenient if, instead of having to place the pointer in the checkbox to select a mod, we could click anywhere along the line to select the desired mod.

**Comment by Postremus** [comment]
Would be a nice feature. 

----- Ursprüngliche Nachricht -----
Von: "Scott" <notifications@github.com>
Gesendet: ‎27.‎05.‎2015 06:58
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Betreff: [CKAN] REQUEST: Enhanced Selection (#964)

It would be convenient if, instead of having to place the pointer in the checkbox to select a mod, we could click anywhere along the line to select the desired mod.
