### ISSUE TITLE
Unable to update or uninstall module manager

### ISSUE THREAD

**Issue by Rcannon95** [KSP-CKAN/CKAN#968]
I have been having an issue where I can not seem to update Module Manager or uninstall it and reinstall from scratch, CKAN keeps saying it detects the dll when I have removed it and the related files from the gamedata folder. Is there anything I can do to fix this?

**Comment by Dazpoet** [comment]
Need more information. Was ModuleManager manually added from the start or installed through CKAN? In case of the latter what made it go from handled by CKAN into an autodetected stage? What kind of error are you getting?

What is your CKAN and KSP version aswell as your OS?

**Comment by Rcannon95** [comment]
Added to a clean install of KSP 1.0.2 using CKAN. It crashed mid-update and caused CKAN to "break". Win7 Professional 64bit. There is no error, it just says it auto detected the DLL, even when I remove it.

Regards,
Ryan

**Comment by pjf** [comment]
> Added to a clean install of KSP 1.0.2 using CKAN. It crashed mid-update and caused CKAN to "break". Win7 Professional 64bit. There is no error, it just says it auto detected the DLL, even when I remove it.

OMG. I know what's going on here. Our transactional (Tx) file layer puts files into their final destination, and then rolls them back if anything goes wrong. If we experience a *hard* crash in the client, the Tx layer doesn't get a chance to do a roll-back, and we have a partially written mod in the directory. Dying from an exception, having the user exit normally, and all those other things should be *soft* crashes that result in a rollback, but obviously there are some ways to get the CKAN to crash that induces this.

Our solutions would include:

1. Get everyone to use transactional filesystems. Alas, nobody does, not even me.
1. Keep some sort of a journal or state that records what we're doing during a transaction. I suspect this is fraught with peril as it will *seem* useful, but really not be.
1. Use enduring transactions, which is a whole bunch of C#/.NET magic.
1. Implement `ckan fsck` (for want of a better name) that verifies that all files are as we expect them to be in the registry (we have them checksummed, after all) and quizzes the user as to what we should do with *extra* files we find (protect/remove/repair/etc).

`ckan fsck` would likely use much of the same underlying logic as #949, insofar that we extend our knowledge of the filesystem to files which are not in the CKAN registry. At the very least `ckan fsck` can report untracked and modified files.

Alas, I have to run to a meeting. If you see this ticket in more than 2 hours' time and I haven't linked a ticket describing `ckan fsck` or equivalent, please nudge me. :)

**Comment by pjf** [comment]
Okay, I'd added to the scope of #949 to cover the `ckan fsck` ideas, since it's so closely related and that ticket is likely to turn into a constellation of individual coding tasks.

@Rcannon95 : As for recovering from your current situation, you *might* find you can:

- Manually remove ModuleManager (if it's currently showing as auto-detected)
- Run `ckan.exe scan` on the command-line, to refresh the CKAN's idea of what's installed.
- Run `ckan.exe install ModuleManager` to install MM from the CKAN. The command-line *should* let you do this, even if your system is otherwise inconsistent without MM installed, as we *should* only be testing for consistency at the end of a transaction.

**Comment by Postremus** [comment]
Isn't there a GUI plugin from Alex, which converts ad mods to regular ckan ones? Couldn't that help?

----- Ursprüngliche Nachricht -----
Von: "Paul Fenwick" <notifications@github.com>
Gesendet: ‎28.‎05.‎2015 08:56
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Betreff: Re: [CKAN] Unable to update or uninstall module manager (#968)

Okay, I'd added to the scope of #949 to cover the ckan fsck ideas, since it's so closely related and that ticket is likely to turn into a constellation of individual coding tasks.
@Rcannon95 : As for recovering from your current situation, you might find you can:
Manually remove ModuleManager (if it's currently showing as auto-detected) 
Run ckan.exe scan on the command-line, to refresh the CKAN's idea of what's installed. 
Run ckan.exe install ModuleManager to install MM from the CKAN. The command-line should let you do this, even if your system is otherwise inconsistent without MM installed, as we should only be testing for consistency at the end of a transaction.

**Comment by Rcannon95** [comment]
Update: I tired those three options that you suggested, along with a few other commands I thought might work, but I am still having the issue.

**Comment by RichardLake** [comment]
While not currently helpful when https://github.com/KSP-CKAN/CKAN-cmdline/pull/69 is merged and released the ckan.exe install fix should work.
